In [43]:
# coding: utf-8

import pandas as pd
from urllib.parse import quote

# Pull tables from Wikipedia
base  = "https://es.wikipedia.org/wiki/" 
path  = "Anexo:Ministros_de_Educación_del_Perú"
url   = base + quote(path)          # Per%C3%BA

# Add a User-Agent header to mimic a browser and avoid 403 Forbidden error
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
eduTables = pd.read_html(url, flavor="bs4",
                      attrs={"class": "wikitable"}, storage_options={"User-Agent": 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'})

In [44]:
path  = "Anexo:Ministros_de_Justicia_del_Perú"
url   = base + quote(path)          # Per%C3%BA

# Add a User-Agent header to mimic a browser and avoid 403 Forbidden error
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
otrTables = pd.read_html(url, flavor="bs4",
                      attrs={"class": "wikitable"}, storage_options={"User-Agent": 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'})

In [45]:
len(otrTables)

13

In [46]:
otr1=otrTables[1]

In [47]:
otr2=otrTables[4]

In [48]:
otr3=otrTables[5]

In [49]:
otr4=otrTables[6]

In [50]:
otr5=otrTables[7]

In [51]:
otr1.columns,otr2.columns,otr3.columns,otr4.columns,otr5.columns

(Index(['Imagen', 'Ministro', 'Presidente', 'Fecha de inicio'], dtype='object'),
 Index(['Imagen', 'Ministro', 'Presidente', 'Fecha de inicio'], dtype='object'),
 Index(['Imagen', 'Ministro', 'Presidente', 'Fecha de inicio'], dtype='object'),
 Index(['Imagen', 'Ministro', 'Presidente', 'Fecha de inicio'], dtype='object'),
 Index(['Imagen', 'Ministro', 'Presidente', 'Fecha de inicio'], dtype='object'))

In [52]:
otr_j=pd.concat([otr1,otr2,otr3,otr4,otr5])

In [53]:
otr_j.rename(columns={'Fecha de inicio':'Inicio'},inplace=True)

In [54]:
len(eduTables)

2

In [55]:
eduTables[0].head()

,Ministro,Partido,Presidente,Inicio
0,Manuel Villarán Loli,Clérigo,Andrés de Santa Cruz,5 de febrero de 1837
1,Agustín Guillermo Charún,Clérigo,Agustín Gamarra,26 de noviembre de 1839
2,Benito Laso de la Vega,Liberal,Francisco de Vidal,20 de octubre de 1842

In [56]:
otr6=eduTables[0].copy()
otr=pd.concat([otr6,otr_j],ignore_index=True)
otr

,Ministro,Partido,Presidente,Inicio,Imagen
0,Manuel Villarán Loli,Clérigo,Andrés de Santa Cruz,5 de febrero de 1837,NaN
1,Agustín Guillermo Charún,Clérigo,Agustín Gamarra,26 de noviembre de 1839,NaN
2,Benito Laso de la Vega,Liberal,Francisco de Vidal,20 de octubre de 1842,NaN
3,Bartolomé Herrera Vélez,NaN,José Rufino Echenique,1 de octubre de 1851,NaN
4,Agustín Guillermo Charún,NaN,José Rufino Echenique,26 de julio de 1852,NaN
...,...,...,...,...,...
122,Daniel Olaechea y Olaechea,NaN,Óscar R. Benavides (2.º gob.),4 de julio de 1933,NaN
123,José de la Riva Agüero y Osma,NaN,Óscar R. Benavides (2.º gob.),25 de noviembre de 1933,NaN
124,Alberto Rey de Castro y Romaña,NaN,Óscar R. Benavides (2.º gob.),19 de mayo de 1934,NaN
125,Carlos Arenas y Loayza,NaN,Óscar R. Benavides (2.º gob.),24 de diciembre de 1934,NaN
126,Ernesto Montagne Markholz,NaN,Óscar R. Benavides (2.º gob.),21 de mayo de 1935,NaN

In [57]:
otr.rename(columns={'Ministro':'Nombre'},inplace=True)
otr['Final']=otr.Inicio.shift(-1)
otr['currentEdu']=False
otr.head()

,Nombre,Partido,Presidente,Inicio,Imagen,Final,currentEdu
0,Manuel Villarán Loli,Clérigo,Andrés de Santa Cruz,5 de febrero de 1837,NaN,26 de noviembre de 1839,False
1,Agustín Guillermo Charún,Clérigo,Agustín Gamarra,26 de noviembre de 1839,NaN,20 de octubre de 1842,False
2,Benito Laso de la Vega,Liberal,Francisco de Vidal,20 de octubre de 1842,NaN,1 de octubre de 1851,False
3,Bartolomé Herrera Vélez,NaN,José Rufino Echenique,1 de octubre de 1851,NaN,26 de julio de 1852,False
4,Agustín Guillermo Charún,NaN,José Rufino Echenique,26 de julio de 1852,NaN,22 de septiembre de 1853,False

In [58]:
eduTables[1].head()

  Titular                                          Partido  \
   Imagen                     Nombre               Partido
0     NaN  Ernesto Montagne Markholz  Unión Revolucionaria
1     NaN         Óscar Arrús Grillo         Independiente
2     NaN    Pedro M. Oliveira Sayán         Independiente
3     NaN       Lino Cornejo Zegarra         Partido Civil
4     NaN   Enrique Laroza Lestonnat         Independiente

               Presidente                    Inicio                   Final
               Presidente                    Inicio                   Final
0      Óscar R. Benavides  12 de septiembre de 1935     19 de abril de 1939
1      Óscar R. Benavides       19 de abril de 1939  8 de diciembre de 1939
2  Manuel Prado Ugarteche    8 de diciembre de 1939     28 de abril de 1943
3  Manuel Prado Ugarteche       28 de abril de 1943                    1943
4  Manuel Prado Ugarteche                      1943     28 de julio de 1945

In [59]:
edu=eduTables[1].copy()
edu.columns=[b for a,b in edu.columns]
edu['currentEdu']=True
edu.head()

,Imagen,Nombre,Partido,Presidente,Inicio,Final,currentEdu
0,NaN,Ernesto Montagne Markholz,Unión Revolucionaria,Óscar R. Benavides,12 de septiembre de 1935,19 de abril de 1939,True
1,NaN,Óscar Arrús Grillo,Independiente,Óscar R. Benavides,19 de abril de 1939,8 de diciembre de 1939,True
2,NaN,Pedro M. Oliveira Sayán,Independiente,Manuel Prado Ugarteche,8 de diciembre de 1939,28 de abril de 1943,True
3,NaN,Lino Cornejo Zegarra,Partido Civil,Manuel Prado Ugarteche,28 de abril de 1943,1943,True
4,NaN,Enrique Laroza Lestonnat,Independiente,Manuel Prado Ugarteche,1943,28 de julio de 1945,True

In [60]:
educa=pd.concat([otr,edu],ignore_index=True)
educa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Nombre      214 non-null    object
 1   Partido     89 non-null     object
 2   Presidente  214 non-null    object
 3   Inicio      214 non-null    object
 4   Imagen      0 non-null      float64
 5   Final       212 non-null    object
 6   currentEdu  214 non-null    bool
dtypes: bool(1), float64(1), object(5)
memory usage: 10.4+ KB

In [61]:
edu=educa.copy()
edu.drop(columns=["Imagen"],inplace=True)

# date text cleaning

In [62]:
edu[edu["Inicio"].isnull()]

Empty DataFrame
Columns: [Nombre, Partido, Presidente, Inicio, Final, currentEdu]
Index: []

In [63]:
edu[edu["Final"].isnull()]

,Nombre,Partido,Presidente,Inicio,Final,currentEdu
126,Ernesto Montagne Markholz,NaN,Óscar R. Benavides (2.º gob.),21 de mayo de 1935,None,False
213,María Cuadros Espinoza,Independiente,José María Balcázar,17 de marzo de 2026,NaN,True

In [64]:
edu.loc[125:128,:]

,Nombre,Partido,Presidente,Inicio,Final,currentEdu
125,Carlos Arenas y Loayza,NaN,Óscar R. Benavides (2.º gob.),24 de diciembre de 1934,21 de mayo de 1935,False
126,Ernesto Montagne Markholz,NaN,Óscar R. Benavides (2.º gob.),21 de mayo de 1935,None,False
127,Ernesto Montagne Markholz,Unión Revolucionaria,Óscar R. Benavides,12 de septiembre de 1935,19 de abril de 1939,True
128,Óscar Arrús Grillo,Independiente,Óscar R. Benavides,19 de abril de 1939,8 de diciembre de 1939,True

In [65]:
edu.loc[127,"Inicio"]='21 de mayo de 1935'

In [66]:
edu.drop(126,inplace=True)
edu.reset_index(drop=True,inplace=True)

In [67]:
edu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213 entries, 0 to 212
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Nombre      213 non-null    object
 1   Partido     89 non-null     object
 2   Presidente  213 non-null    object
 3   Inicio      213 non-null    object
 4   Final       212 non-null    object
 5   currentEdu  213 non-null    bool
dtypes: bool(1), object(5)
memory usage: 8.7+ KB

In [68]:
edu[edu.Inicio.str.contains(r"del|\[",regex=True)]

,Nombre,Partido,Presidente,Inicio,Final,currentEdu
142,Jorge Basadre Grohmann,Independiente,Manuel Prado Ugarteche,28 de julio de 1956[2],octubre de 1958,True
184,Federico Salas-Guevara,Agrupación Independiente Avancemos,Alberto Fujimori,29 de julio del 2000,21 de noviembre de 2000,True
199,Martín Benavides Abanto,Independiente,Martín Vizcarra,13 de febrero de 2020[3],10 de noviembre de 2020,True
207,Magnet Márquez Ramírez,Independiente,Dina Boluarte,23 de abril del 2023,5 de septiembre de 2023,True
208,Miriam Ponce Vértiz,Independiente,Dina Boluarte,6 de septiembre de 2023[4],1 de abril de 2024,True
209,Morgan Quero Gaime,Independiente,Dina Boluarte,1 de abril de 2024[5],12 de octubre de 2025,True
210,Jorge Figueroa Guzmán,Independiente,José Jerí,14 de octubre de 2025[6],24 de febrero de 2026,True

In [69]:
edu['Inicio']=edu['Inicio'].str.replace(r'\[.*\]', '', regex=True)

In [70]:
edu[edu["Final"].isnull()]

,Nombre,Partido,Presidente,Inicio,Final,currentEdu
212,María Cuadros Espinoza,Independiente,José María Balcázar,17 de marzo de 2026,NaN,True

In [71]:
edu[edu.Inicio.str.contains(r"del|\[", regex=True, na=False)]

,Nombre,Partido,Presidente,Inicio,Final,currentEdu
184,Federico Salas-Guevara,Agrupación Independiente Avancemos,Alberto Fujimori,29 de julio del 2000,21 de noviembre de 2000,True
207,Magnet Márquez Ramírez,Independiente,Dina Boluarte,23 de abril del 2023,5 de septiembre de 2023,True

In [72]:
edu.loc[184,"Inicio"]='29 de julio de 2000'
edu.loc[207,"Inicio"]='23 de abril de 2023'

In [73]:
edu[edu.Final.str.contains(r"del|\[", regex=True, na=False)]

,Nombre,Partido,Presidente,Inicio,Final,currentEdu
194,Jaime Saavedra Chanduví,Independiente,Pedro Pablo Kuczynski,28 de julio de 2016,18 de diciembre del 2016,True

In [74]:

edu['Final']=edu['Final'].str.replace('del', 'de', regex=False)

In [75]:
edu[edu["Inicio"].str.split("de").apply(len)!=3]

,Nombre,Partido,Presidente,Inicio,Final,currentEdu
130,Enrique Laroza Lestonnat,Independiente,Manuel Prado Ugarteche,1943,28 de julio de 1945,True
143,Ulises Montoya Manfredi,Independiente,Manuel Prado Ugarteche,octubre de 1958,17 de octubre de 1958,True

In [76]:
edu[edu["Final"].str.split("de").str.len().fillna(0) != 3]

,Nombre,Partido,Presidente,Inicio,Final,currentEdu
129,Lino Cornejo Zegarra,Partido Civil,Manuel Prado Ugarteche,28 de abril de 1943,1943,True
142,Jorge Basadre Grohmann,Independiente,Manuel Prado Ugarteche,28 de julio de 1956,octubre de 1958,True
212,María Cuadros Espinoza,Independiente,José María Balcázar,17 de marzo de 2026,NaN,True

In [77]:
edu.loc[130,"Inicio"]='28 de julio de 1943'
edu.loc[129,"Final"]='28 de julio de 1943'

edu.loc[143,"Inicio"]='1 de octubre de 1958'
edu.loc[142,"Final"]='1 de octubre de 1958'

edu.loc[212,"Final"]=None

In [78]:
edu[edu.Inicio=='']

Empty DataFrame
Columns: [Nombre, Partido, Presidente, Inicio, Final, currentEdu]
Index: []

In [79]:
edu[edu.Final=='']

Empty DataFrame
Columns: [Nombre, Partido, Presidente, Inicio, Final, currentEdu]
Index: []

In [80]:
import numpy as np
from datetime import datetime, timedelta
import locale

# 1. Configurar locale (con fallback por si estás en Windows)
try:
    locale.setlocale(locale.LC_TIME, "es_ES.UTF-8")
except locale.Error:
    locale.setlocale(locale.LC_TIME, "Spanish_Spain.1252") # Windows

# Tu función lambda (agregamos validación por si hay NaN)
str_to_date = lambda x: datetime.strptime(x, "%d de %B de %Y") if pd.notna(x) else pd.NaT

edu[["Inicio", "Final"]] = edu[["Inicio", "Final"]].apply(lambda x: x.str.strip())

# Date format

In [81]:
# 2. Convertir a datetime
edu['fecha_start'] = edu['Inicio'].apply(str_to_date)
edu['fecha_end'] = edu['Final'].apply(str_to_date)

In [86]:
edu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213 entries, 0 to 212
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Nombre       213 non-null    object
 1   Partido      89 non-null     object
 2   Presidente   213 non-null    object
 3   Inicio       213 non-null    object
 4   Fin          212 non-null    object
 5   currentEdu   213 non-null    bool
 6   fecha_start  213 non-null    datetime64[ns]
 7   fecha_end    212 non-null    datetime64[ns]
 8   cartera      213 non-null    object
dtypes: bool(1), datetime64[ns](2), object(6)
memory usage: 13.6+ KB

In [85]:
edu.rename(columns={'Final':'Fin'},inplace=True)

In [83]:
edu['cartera']='Educacion'

In [87]:
edu.to_pickle("edu.pkl")