In [3]:
# coding: utf-8

import pandas as pd
from urllib.parse import quote

# Pull tables from Wikipedia
base  = "https://es.wikipedia.org/wiki/"
path  = "Anexo:Ministros_de_Economía_del_Perú"
url   = base + quote(path)          # Per%C3%BA

# Add a User-Agent header to mimic a browser and avoid 403 Forbidden error
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
mefTables = pd.read_html(url, flavor="bs4",
                      attrs={"class": "wikitable sortable"}, storage_options={"User-Agent": 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'})

In [4]:
len(mefTables)

4

In [39]:
mefTables[0].head()

,Imagen,Titular,Partido,Presidente,Fecha de inicio
0,NaN,Hipólito Unanue,NaN,José de San Martín (Protectorado),3 de agosto de 1821
1,NaN,Dionisio Vizcarra,NaN,Francisco Valdivieso (encargado del mando),23 de junio de 1823
2,NaN,Hipólito Unanue,NaN,José Bernardo de Tagle,24 de septiembre de 1823
3,NaN,José de Espinar,NaN,Simón Bolívar,19 de febrero de 1824
4,NaN,José Faustino Sánchez Carrión (Secretario Gene...,NaN,Simón Bolívar,1 de abril de 1824

In [40]:
mefTables[1].head()

,Imagen,Titular,Partido,Presidente,Fecha de inicio
0,NaN,Mariano A. Belaúnde,Partido Demócrata,Eduardo López de Romaña,8 de septiembre de 1899
1,NaN,Rafael Quiróz,NaN,Eduardo López de Romaña,8 de agosto de 1900
2,NaN,José V. Larrabure,NaN,Eduardo López de Romaña,31 de agosto de 1900
3,NaN,Domingo Almenara Butler,Partido Civil,Eduardo López de Romaña,2 de octubre de 1900
4,NaN,Adrián Ward,NaN,Eduardo López de Romaña,12 de septiembre de 1901

In [38]:
mefTables[2].head()

  Titular                                    Partido  \
   Imagen                      Nombre        Partido
0     NaN  Francisco Morales Bermúdez            s/p
1     NaN    Guillermo Marcó del Pont            s/p
2     NaN     Amílcar Vargas Gavilano            s/p
3     NaN        Luis Barúa Castañeda  Independiente
4     NaN       Walter Piazza Tanguis  Independiente

                   Presidente                                     Periodo
                   Presidente                                     Periodo
0       Juan Velasco Alvarado       1 de marzo de 1969-2 de enero de 1974
1       Juan Velasco Alvarado      2 de enero de 1974-18 de julio de 1974
2       Juan Velasco Alvarado    18 de julio de 1974-30 de agosto de 1975
3  Francisco Morales Bermúdez  2 de septiembre de 1975-16 de mayo de 1977
4  Francisco Morales Bermúdez       16 de mayo de 1977-6 de julio de 1977

In [41]:
mefTables[3].head()

  Titular                                 Partido         Presidente  \
   Imagen                   Nombre        Partido         Presidente
0     NaN       Javier Silva Ruete     Somos Perú  Valentín Paniagua
1     NaN    Pedro Pablo Kuczynski  Independiente   Alejandro Toledo
2     NaN       Javier Silva Ruete  Independiente   Alejandro Toledo
3     NaN  Jaime Quijandría Salmón  Independiente   Alejandro Toledo
4     NaN    Pedro Pablo Kuczynski  Independiente   Alejandro Toledo

                                       Periodo
                                       Periodo
0  25 de noviembre de 2000-28 de julio de 2001
1      28 de julio de 2001-11 de julio de 2002
2      12 de julio de 2002-25 de julio de 2003
3    25 de julio de 2003-16 de febrero de 2004
4   16 de febrero de 2004-16 de agosto de 2005

# concat

In [20]:
mefa=pd.concat(mefTables[:2],ignore_index=True)

In [21]:
mefa=mefa[~mefa.isnull().all(axis=1)]
mefa.drop(columns=["Imagen"],inplace=True)

In [22]:
mefa.info()

<class 'pandas.core.frame.DataFrame'>
Index: 244 entries, 0 to 244
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Titular          244 non-null    object
 1   Partido          42 non-null     object
 2   Presidente       244 non-null    object
 3   Fecha de inicio  243 non-null    object
dtypes: object(4)
memory usage: 9.5+ KB

In [43]:
mefb=pd.concat(mefTables[2::],ignore_index=True)

In [44]:
mefb.columns

MultiIndex([(   'Titular',     'Imagen'),
            (   'Titular',     'Nombre'),
            (   'Partido',    'Partido'),
            ('Presidente', 'Presidente'),
            (   'Periodo',    'Periodo')],
           )

In [45]:
mefb.columns=[b for a,b in mefb.columns]

In [46]:
mefb=mefb[~mefb.isnull().all(axis=1)]
mefb.drop(columns=["Imagen"],inplace=True)
mefb.head()

,Nombre,Partido,Presidente,Periodo
0,Francisco Morales Bermúdez,s/p,Juan Velasco Alvarado,1 de marzo de 1969-2 de enero de 1974
1,Guillermo Marcó del Pont,s/p,Juan Velasco Alvarado,2 de enero de 1974-18 de julio de 1974
2,Amílcar Vargas Gavilano,s/p,Juan Velasco Alvarado,18 de julio de 1974-30 de agosto de 1975
3,Luis Barúa Castañeda,Independiente,Francisco Morales Bermúdez,2 de septiembre de 1975-16 de mayo de 1977
4,Walter Piazza Tanguis,Independiente,Francisco Morales Bermúdez,16 de mayo de 1977-6 de julio de 1977

# date text cleaning

In [48]:
mefa[mefa["Fecha de inicio"].isnull()]

              Titular Partido      Presidente Fecha de inicio
16  Dionisio Vizcarra     NaN  José de la Mar             NaN

In [50]:
mefa.loc[16,"Fecha de inicio"]="21 de junio de 1828"

In [51]:
mefa[mefa["Fecha de inicio"].str.contains("del")]

Empty DataFrame
Columns: [Titular, Partido, Presidente, Fecha de inicio]
Index: []

In [60]:
mefa[mefa["Fecha de inicio"].str.split("de").apply(len)!=3]

,Titular,Partido,Presidente,Fecha de inicio
126,Ladislao de la Jara,NaN,Lizardo Montero,abril de 1883
210,Manuel Ugarteche,NaN,Óscar R. Benavides,octubre de 1935
234,Pedro G. Beltrán,Independiente,Manuel Prado Ugarteche,septiembre de 1959

In [61]:
mefa.loc[126,"Fecha de inicio"]="1 de abril de 1883"
mefa.loc[210,"Fecha de inicio"]="1 de octubre de 1935"
mefa.loc[234,"Fecha de inicio"]="20 de julio de 1959"

In [52]:
mefb[mefb["Periodo"].isnull()]

Empty DataFrame
Columns: [Nombre, Partido, Presidente, Periodo]
Index: []

In [53]:
mefb[mefb["Periodo"].str.contains("del")]

Empty DataFrame
Columns: [Nombre, Partido, Presidente, Periodo]
Index: []

In [75]:
mefb[mefb.loc[:,"Periodo"].str.split().apply(len)!=9]

,Nombre,Partido,Presidente,Periodo
55,Rodolfo Acuña Namihas,Independiente,José María Balcázar,17 de marzo de 2026

In [79]:
mefb[mefb.loc[:,"Periodo"].str.split("-").apply(len)!=2]

,Nombre,Partido,Presidente,Periodo
55,Rodolfo Acuña Namihas,Independiente,José María Balcázar,17 de marzo de 2026

In [83]:
mefb[["fecha_start","fecha_end"]]=mefb.loc[:,"Periodo"].str.split("-",expand=True)
mefb[["fecha_start", "fecha_end"]] = mefb[["fecha_start", "fecha_end"]].apply(lambda x: x.str.strip())

# Date format

In [64]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import locale

# 1. Configurar locale (con fallback por si estás en Windows)
try:
    locale.setlocale(locale.LC_TIME, "es_ES.UTF-8")
except locale.Error:
    locale.setlocale(locale.LC_TIME, "Spanish_Spain.1252") # Windows

# Tu función lambda (agregamos validación por si hay NaN)
str_to_date = lambda x: datetime.strptime(x, "%d de %B de %Y") if pd.notna(x) else pd.NaT

# --- Supongamos que tu columna de fechas se llama 'fecha_inicio' ---

# 2. Convertir a datetime
mefa['fecha_start'] = mefa['Fecha de inicio'].apply(str_to_date)

# 3. Desplazar (-1), restar 1 día y volver a formato texto español
mefa['fecha_end'] = (mefa['fecha_start'].shift(-1) - timedelta(days=1))



mefa

,Titular,Partido,Presidente,Fecha de inicio,fecha_start,fecha_end
0,Hipólito Unanue,NaN,José de San Martín (Protectorado),3 de agosto de 1821,1821-08-03,1823-06-22
1,Dionisio Vizcarra,NaN,Francisco Valdivieso (encargado del mando),23 de junio de 1823,1823-06-23,1823-09-23
2,Hipólito Unanue,NaN,José Bernardo de Tagle,24 de septiembre de 1823,1823-09-24,1824-02-18
3,José de Espinar,NaN,Simón Bolívar,19 de febrero de 1824,1824-02-19,1824-03-31
4,José Faustino Sánchez Carrión (Secretario Gene...,NaN,Simón Bolívar,1 de abril de 1824,1824-04-01,1824-10-27
...,...,...,...,...,...,...
240,Tulio de Andrea Marcazzolo,NaN,Fernando Belaúnde,8 de septiembre de 1967,1967-09-08,1968-01-28
241,Raúl Ferrero Rebagliati,NaN,Fernando Belaúnde,29 de enero de 1968,1968-01-29,1968-03-19
242,Francisco Morales Bermúdez,Militar,Fernando Belaúnde,20 de marzo de 1968,1968-03-20,1968-05-31
243,Manuel Ulloa Elías,Acción Popular,Fernando Belaúnde,1 de junio de 1968,1968-06-01,1968-10-02
244,Ángel Valdivia Morriberón,Militar,Juan Velasco Alvarado,3 de octubre de 1968,1968-10-03,NaT

In [85]:
# 2. Convertir a datetime
mefb['fecha_start'] = mefb['fecha_start'].apply(str_to_date)
mefb['fecha_end'] = mefb['fecha_end'].apply(str_to_date)

In [87]:
mefb.head()

,Nombre,Partido,Presidente,Periodo,fecha_start,fecha_end
0,Francisco Morales Bermúdez,s/p,Juan Velasco Alvarado,1 de marzo de 1969-2 de enero de 1974,1969-03-01,1974-01-02
1,Guillermo Marcó del Pont,s/p,Juan Velasco Alvarado,2 de enero de 1974-18 de julio de 1974,1974-01-02,1974-07-18
2,Amílcar Vargas Gavilano,s/p,Juan Velasco Alvarado,18 de julio de 1974-30 de agosto de 1975,1974-07-18,1975-08-30
3,Luis Barúa Castañeda,Independiente,Francisco Morales Bermúdez,2 de septiembre de 1975-16 de mayo de 1977,1975-09-02,1977-05-16
4,Walter Piazza Tanguis,Independiente,Francisco Morales Bermúdez,16 de mayo de 1977-6 de julio de 1977,1977-05-16,1977-07-06