In [3]:
# coding: utf-8

import pandas as pd
from urllib.parse import quote

# Pull tables from Wikipedia
base  = "https://es.wikipedia.org/wiki/"
path  = "Anexo:Gobernantes_del_Perú"
url   = base + quote(path)          # Per%C3%BA

# Add a User-Agent header to mimic a browser and avoid 403 Forbidden error
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
presisTables = pd.read_html(url, flavor="bs4", storage_options={"User-Agent": 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'})

In [4]:
len(presisTables)

8

In [6]:
presisTables[0]

,Gobernante,Gobernante.1,Periodo,Vez de Gobierno,Asunción,Título
0,NaN,José de San Martín y Matorras,3 de agosto de 1821 - 20 de septiembre de 1822,Única,Cabildo Abierto en Lima[1],Protector del Perú
1,NaN,"José Bernardo de Tagle y Portocarrero, Marqués...",19 de enero de 1822 - 21 de agosto de 1822,1.ª,"Encargado interino, por viaje de San Martín a ...",Supremo Delegado
2,NaN,José de La Mar Cortázar,22 de septiembre de 1822 - 27 de febrero de 1823,—,Elección por el Congreso de entre sus miembros[2],Suprema Junta Gubernativa del Perú
3,NaN,"José Bernardo de Tagle y Portocarrero, Marqués...",27 de febrero de 1823 - 28 de febrero de 1823,2.ª,Designado por el Congreso tras el Motín de Bal...,Jefe Interino
4,NaN,José de la Riva Agüero y Sánchez Boquete,28 de febrero de 1823 - 23 de junio de 1823,Única,Impuesto por el Motín de Balconcillo. Ratifica...,Presidente de la República
5,NaN,Francisco Valdivieso y Prada,23 de junio de 1823 - 17 de julio de 1823,Única,Elegido provisionalmente por el Congreso para ...,Encargado interino del Gobierno
6,NaN,Antonio José de Sucre y Alcalá,23 de junio de 1823 - 17 de julio de 1823,Única,Elegido provisionalmente por el Congreso para ...,Jefe Supremo Militar
7,NaN,"José Bernardo de Tagle y Portocarrero, Marqués...",17 de julio de 1823 - 16 de agosto de 1823,3.ª,"Elegido por el Congreso, delegado por Sucre[6]",Encargado del Mando
8,NaN,"José Bernardo de Tagle y Portocarrero, Marqués...",16 de agosto de 1823 - 10 de febrero de 1824,3.ª (continuación),Ratificado como Presidente de la República por...,Presidente de la República
9,NaN,Simón Bolívar,10 de febrero de 1824 - 9 de diciembre de 1826,Única,El Congreso Constituyente le otorgó la suprema...,Suprema autoridad política y militar (Dictador)
10,NaN,Simón Bolívar,9 de diciembre de 1826 - 27 de enero de 1827,Única (continuación),Constitución de 1826,Presidente Vitalicio de la República
11,NaN,Hipólito Unanue y Pavón,1 de abril de 1825 - 5 de enero de 1826,1.ª,En su calidad de vicepresidente del Consejo de...,Presidente del Consejo de Gobierno
12,NaN,José de La Mar Cortázar,5 de enero de 1826 - 25 de febrero de 1826,2.ª,Encargado del Gobierno hasta el retorno de Bol...,Presidente del Consejo de Gobierno
13,NaN,Hipólito Unanue y Pavón,25 de febrero de 1826 - 28 de junio de 1826,2.ª,Encargado,Presidente del Consejo de Gobierno
14,NaN,Andrés de Santa Cruz y Calaumana,28 de junio de 1826 - 28 de enero de 1827,1.ª,"Encargado del mando. Desde el 3-09-1826, ante ...",Presidente del Consejo de Gobierno
15,NaN,Junta de Gobierno: Andrés de Santa Cruz y Cala...,28 de enero de 1827 - 9 de junio de 1827,-,Electo por el Congreso tras la revuelta que pu...,Presidente de la Junta de Gobierno
16,NaN,Manuel Salazar y Baquíjano,9 de junio de 1827 - 22 de agosto de 1827,1.ª,En su calidad de Vicepresidente de la Repúblic...,Encargado del Poder Ejecutivo
17,NaN,José de La Mar Cortázar,9 de junio de 1827 - 5 de junio de 1829,4.ª,Elegido por el Congreso[9],Presidente de la República
18,NaN,Manuel Salazar y Baquíjano,13 de septiembre de 1828 - 5 de junio de 1829,2.ª,"Vicepresidente encargado del gobierno, por aus...",Encargado del Poder Ejecutivo
19,NaN,Antonio Gutiérrez de la Fuente,6 de junio de 1829 - 1 de septiembre de 1829,1.ª,Golpe de Estado. Encargado del mando en tanto ...,Jefe Supremo
20,NaN,Agustín Gamarra Messia,1 de septiembre de 1829 - 19 de diciembre de 1829,1.ª,Elegido por el Congreso.[10],Presidente provisorio
21,NaN,Antonio Gutiérrez de la Fuente,21 de septiembre de 1829 - 25 de noviembre de ...,2.ª,Vicepresidente provisorio encargado del gobier...,Encargado del Mando
22,NaN,Agustín Gamarra Messia,19 de diciembre de 1829 - 20 de diciembre de 1833,1.ª (continuación),Elecciones populares,Presidente de la República
23,NaN,Antonio Gutiérrez de la Fuente,5 de septiembre de 1830 - 16 de abril de 1831,3.ª,Vicepresidente de la República encargado del g...,Encargado del Mando
24,NaN,Juan Bautista Eléspuru,16 de abril de 1831 - 18 de abril de 1831,Única,"En su calidad de Prefecto de Lima, asumió inte...",Encargado del Mando
25,NaN,Andrés Reyes y Buitrón,18 de abril de 1831 - 7 de junio de 1831,1.ª,"Como Presidente del Senado, se encargó del man...",Encargado del Mando
26,NaN,Andrés Reyes y Buitrón,29 de junio de 1831 - 14 de diciembre de 1831,2.ª,"Como Presidente del Senado, se encargó del man...",Encargado del Mando
27,NaN,Manuel Tellería Vicuña,27 de septiembre de 1832 - 31 de octubre de 1832,Única,"Como Presidente del Senado, se encargó del man...",Encargado del Mando
28,NaN,José Braulio del Camporredondo Cisneros,30 de julio de 1833 - 22 de noviembre de 1833,Única,"Como Vicepresidente del Senado, se encargó del...",Encargado del Mando
29,NaN,Luis José de Orbegoso y Moncada,21 de diciembre de 1833 - 11 de agosto de 1836,Única,Elegido por la Convención Nacional (Congreso)[11],Presidente Provisorio
30,NaN,Pedro Pablo Bermúdez Ascarza,4 de enero de 1834 - 28 de abril de 1834,Única,Autoproclamado,Jefe Supremo Provisorio
31,NaN,Manuel Salazar y Baquíjano,30 de marzo de 1834 - 6 de mayo de 1834,3.ª,Encargado del mando por ausencia del president...,Supremo Delegado
32,NaN,Manuel Salazar y Baquíjano,9 de noviembre de 1834 - 23 de febrero de 1835,4.ª,Encargado del mando por ausencia de Orbegoso,Supremo Delegado
33,NaN,Juan Francisco de Vidal La Hoz,30 de diciembre de 1835 - 9 de enero de 1836,1.ª,"Presidente del Consejo de Gobierno, encargado ...",Encargado del Ejecutivo
34,NaN,Felipe Santiago Salaverry del Solar,23 de febrero de 1835 - 7 de febrero de 1836,Única,Autoproclamado,Jefe y Legislador Supremo de la República
35,NaN,Juan Ángel Bujanda,6 de abril de 1835 - 17 de mayo de 1835,Única,Encargado del gobierno en Lima por autorizació...,Encargado del Ejecutivo
36,NaN,Juan José Salas,28 de septiembre de 1835 - 14 de octubre de 1835,Única,"Vicepresidente del Consejo de Gobierno, encarg...",Encargado del Ejecutivo
37,NaN,Juan Bautista de Lavalle y Zugasti,14 de octubre de 1835 - 27 de diciembre de 1835,1.ª,"Presidente del Consejo de Gobierno, encargado ...",Encargado del Ejecutivo

In [7]:
presisTables[1]

,Gobernante,Gobernante.1,Periodo,Vez de Gobierno,Asunción,Título
0,NaN,Andrés de Santa Cruz y Calaumana,7 de febrero de 1836 - 9 de mayo de 1836,2.ª,Designado por Luis José de Orbegoso para dirig...,Jefe Superior del Ejercito Unido
1,NaN,Andrés de Santa Cruz y Calaumana,17 de marzo de 1836 - 20 de febrero de 1839,2.ª (continuación),Designación por la Asamblea de Sicuani,Protector del Sud-Perú
2,NaN,Andrés de Santa Cruz y Calaumana,6 de agosto de 1836 - 20 de febrero de 1839,2.ª (continuación),Designación por la Asamblea de Huaura,Protector del Nor-Perú
3,NaN,Andrés de Santa Cruz y Calaumana,9 de mayo de 1836 - 20 de febrero de 1839,2.ª (continuación),Designación por el Congreso de Tacna,Supremo Protector de la Confederación[13]
4,NaN,Juan Pío de Tristán y Moscoso,24 de enero de 1837 - 10 de abril de 1837,Única,Encargado,Presidente del Consejo de Gobierno

In [8]:
presisTables[2]

,0,1,2,3
0,Presidente del Estado Nor-Peruano Gobernante F...,Presidente del Estado Sud-Peruano Gobernante ...,NaN,NaN
1,Gobernante,Gobernante,Fecha de inicio,Fecha de término
2,NaN,Luis José de Orbegoso,22 de agosto de 1837,21 de agosto de 1838
3,NaN,José de la Riva-Agüero,11 de agosto de 1838,24 de enero de 1839
4,Gobernante,Gobernante,Fecha de inicio,Fecha de término
5,NaN,Juan Pío de Tristán y Moscoso,20 de enero de 1837,10 de abril de 1837
6,NaN,Ramón Herrera y Rodado,17 de septiembre de 1837,12 de octubre de 1838
7,NaN,Juan Pío de Tristán y Moscoso,12 de octubre de 1838,23 de febrero de 1839

In [9]:
presisTables[3]

,Gobernante,Gobernante.1,Fecha de inicio,Fecha de término
0,NaN,Luis José de Orbegoso,22 de agosto de 1837,21 de agosto de 1838
1,NaN,José de la Riva-Agüero,11 de agosto de 1838,24 de enero de 1839

In [10]:
presisTables[4]

,Gobernante,Gobernante.1,Fecha de inicio,Fecha de término
0,NaN,Juan Pío de Tristán y Moscoso,20 de enero de 1837,10 de abril de 1837
1,NaN,Ramón Herrera y Rodado,17 de septiembre de 1837,12 de octubre de 1838
2,NaN,Juan Pío de Tristán y Moscoso,12 de octubre de 1838,23 de febrero de 1839

In [11]:
presisTables[5]

,Gobernante,Gobernante.1,Gobernante.2,Periodo,Vez de Gobierno,Organización Política,Asunción,Título
0,NaN,NaN,Agustín Gamarra Messia,25 de agosto de 1838 - 15 de agosto de 1839,2.ª,(Militar),Proclamación por cabildo abierto en Lima duran...,Presidente de la República
1,NaN,NaN,Agustín Gamarra Messia,15 de agosto de 1839 - 10 de julio de 1840,2.ª (continuación),(Militar),Designado por el Congreso General de Huancayo[14],Presidente Provisorio
2,NaN,NaN,Agustín Gamarra Messia,10 de julio de 1840 - 18 de noviembre de 1841 (†),2.ª (continuación),(Militar),Elección popular[15],Presidente Constitucional de la República
3,NaN,NaN,Manuel Menéndez Gorozabel,18 de noviembre de 1841 - 16 de agosto de 1842,1.ª,NaN,Sucesión legal por ser el presidente del Conse...,Presidente provisorio
4,NaN,NaN,Juan Crisóstomo Torrico y Bargas,16 de agosto de 1842 - 20 de agosto de 1842,Única,(Militar),Autoproclamación,Jefe Supremo
...,...,...,...,...,...,...,...,...
113,NaN,NaN,Francisco Rafael Sagasti Hochhausler,17 de noviembre de 2020 - 28 de julio de 2021,Única,PM,Sucesión constitucional (Presidente del Congre...,Presidente Constitucional de la República
114,NaN,NaN,José Pedro Castillo Terrones,28 de julio de 2021 - 7 de diciembre de 2022,Única,PL Independiente,Elección,Presidente Constitucional de la República
115,NaN,NaN,Dina Ercilia Boluarte Zegarra,7 de diciembre de 2022 - 10 de octubre de 2025,Única,Independiente,Sucesión constitucional (Primera Vicepresident...,Presidenta Constitucional de la República
116,NaN,NaN,José Enrique Jerí Oré,10 de octubre de 2025 - 17 de febrero de 2026,Única,SP,Sucesión constitucional (Presidente del Congre...,Presidente Constitucional de la República
117,NaN,NaN,José María Balcázar Zelada,18 de febrero de 2026 - En el cargo,Única,PL,Sucesión constitucional (Presidente del Congre...,Presidente Constitucional de la República

In [13]:
presisTables[0].head()

,Gobernante,Gobernante.1,Periodo,Vez de Gobierno,Asunción,Título
0,NaN,José de San Martín y Matorras,3 de agosto de 1821 - 20 de septiembre de 1822,Única,Cabildo Abierto en Lima[1],Protector del Perú
1,NaN,"José Bernardo de Tagle y Portocarrero, Marqués...",19 de enero de 1822 - 21 de agosto de 1822,1.ª,"Encargado interino, por viaje de San Martín a ...",Supremo Delegado
2,NaN,José de La Mar Cortázar,22 de septiembre de 1822 - 27 de febrero de 1823,—,Elección por el Congreso de entre sus miembros[2],Suprema Junta Gubernativa del Perú
3,NaN,"José Bernardo de Tagle y Portocarrero, Marqués...",27 de febrero de 1823 - 28 de febrero de 1823,2.ª,Designado por el Congreso tras el Motín de Bal...,Jefe Interino
4,NaN,José de la Riva Agüero y Sánchez Boquete,28 de febrero de 1823 - 23 de junio de 1823,Única,Impuesto por el Motín de Balconcillo. Ratifica...,Presidente de la República

In [16]:
presisTables[1].head()

,Gobernante,Gobernante.1,Periodo,Vez de Gobierno,Asunción,Título
0,NaN,Andrés de Santa Cruz y Calaumana,7 de febrero de 1836 - 9 de mayo de 1836,2.ª,Designado por Luis José de Orbegoso para dirig...,Jefe Superior del Ejercito Unido
1,NaN,Andrés de Santa Cruz y Calaumana,17 de marzo de 1836 - 20 de febrero de 1839,2.ª (continuación),Designación por la Asamblea de Sicuani,Protector del Sud-Perú
2,NaN,Andrés de Santa Cruz y Calaumana,6 de agosto de 1836 - 20 de febrero de 1839,2.ª (continuación),Designación por la Asamblea de Huaura,Protector del Nor-Perú
3,NaN,Andrés de Santa Cruz y Calaumana,9 de mayo de 1836 - 20 de febrero de 1839,2.ª (continuación),Designación por el Congreso de Tacna,Supremo Protector de la Confederación[13]
4,NaN,Juan Pío de Tristán y Moscoso,24 de enero de 1837 - 10 de abril de 1837,Única,Encargado,Presidente del Consejo de Gobierno

In [19]:
presisTables[3].head()

,Gobernante,Gobernante.1,Fecha de inicio,Fecha de término
0,NaN,Luis José de Orbegoso,22 de agosto de 1837,21 de agosto de 1838
1,NaN,José de la Riva-Agüero,11 de agosto de 1838,24 de enero de 1839

In [21]:
presisTables[4].head()

,Gobernante,Gobernante.1,Fecha de inicio,Fecha de término
0,NaN,Juan Pío de Tristán y Moscoso,20 de enero de 1837,10 de abril de 1837
1,NaN,Ramón Herrera y Rodado,17 de septiembre de 1837,12 de octubre de 1838
2,NaN,Juan Pío de Tristán y Moscoso,12 de octubre de 1838,23 de febrero de 1839

In [23]:
presisTables[5].head()

,Gobernante,Gobernante.1,Gobernante.2,Periodo,Vez de Gobierno,Organización Política,Asunción,Título
0,NaN,NaN,Agustín Gamarra Messia,25 de agosto de 1838 - 15 de agosto de 1839,2.ª,(Militar),Proclamación por cabildo abierto en Lima duran...,Presidente de la República
1,NaN,NaN,Agustín Gamarra Messia,15 de agosto de 1839 - 10 de julio de 1840,2.ª (continuación),(Militar),Designado por el Congreso General de Huancayo[14],Presidente Provisorio
2,NaN,NaN,Agustín Gamarra Messia,10 de julio de 1840 - 18 de noviembre de 1841 (†),2.ª (continuación),(Militar),Elección popular[15],Presidente Constitucional de la República
3,NaN,NaN,Manuel Menéndez Gorozabel,18 de noviembre de 1841 - 16 de agosto de 1842,1.ª,NaN,Sucesión legal por ser el presidente del Conse...,Presidente provisorio
4,NaN,NaN,Juan Crisóstomo Torrico y Bargas,16 de agosto de 1842 - 20 de agosto de 1842,Única,(Militar),Autoproclamación,Jefe Supremo

In [15]:
presisTables[0].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gobernante       0 non-null      float64
 1   Gobernante.1     38 non-null     object
 2   Periodo          38 non-null     object
 3   Vez de Gobierno  38 non-null     object
 4   Asunción         38 non-null     object
 5   Título           38 non-null     object
dtypes: float64(1), object(5)
memory usage: 1.9+ KB

In [17]:
presisTables[1].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Gobernante       0 non-null      float64
 1   Gobernante.1     5 non-null      object
 2   Periodo          5 non-null      object
 3   Vez de Gobierno  5 non-null      object
 4   Asunción         5 non-null      object
 5   Título           5 non-null      object
dtypes: float64(1), object(5)
memory usage: 372.0+ bytes

In [24]:
presisTables[5].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Gobernante             0 non-null      float64
 1   Gobernante.1           0 non-null      float64
 2   Gobernante.2           118 non-null    object
 3   Periodo                118 non-null    object
 4   Vez de Gobierno        118 non-null    object
 5   Organización Política  113 non-null    object
 6   Asunción               118 non-null    object
 7   Título                 118 non-null    object
dtypes: float64(2), object(6)
memory usage: 7.5+ KB

In [31]:
presisAll=pd.concat([presisTables[0],presisTables[1],
           presisTables[5].drop(columns="Gobernante.1").rename(columns={"Gobernante.2":"Gobernante.1"})],
          ignore_index=True)

In [34]:
presisAll.columns

Index(['Gobernante', 'Gobernante.1', 'Periodo', 'Vez de Gobierno', 'Asunción',
       'Título', 'Organización Política'],
      dtype='object')

In [36]:
presisAll.drop(columns=["Gobernante"],inplace=True)
presisAll.rename(columns={"Gobernante.1":"Gobernante"}, inplace=True)
presisAll.head()

,Gobernante,Periodo,Vez de Gobierno,Asunción,Título,Organización Política
0,José de San Martín y Matorras,3 de agosto de 1821 - 20 de septiembre de 1822,Única,Cabildo Abierto en Lima[1],Protector del Perú,NaN
1,"José Bernardo de Tagle y Portocarrero, Marqués...",19 de enero de 1822 - 21 de agosto de 1822,1.ª,"Encargado interino, por viaje de San Martín a ...",Supremo Delegado,NaN
2,José de La Mar Cortázar,22 de septiembre de 1822 - 27 de febrero de 1823,—,Elección por el Congreso de entre sus miembros[2],Suprema Junta Gubernativa del Perú,NaN
3,"José Bernardo de Tagle y Portocarrero, Marqués...",27 de febrero de 1823 - 28 de febrero de 1823,2.ª,Designado por el Congreso tras el Motín de Bal...,Jefe Interino,NaN
4,José de la Riva Agüero y Sánchez Boquete,28 de febrero de 1823 - 23 de junio de 1823,Única,Impuesto por el Motín de Balconcillo. Ratifica...,Presidente de la República,NaN

In [39]:
presisAll.columns

Index(['Gobernante', 'Periodo', 'Vez de Gobierno', 'Asunción', 'Título',
       'Organización Política'],
      dtype='object')

In [40]:
presisAll.columns=['Gobernante', 'Periodo', 'Vez', 'Mecanismo', 'Titulo','Organizacion']

In [102]:
presisAll[presisAll.Periodo.str.contains(r'\[|\(',regex=True)]["Periodo"]

45     10 de julio de 1840 - 18 de noviembre de 1841 (†)
55     3 de septiembre de 1843 - 17 de febrero de 184...
70        24 de octubre de 1862 - 3 de abril de 1863 (†)
83     2 de agosto de 1868 - 22 de julio de 1872 (26 ...
84         22 de julio de 1872 - 26 de julio de 1872 (†)
103        10 de agosto de 1890 - 1 de abril de 1894 (†)
109    8 de septiembre de 1903- 18 de abril de 1904 (...
128     8 de diciembre de 1931 - 30 de abril de 1933 (†)
Name: Periodo, dtype: object

In [103]:
regex_brackets = r'\[.*?\]|\(.*?\)'

presisAll['Periodo'] = presisAll['Periodo'].str.replace(regex_brackets, '', regex=True).str.strip()

In [104]:
presisAll[presisAll.Periodo.str.split('-',expand=False).str.len()!=2]

Empty DataFrame
Columns: [Gobernante, Periodo, Vez, Mecanismo, Titulo, Organizacion, InicioGob, FinGob]
Index: []

In [105]:
presisAll[['InicioGob',"FinGob"]]=presisAll.Periodo.str.split('-',expand=True)

In [106]:
presisAll.head()

,Gobernante,Periodo,Vez,Mecanismo,Titulo,Organizacion,InicioGob,FinGob
0,José de San Martín y Matorras,3 de agosto de 1821 - 20 de septiembre de 1822,Única,Cabildo Abierto en Lima[1],Protector del Perú,NaN,3 de agosto de 1821,20 de septiembre de 1822
1,"José Bernardo de Tagle y Portocarrero, Marqués...",19 de enero de 1822 - 21 de agosto de 1822,1.ª,"Encargado interino, por viaje de San Martín a ...",Supremo Delegado,NaN,19 de enero de 1822,21 de agosto de 1822
2,José de La Mar Cortázar,22 de septiembre de 1822 - 27 de febrero de 1823,—,Elección por el Congreso de entre sus miembros[2],Suprema Junta Gubernativa del Perú,NaN,22 de septiembre de 1822,27 de febrero de 1823
3,"José Bernardo de Tagle y Portocarrero, Marqués...",27 de febrero de 1823 - 28 de febrero de 1823,2.ª,Designado por el Congreso tras el Motín de Bal...,Jefe Interino,NaN,27 de febrero de 1823,28 de febrero de 1823
4,José de la Riva Agüero y Sánchez Boquete,28 de febrero de 1823 - 23 de junio de 1823,Única,Impuesto por el Motín de Balconcillo. Ratifica...,Presidente de la República,NaN,28 de febrero de 1823,23 de junio de 1823

In [107]:
presisAll[presisAll.InicioGob.str.split(r'\s*de\s*', expand=False).str.len()!=3]

,Gobernante,Periodo,Vez,Mecanismo,Titulo,Organizacion,InicioGob,FinGob
63,Ramón Castilla y Marquesado,febrero 1854 - 5 de enero de 1855,3.ª,Autoproclamación (Sur y Centro del País) Insur...,Presidente interino,(Militar),febrero 1854,5 de enero de 1855

In [108]:
presisAll.loc[63,"InicioGob"]="13 de febrero de 1854"

In [109]:
presisAll[presisAll.FinGob.str.split(r'\s*de\s*', expand=False).str.len()!=3]

,Gobernante,Periodo,Vez,Mecanismo,Titulo,Organizacion,InicioGob,FinGob
160,José María Balcázar Zelada,18 de febrero de 2026 - En el cargo,Única,Sucesión constitucional (Presidente del Congre...,Presidente Constitucional de la República,PL,18 de febrero de 2026,En el cargo

In [110]:
presisAll.loc[83,"FinGob"]="22 de julio de 1872"
presisAll.loc[109,"FinGob"]="18 de abril de 1904"
presisAll.loc[160,"FinGob"]="28 de julio de 2026"

In [111]:
presisAll.loc[86,:]

Gobernante                   Mariano Herencia-Zevallos y Larrauri
Periodo                 27 de julio de 1872 - 2 de agosto de 1872
Vez                                                         Única
Mecanismo       Sucesión Legal (por ser el 1.º vicepresidente ...
Titulo                                Encargado del Mando Supremo
Organizacion                                            (Militar)
InicioGob                                    27 de julio de 1872
FinGob                                        2 de agosto de 1872
Name: 86, dtype: object

In [112]:
presisAll[['InicioGob', 'FinGob']] = presisAll[['InicioGob', 'FinGob']].apply(lambda x: x.str.strip())

In [13]:
from datetime import datetime
import locale

# Set Spanish locale (use es_ES.utf8 or es_ES.UTF-8 depending on OS) - windows: "Spanish_Spain" or "Spanish_Spain.1252"
locale.setlocale(locale.LC_TIME, "es_ES.UTF-8")

spanish_cellToGoodDates=lambda x: datetime.strptime(x, "%d de %B de %Y")

# Apply parsing with datetime and locale
presisAll[['startGob','endGob']]=presisAll[['InicioGob','FinGob']].map(spanish_cellToGoodDates)
presisAll

In [114]:
presisAll.to_pickle("presisAll.pkl")

In [22]:
import pandas as pd

presisAll=pd.read_pickle("presisAll.pkl")

In [5]:
presisTables[3].info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Gobernante        0 non-null      float64
 1   Gobernante.1      2 non-null      str
 2   Fecha de inicio   2 non-null      str
 3   Fecha de término  2 non-null      str
dtypes: float64(1), str(3)
memory usage: 196.0 bytes

In [6]:
presisTables[4].info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Gobernante        0 non-null      float64
 1   Gobernante.1      3 non-null      str
 2   Fecha de inicio   3 non-null      str
 3   Fecha de término  3 non-null      str
dtypes: float64(1), str(3)
memory usage: 228.0 bytes

In [14]:
bolicon=pd.concat(presisTables[3:5],ignore_index=True)

In [26]:
bolicon

,Gobernante,Gobernante.1,Fecha de inicio,Fecha de término,startGob,endGob
0,NaN,Luis José de Orbegoso,22 de agosto de 1837,21 de agosto de 1838,1837-08-22,1838-08-21
1,NaN,José de la Riva-Agüero,11 de agosto de 1838,24 de enero de 1839,1838-08-11,1839-01-24
2,NaN,Juan Pío de Tristán y Moscoso,20 de enero de 1837,10 de abril de 1837,1837-01-20,1837-04-10
3,NaN,Ramón Herrera y Rodado,17 de septiembre de 1837,12 de octubre de 1838,1837-09-17,1838-10-12
4,NaN,Juan Pío de Tristán y Moscoso,12 de octubre de 1838,23 de febrero de 1839,1838-10-12,1839-02-23

In [16]:
bolicon[['startGob','endGob']]=bolicon[['Fecha de inicio','Fecha de término']].map(spanish_cellToGoodDates)
bolicon.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Gobernante        0 non-null      float64
 1   Gobernante.1      5 non-null      str
 2   Fecha de inicio   5 non-null      str
 3   Fecha de término  5 non-null      str
 4   startGob          5 non-null      datetime64[us]
 5   endGob            5 non-null      datetime64[us]
dtypes: datetime64[us](2), float64(1), str(3)
memory usage: 372.0 bytes

In [27]:
bolicon.drop(columns=['Gobernante','Fecha de inicio','Fecha de término'],inplace=True)
bolicon.rename(columns={'Gobernante.1':'Gobernante'},inplace=True)
bolicon

                      Gobernante   startGob     endGob
0          Luis José de Orbegoso 1837-08-22 1838-08-21
1         José de la Riva-Agüero 1838-08-11 1839-01-24
2  Juan Pío de Tristán y Moscoso 1837-01-20 1837-04-10
3         Ramón Herrera y Rodado 1837-09-17 1838-10-12
4  Juan Pío de Tristán y Moscoso 1838-10-12 1839-02-23

In [24]:
presisAll.columns

Index(['Gobernante', 'Periodo', 'Vez', 'Mecanismo', 'Titulo', 'Organizacion',
       'InicioGob', 'FinGob', 'startGob', 'endGob'],
      dtype='object')

In [29]:
# presisAll.drop(columns=['Periodo', 'Vez','InicioGob', 'FinGob'],inplace=True)
presisAll.head()

,Gobernante,Mecanismo,Titulo,Organizacion,startGob,endGob
0,José de San Martín y Matorras,Cabildo Abierto en Lima[1],Protector del Perú,NaN,1821-08-03,1822-09-20
1,"José Bernardo de Tagle y Portocarrero, Marqués...","Encargado interino, por viaje de San Martín a ...",Supremo Delegado,NaN,1822-01-19,1822-08-21
2,José de La Mar Cortázar,Elección por el Congreso de entre sus miembros[2],Suprema Junta Gubernativa del Perú,NaN,1822-09-22,1823-02-27
3,"José Bernardo de Tagle y Portocarrero, Marqués...",Designado por el Congreso tras el Motín de Bal...,Jefe Interino,NaN,1823-02-27,1823-02-28
4,José de la Riva Agüero y Sánchez Boquete,Impuesto por el Motín de Balconcillo. Ratifica...,Presidente de la República,NaN,1823-02-28,1823-06-23

In [30]:
bolicon.loc[0,['Mecanismo','Titulo']]=['Designado por Asamblea','Presidente Provisorio del Nor-Peruano']
bolicon.loc[1,['Mecanismo','Titulo']]=['Designado por Presidente','Presidente Provisorio del Nor-Peruano']
bolicon.loc[3,['Mecanismo','Titulo']]=['Designado por Congreso del Estado Sud Peruano','Presidente Provisorio del Sud Perú']
bolicon.loc[4,['Mecanismo','Titulo']]=['Sucesión por Presidente saliente','Presidente Provisorio del Sud Perú']

In [32]:
bolicon.drop(index=2,inplace=True)

In [35]:
presisFull=pd.concat([presisAll,bolicon],ignore_index=True)

In [36]:
presisFull

,Gobernante,Mecanismo,Titulo,Organizacion,startGob,endGob
0,José de San Martín y Matorras,Cabildo Abierto en Lima[1],Protector del Perú,NaN,1821-08-03,1822-09-20
1,"José Bernardo de Tagle y Portocarrero, Marqués...","Encargado interino, por viaje de San Martín a ...",Supremo Delegado,NaN,1822-01-19,1822-08-21
2,José de La Mar Cortázar,Elección por el Congreso de entre sus miembros[2],Suprema Junta Gubernativa del Perú,NaN,1822-09-22,1823-02-27
3,"José Bernardo de Tagle y Portocarrero, Marqués...",Designado por el Congreso tras el Motín de Bal...,Jefe Interino,NaN,1823-02-27,1823-02-28
4,José de la Riva Agüero y Sánchez Boquete,Impuesto por el Motín de Balconcillo. Ratifica...,Presidente de la República,NaN,1823-02-28,1823-06-23
...,...,...,...,...,...,...
160,José María Balcázar Zelada,Sucesión constitucional (Presidente del Congre...,Presidente Constitucional de la República,PL,2026-02-18,2026-07-28
161,Luis José de Orbegoso,Designado por Asamblea,Presidente Provisorio del Nor-Peruano,NaN,1837-08-22,1838-08-21
162,José de la Riva-Agüero,Designado por Presidente,Presidente Provisorio del Nor-Peruano,NaN,1838-08-11,1839-01-24
163,Ramón Herrera y Rodado,Designado por Congreso del Estado Sud Peruano,Presidente Provisorio del Sud Perú,NaN,1837-09-17,1838-10-12
164,Juan Pío de Tristán y Moscoso,Sucesión por Presidente saliente,Presidente Provisorio del Sud Perú,NaN,1838-10-12,1839-02-23

In [37]:
presisFull.to_pickle('presisFull.pkl')

In [2]:
import pandas as pd

presisFull=pd.read_pickle('presisFull.pkl')

In [3]:
presisFull

,Gobernante,Mecanismo,Titulo,Organizacion,startGob,endGob
0,José de San Martín y Matorras,Cabildo Abierto en Lima[1],Protector del Perú,NaN,1821-08-03,1822-09-20
1,"José Bernardo de Tagle y Portocarrero, Marqués...","Encargado interino, por viaje de San Martín a ...",Supremo Delegado,NaN,1822-01-19,1822-08-21
2,José de La Mar Cortázar,Elección por el Congreso de entre sus miembros[2],Suprema Junta Gubernativa del Perú,NaN,1822-09-22,1823-02-27
3,"José Bernardo de Tagle y Portocarrero, Marqués...",Designado por el Congreso tras el Motín de Bal...,Jefe Interino,NaN,1823-02-27,1823-02-28
4,José de la Riva Agüero y Sánchez Boquete,Impuesto por el Motín de Balconcillo. Ratifica...,Presidente de la República,NaN,1823-02-28,1823-06-23
...,...,...,...,...,...,...
160,José María Balcázar Zelada,Sucesión constitucional (Presidente del Congre...,Presidente Constitucional de la República,PL,2026-02-18,2026-07-28
161,Luis José de Orbegoso,Designado por Asamblea,Presidente Provisorio del Nor-Peruano,NaN,1837-08-22,1838-08-21
162,José de la Riva-Agüero,Designado por Presidente,Presidente Provisorio del Nor-Peruano,NaN,1838-08-11,1839-01-24
163,Ramón Herrera y Rodado,Designado por Congreso del Estado Sud Peruano,Presidente Provisorio del Sud Perú,NaN,1837-09-17,1838-10-12
164,Juan Pío de Tristán y Moscoso,Sucesión por Presidente saliente,Presidente Provisorio del Sud Perú,NaN,1838-10-12,1839-02-23