In [1]:
# coding: utf-8

import pandas as pd
from urllib.parse import quote

# Pull tables from Wikipedia
base  = "https://es.wikipedia.org/wiki/"
path  = "Anexo:Gobernantes_del_Perú"
url   = base + quote(path)          # Per%C3%BA

# Add a User-Agent header to mimic a browser and avoid 403 Forbidden error
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
presisTables = pd.read_html(url, flavor="bs4", storage_options={"User-Agent": 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'})

In [2]:
len(presisTables)

15

In [3]:
presisTables[0].head(10)

,Retrato,Nombre,Mandato,Vez,Asunción y comentarios,Título
0,NaN,José de San Martín y Matorras,3 de agosto de 1821 - 20 de septiembre de 1822,Única,Cabildo abierto en Lima.[3][n 5],Protector del Perú
1,NaN,José Bernardo de Tagle y Portocarrero,19 de enero - 21 de agosto de 1822,1.ª,"Encargado interino, por viaje de San Martín a ...",Supremo Delegado
2,NaN,José Domingo de la Mar Cortázar,21 de septiembre de 1822 - 27 de febrero de 1823,1.ª,Elección por el Congreso de entre sus miembros...,Presidente de la Suprema Junta Gubernativa del...
3,NaN,José Bernardo de Tagle y Portocarrero,27-28 de febrero de 1823,2.ª,Elegido provisionalmente por el Congreso tras ...,Encargado del Poder Ejecutivo
4,NaN,José Mariano de la Riva-Agüero y Sánchez-Boquete,28 de febrero - 23 de junio de 1823,1.ª,Impuesto por los militares tras el Motín de Ba...,Presidente de la República
5,NaN,Francisco Valdivieso y Prada,23 de junio - 17 de julio de 1823,Única,Designado provisionalmente por el Congreso tra...,Encargado interino del despacho del Gobierno
6,NaN,Antonio José de Sucre y Alcalá,23 de junio - 17 de julio de 1823,Única,Designado provisionalmente por el Congreso par...,Jefe Supremo militar
7,NaN,José Mariano de la Riva-Agüero y Sánchez-Boquete,23 de junio - 25 de noviembre de 1823,2.ª,Autoproclamado presidente tras ser vacado por ...,Presidente de la República
8,NaN,José Bernardo de Tagle y Portocarrero,17 de julio de 1823 -,3.ª,"Delegado por Sucre,[19] ratificado por el Cong...",Jefe Supremo político y militar
9,NaN,José Bernardo de Tagle y Portocarrero,16 de agosto de 1823 -,3.ª,Nombrado presidente por el Congreso.[21],Presidente de la República

In [4]:
presisTables[0].rename(columns={'Asunción y comentarios':'Asunción'},inplace=True)

In [5]:
presisTables[1].head()

,Retrato,Nombre,Mandato,Vez,Asunción,Título
0,NaN,José Domingo de la Mar Cortázar,9 de junio de 1827 - 6 de junio de 1829,4.ª,Elegido por el Congreso.[34],Presidente de la República
1,NaN,Manuel Salazar y Baquíjano,9 de junio - 22 de agosto de 1827,1.ª,"Vicepresidente encargado del gobierno, en tant...",Encargado del Poder Ejecutivo
2,NaN,Manuel Salazar y Baquíjano,13 de septiembre de 1828 - 6 de junio de 1829,2.ª,"Vicepresidente encargado del gobierno, por aus...",Encargado del Poder Ejecutivo
3,NaN,Antonio Gutiérrez de la Fuente,6 de junio - 31 de agosto de 1829,1.ª,Golpe de Estado confabulado con Agustín Gamarr...,Jefe Supremo
4,NaN,Agustín Gamarra Messia,31 de agosto de 1829 - 19 de diciembre de 1829,1.ª,Elegido por el Congreso tras la deposición de ...,Presidente provisorio

In [6]:
presisTables[2].head()

,Retrato,Nombre,Mandato,Vez,Asunción y comentarios,Título
0,NaN,Andrés de Santa Cruz y Calaumana,17 de marzo de 1836 -,2.ª,Designación por la Asamblea de Sicuani[60],Supremo Protector del Sud-Perú
1,NaN,Andrés de Santa Cruz y Calaumana,6 de agosto de 1836 -,2.ª,Designación por la Asamblea de Huaura[61],Supremo Protector del Nor-Perú
2,NaN,Andrés de Santa Cruz y Calaumana,28 de octubre de 1836 - 20 de febrero de 1839[62],2.ª,Designación por el Congreso de Tacna[63] y rat...,Protector de la Confederación Perú-Boliviana
3,NaN,Juan Pío de Tristán y Moscoso,24 de enero - abril de 1837,1.ª,Delegado por Santa Cruz.[11],Presidente del Consejo de Gobierno
4,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
presisTables[2].rename(columns={'Asunción y comentarios':'Asunción'},inplace=True)

In [8]:
presisTables[4]

,Retrato,Nombre,Vez,Mandato
0,NaN,Luis José de Orbegoso[65],2.ª,21 de agosto de 1837 - 21 de agosto de 1838[n 10]
1,NaN,José de la Riva-Agüero[69],3.ª,11 de agosto de 1838 - 24 de enero de 1839[70]

In [9]:
presisTables[5]

,Gobernante,Gobernante.1,Vez,Mandato
0,NaN,Ramón Herrera y Rodado[71][68],Única,17 de septiembre de 1837 - 12 de octubre de 1838
1,NaN,Juan Pío de Tristán y Moscoso[72],2.ª,12 de octubre de 1838 - 20 de febrero de 1839[62]

In [10]:
presisTables[5].rename(columns={'Gobernante.1':'Nombre'},inplace=True)
presisTables[5].drop(columns=['Gobernante'],inplace=True)

In [11]:
presisTables[6].head()

,Retrato,Nombre,Mandato,Vez,Asunción,Título
0,NaN,Agustín Gamarra Messia,24 de agosto de 1838 -,2.ª,Proclamación por cabildo abierto en Lima duran...,Presidente Provisorio
1,NaN,Agustín Gamarra Messia,15 de agosto de 1839 -,2.ª (cont.),Designado por el Congreso General de Huancayo[75],Presidente Provisorio
2,NaN,Agustín Gamarra Messia,10 de julio de 1840 - 18 de noviembre de 1841 (†),2.ª (cont.),Elecciones[76],Presidente de la República
3,NaN,Antonio Gutiérrez de la Fuente,17 de octubre-17 de nov. 1837,4.ª,Cabildo abierto en Arequipa (Ejército Restaura...,Jefe Supremo de la República
4,NaN,Antonio Gutiérrez de la Fuente,22 de marzo-6 de dic. 1839,5.ª,Encargado del mando en Lima y los departamento...,Jefe Superior político y militar del Norte

In [12]:
presisTables[7].head()

,Retrato,Nombre,Mandato,Vez,Partido,Partido.1,Asunción,Título
0,NaN,Manuel Justo Pardo y Lavalle,2 de agosto de 1872 - 2 de agosto de 1876,Única,NaN,Partido Civil,Elecciones[129],Presidente Constitucional
1,NaN,Manuel Costas Arce,28 de noviembre de 1874 - 18 de enero de 1875,Única,NaN,Partido Civil,"Por ausencia del presidente Pardo, en su calid...",Encargado del Poder Ejecutivo
2,NaN,Mariano Ignacio Prado Ochoa,2 de agosto de 1876 - 23 de diciembre de 1879,2.ª,NaN,Partido Civil,Elecciones[131],Presidente Constitucional
3,NaN,Luis La Puerta de Mendoza,16 de mayo - 2 de diciembre de 1879,2.ª,NaN,Partido Civil,1.º vicepresidente encargado en tanto el presi...,Encargado del Poder Ejecutivo
4,NaN,Luis La Puerta de Mendoza,18-23 de diciembre de 1879,3.ª,NaN,Partido Civil,1.º vicepresidente encargado tras viaje del pr...,Encargado del Poder Ejecutivo

In [13]:
presisTables[8].head()

,Retrato,Nombre,Mandato,Vez,Partido,Partido.1,Asunción,Título
0,NaN,José Nicolás Baltazar Fernández de Piérola y V...,23 de diciembre de 1879 - 28 de julio de 1881,1.ª,NaN,-,Autoproclamación[136] y Cabildo Abierto de Lim...,Jefe Supremo
1,NaN,José Nicolás Baltazar Fernández de Piérola y V...,29 de julio - 28 de noviembre de 1881,1.ª (cont.),NaN,-,Designado por la Asamblea Nacional de Ayacucho...,Presidente de la República
2,NaN,Patricio Lynch,17 de enero de 1881 - 23 de octubre de 1883,-,NaN,-,Jefe político y militar chileno de la ocupació...,-
3,NaN,Francisco García-Calderón Landa,12 de marzo-10 de julio de 1881,Única,NaN,-,Elegido en Cabildo Abierto (Magdalena)[139],Presidente Provisorio
4,NaN,Francisco García-Calderón Landa,10 de julio-6 de nov. de 1881,Única (cont.),NaN,-,Ratificado por el Congreso de Chorrillos y rec...,Presidente Provisorio

In [14]:
presisTables[9].head()

,Retrato,Nombre,Mandato,Vez,Partido,Partido.1,Asunción,Título
0,NaN,José Nicolás Baltazar Fernández de Piérola y V...,8 de septiembre de 1895 - 8 de septiembre de 1899,2.ª,NaN,Partido Demócrata,"Elecciones[155] (único candidato, de facto gol...",Presidente Constitucional
1,NaN,José Gabriel Eduardo Octavio López de Romaña y...,8 de septiembre de 1899 - 8 de septiembre de 1903,Única,NaN,Partido Civil- Partido Demócrata,Elecciones[156],Presidente Constitucional
2,NaN,Manuel González de Candamo e Iriarte,8 de septiembre de 1903 - 7 de mayo de 1904,2.ª,NaN,Partido Civil,Elecciones[157] (único candidato),Presidente Constitucional
3,NaN,Serapio Calderón Lazo de la Vega,18 de abril-7 de mayo de 1904,Única,NaN,Partido Civil,2.º Vicepresidente encargado del mando por enf...,Encargado del Poder Ejecutivo
4,NaN,Serapio Calderón Lazo de la Vega,7 de mayo - 24 de septiembre de 1904,Única (cont.),NaN,Partido Civil,Sucesión constitucinoal (2.º Vicepresidente) t...,Encargado del Poder Ejecutivo (Presidente tran...

In [15]:
presisTables[10].head()

,Retrato,Nombre,Mandato,Vez,Partido,Partido.1,Asunción,Título
0,NaN,Óscar Raimundo Benavides Larrea,4 de febrero de 1914 -,1.ª,NaN,(Militar),NaN,Presidente de la Junta de Gobierno
1,NaN,Óscar Raimundo Benavides Larrea,15 de mayo de 1914 - 18 de agosto de 1915,1.ª (cont.),NaN,(Militar),NaN,Presidente Provisorio
2,NaN,José Simón Pardo y Barreda,18 de agosto de 1915 - 4 de julio de 1919,2.ª,NaN,Partido Civil,Elecciones[163],Presidente Constitucional
3,NaN,Augusto Bernardino Leguía y Salcedo,4 de julio de 1919 -,2.ª,NaN,-,"Golpe de Estado tras Elecciones, siendo entonc...",Presidente Provisorio
4,NaN,Augusto Bernardino Leguía y Salcedo,12 de octubre de 1919 -,2.ª (cont.),NaN,PDR,Ratificación de elección previa al Golpe.[165],Presidente Constitucional

In [16]:
presisTables[11].head()

,Retrato,Nombre,Mandato,Vez,Partido,Partido.1,Asunción,Título
0,NaN,Fernando Sergio Marcelo Marcos Belaúnde Terry,28 de julio de 1980 - 28 de julio de 1985,2.ª,NaN,AP,Elecciones;[194] primeras con sufragio universal,Presidente Constitucional
1,NaN,Alan Gabriel Ludwig García Pérez,28 de julio de 1985 - 28 de julio de 1990,1.ª,NaN,APRA,Elecciones[195],Presidente Constitucional
2,NaN,Alberto Kenya Fujimori Inomoto[n 14],28 de julio de 1990 -,1.ª,NaN,C90,Elecciones[197],Presidente Constitucional
3,NaN,Alberto Kenya Fujimori Inomoto[n 14],5 de abril de 1992 -,1.ª (cont.),NaN,C90,Autogolpe de Estado[198][199],Presidente del Gobierno de Emergencia y Recons...
4,NaN,Alberto Kenya Fujimori Inomoto[n 14],9 de enero de 1993 -,1.ª (cont.),NaN,C90,Ratificado por el Congreso Constituyente[200][...,Presidente Constitucional

In [17]:
 
# Generate the indices from 0 to 11, skipping 3
indices = [i for i in range(12) if i != 3]

# Extract those specific tables from your list and concat them
presisAll=pd.concat([presisTables[i] for i in indices],ignore_index=True)
presisAll

,Retrato,Nombre,Mandato,Vez,Asunción,Título,Partido,Partido.1
0,NaN,José de San Martín y Matorras,3 de agosto de 1821 - 20 de septiembre de 1822,Única,Cabildo abierto en Lima.[3][n 5],Protector del Perú,NaN,NaN
1,NaN,José Bernardo de Tagle y Portocarrero,19 de enero - 21 de agosto de 1822,1.ª,"Encargado interino, por viaje de San Martín a ...",Supremo Delegado,NaN,NaN
2,NaN,José Domingo de la Mar Cortázar,21 de septiembre de 1822 - 27 de febrero de 1823,1.ª,Elección por el Congreso de entre sus miembros...,Presidente de la Suprema Junta Gubernativa del...,NaN,NaN
3,NaN,José Bernardo de Tagle y Portocarrero,27-28 de febrero de 1823,2.ª,Elegido provisionalmente por el Congreso tras ...,Encargado del Poder Ejecutivo,NaN,NaN
4,NaN,José Mariano de la Riva-Agüero y Sánchez-Boquete,28 de febrero - 23 de junio de 1823,1.ª,Impuesto por los militares tras el Motín de Ba...,Presidente de la República,NaN,NaN
...,...,...,...,...,...,...,...,...
175,NaN,Francisco Rafael Sagasti Hochhausler,17 de noviembre de 2020 - 28 de julio de 2021,Única,Sucesión constitucional tras renuncia de Merin...,Presidente Constitucional,NaN,PM
176,NaN,José Pedro Castillo Terrones,28 de julio de 2021 - 7 de diciembre de 2022,Única,Elecciones[234],Presidente Constitucional,NaN,PL Independiente
177,NaN,Dina Ercilia Boluarte Zegarra,7 de diciembre de 2022 - 10 de octubre de 2025,Única,Sucesión constitucional tras vacancia de Casti...,Presidente Constitucional,NaN,Independiente
178,NaN,José Enrique Jerí Oré,10 de octubre de 2025 - 17 de febrero de 2026,Única,Sucesión constitucional tras vacancia de Bolua...,Presidente Constitucional,NaN,SP
179,NaN,José María Balcázar Zelada,18 de febrero de 2026 - En el cargo,Única,Sucesión constitucional tras censura de Jerí; ...,Presidente Constitucional,NaN,PL

In [18]:
presisAll.drop(columns="Partido",inplace=True)
presisAll.rename(columns={"Partido.1":"Partido"},inplace=True)

In [19]:
presisAll.columns

Index(['Retrato', 'Nombre', 'Mandato', 'Vez', 'Asunción', 'Título', 'Partido'], dtype='object')

In [20]:
# presisAll[presisAll.isnull().all(axis=1)]
presisAll.dropna(how='all',axis=0,inplace=True)
presisAll.reset_index(drop=True,inplace=True)

In [21]:
presisAll["Mandato"][presisAll.Mandato.str.contains(r'\[|\(',regex=True)]

36     25 de febrero de 1835 - 7 de febrero de 1836 (...
43     28 de octubre de 1836 - 20 de febrero de 1839[62]
45     21 de agosto de 1837 - 21 de agosto de 1838[n 10]
46        11 de agosto de 1838 - 24 de enero de 1839[70]
48     12 de octubre de 1838 - 20 de febrero de 1839[62]
51     10 de julio de 1840 - 18 de noviembre de 1841 (†)
70     3 de septiembre de 1843 - 17 de febrero de 184...
71           17 de febrero - 11 de diciembre de 1844[94]
85        24 de octubre de 1862 - 3 de abril de 1863 (†)
92         31 de agosto de 1867- 7 de enero de 1868[114]
93               12 de octubre - 7 de enero de 1868[117]
98     2 de agosto de 1868 - 22 de julio de 1872 (26 ...
99                            22-26 de julio de 1872 (†)
111    6 de noviembre de 1881 - 28 de octubre de 1883...
118        10 de agosto de 1890 - 1 de abril de 1894 (†)
139                         1 de marzo de 1931 (6 horas)
143     8 de diciembre de 1931 - 30 de abril de 1933 (†)
144                           11-14 de marzo de 1933 (†)
173    De forma insólita, el Poder Ejecutivo de la Re...
Name: Mandato, dtype: object

In [22]:
presisAll.drop(index=[173],inplace=True)
presisAll.reset_index(drop=True,inplace=True)

In [23]:
presisAll[['Periodo','temp']]=presisAll["Mandato"].str.split(r'\[|\(',regex=True,expand=True)

In [24]:
regex_brackets = r'\[.*?\]|\(.*?\)'

# presisAll['Periodo'] = 
presisAll['Periodo'].str.replace(regex_brackets, '', regex=True).str.strip()

0        3 de agosto de 1821 - 20 de septiembre de 1822
1                    19 de enero - 21 de agosto de 1822
2      21 de septiembre de 1822 - 27 de febrero de 1823
3                              27-28 de febrero de 1823
4                   28 de febrero - 23 de junio de 1823
                             ...
173       17 de noviembre de 2020 - 28 de julio de 2021
174        28 de julio de 2021 - 7 de diciembre de 2022
175      7 de diciembre de 2022 - 10 de octubre de 2025
176       10 de octubre de 2025 - 17 de febrero de 2026
177                 18 de febrero de 2026 - En el cargo
Name: Periodo, Length: 178, dtype: object

In [25]:
presisAll[presisAll.Periodo.str.split('-',expand=False).str.len()!=2]

,Retrato,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp
139,NaN,Francisco Mariano Holguín Maldonado,1 de marzo de 1931 (6 horas),Única,Designación presidencial transitoria tras renu...,Presidente de la Asamblea de Notables,(Religioso),1 de marzo de 1931,6 horas)

In [26]:
presisAll.loc[139,"Periodo"]="1 de marzo de 1931 - 1 de marzo de 1931"

In [27]:
presisAll[['InicioGob',"FinGob"]]=presisAll.Periodo.str.split('-',expand=True)

In [28]:
presisAll.head()

,Retrato,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
0,NaN,José de San Martín y Matorras,3 de agosto de 1821 - 20 de septiembre de 1822,Única,Cabildo abierto en Lima.[3][n 5],Protector del Perú,NaN,3 de agosto de 1821 - 20 de septiembre de 1822,None,3 de agosto de 1821,20 de septiembre de 1822
1,NaN,José Bernardo de Tagle y Portocarrero,19 de enero - 21 de agosto de 1822,1.ª,"Encargado interino, por viaje de San Martín a ...",Supremo Delegado,NaN,19 de enero - 21 de agosto de 1822,None,19 de enero,21 de agosto de 1822
2,NaN,José Domingo de la Mar Cortázar,21 de septiembre de 1822 - 27 de febrero de 1823,1.ª,Elección por el Congreso de entre sus miembros...,Presidente de la Suprema Junta Gubernativa del...,NaN,21 de septiembre de 1822 - 27 de febrero de 1823,None,21 de septiembre de 1822,27 de febrero de 1823
3,NaN,José Bernardo de Tagle y Portocarrero,27-28 de febrero de 1823,2.ª,Elegido provisionalmente por el Congreso tras ...,Encargado del Poder Ejecutivo,NaN,27-28 de febrero de 1823,None,27,28 de febrero de 1823
4,NaN,José Mariano de la Riva-Agüero y Sánchez-Boquete,28 de febrero - 23 de junio de 1823,1.ª,Impuesto por los militares tras el Motín de Ba...,Presidente de la República,NaN,28 de febrero - 23 de junio de 1823,None,28 de febrero,23 de junio de 1823

In [29]:
presisAll[presisAll.InicioGob.str.split(r'\s*de\s*', expand=False).str.len()!=3]

,Retrato,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
1,NaN,José Bernardo de Tagle y Portocarrero,19 de enero - 21 de agosto de 1822,1.ª,"Encargado interino, por viaje de San Martín a ...",Supremo Delegado,NaN,19 de enero - 21 de agosto de 1822,None,19 de enero,21 de agosto de 1822
3,NaN,José Bernardo de Tagle y Portocarrero,27-28 de febrero de 1823,2.ª,Elegido provisionalmente por el Congreso tras ...,Encargado del Poder Ejecutivo,NaN,27-28 de febrero de 1823,None,27,28 de febrero de 1823
4,NaN,José Mariano de la Riva-Agüero y Sánchez-Boquete,28 de febrero - 23 de junio de 1823,1.ª,Impuesto por los militares tras el Motín de Ba...,Presidente de la República,NaN,28 de febrero - 23 de junio de 1823,None,28 de febrero,23 de junio de 1823
5,NaN,Francisco Valdivieso y Prada,23 de junio - 17 de julio de 1823,Única,Designado provisionalmente por el Congreso tra...,Encargado interino del despacho del Gobierno,NaN,23 de junio - 17 de julio de 1823,None,23 de junio,17 de julio de 1823
6,NaN,Antonio José de Sucre y Alcalá,23 de junio - 17 de julio de 1823,Única,Designado provisionalmente por el Congreso par...,Jefe Supremo militar,NaN,23 de junio - 17 de julio de 1823,None,23 de junio,17 de julio de 1823
...,...,...,...,...,...,...,...,...,...,...,...
147,NaN,Alfredo Solf y Muro,3-31 de mayo de 1942,Única,Encargado interino durante el viaje de Manuel ...,-,-,3-31 de mayo de 1942,None,3,31 de mayo de 1942
151,NaN,Zenón Noriega Agüero,29 de octubre-1 de nov. de 1948,1.ª,Presidente interino de la Junta Militar mientr...,Presidente de la Junta Militar de Gobierno,(Militar),29 de octubre-1 de nov. de 1948,None,29 de octubre,1 de nov. de 1948
152,NaN,Zenón Noriega Agüero,1 de junio-28 de julio de 1950,2.ª,De iure presidente interino de la Junta Milita...,Presidente de la Junta Militar de Gobierno,(Militar),1 de junio-28 de julio de 1950,None,1 de junio,28 de julio de 1950
165,NaN,Alberto Kenya Fujimori Inomoto[n 14],28 de julio - 21 de noviembre de 2000,3.ª (cont.),Elecciones[203] (fraude electoral),Presidente Constitucional,Perú 2000,28 de julio - 21 de noviembre de 2000,None,28 de julio,21 de noviembre de 2000
172,NaN,Manuel Arturo Merino de Lama,10-15 de noviembre de 2020,Única,Sucesión constitucional tras vacancia de Vizca...,Presidente Constitucional[n 15],AP,10-15 de noviembre de 2020,None,10,15 de noviembre de 2020

In [30]:
import pandas as pd
import re

# 1. Extract the year from FinGob (4 digits)
years = presisAll["FinGob"].str.extract(r"(\d{4})")[0]

# 2. Extract the month from FinGob (e.g., 'marzo', 'enero')
months = presisAll["FinGob"].str.extract(r"de\s+([a-zA-ZñÑ]+)\s+de")[0]


# 3. Smart fix function
def fix_col1(row, year, month):
    val = str(row["InicioGob"]).strip()

    # Case C: If it ALREADY ends with a 4-digit year, do nothing
    if re.search(r"\d{4}$", val):
        return val

    # Case A: If it's just a number (e.g., "10"), add month and year
    if val.isdigit():
        return f"{val} de {month} de {year}"

    # Case B: If it has text (e.g., "19 de enero") but no year, add year
    else:
        return f"{val} de {year}"


# 4. Apply and ASSIGN it back to the column
presisAll["InicioGob"] = presisAll.apply(
    lambda r: fix_col1(r, years[r.name], months[r.name]), axis=1
)

In [31]:
presisAll[presisAll.InicioGob.str.split(r'\s*de\s*', expand=False).str.len()!=3]

,Retrato,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
60,NaN,Juan Bautista de Lavalle y Zugasti,agosto-octubre de 1842,2.ª,Presidente del Consejo de Gobierno encargado d...,Encargado del Poder Ejecutivo,NaN,agosto-octubre de 1842,None,agosto de 1842,octubre de 1842

In [32]:
presisAll.loc[60,"InicioGob"]="20 de agosto de 1842"
presisAll.loc[60,"FinGob"]="20 de octubre de 1842"
presisAll.loc[65,"InicioGob"]="28 de enero de 1843"

In [33]:
presisAll[presisAll.InicioGob.str.split(r'\s*de\s*', expand=False).str.len()!=3]

Empty DataFrame
Columns: [Retrato, Nombre, Mandato, Vez, Asunción, Título, Partido, Periodo, temp, InicioGob, FinGob]
Index: []

In [34]:
presisAll[presisAll.FinGob.str.split(r'\s*de\s*', expand=False).str.len()!=3]

,Retrato,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
8,NaN,José Bernardo de Tagle y Portocarrero,17 de julio de 1823 -,3.ª,"Delegado por Sucre,[19] ratificado por el Cong...",Jefe Supremo político y militar,NaN,17 de julio de 1823 -,None,17 de julio de 1823,
9,NaN,José Bernardo de Tagle y Portocarrero,16 de agosto de 1823 -,3.ª,Nombrado presidente por el Congreso.[21],Presidente de la República,NaN,16 de agosto de 1823 -,None,16 de agosto de 1823,
41,NaN,Andrés de Santa Cruz y Calaumana,17 de marzo de 1836 -,2.ª,Designación por la Asamblea de Sicuani[60],Supremo Protector del Sud-Perú,NaN,17 de marzo de 1836 -,None,17 de marzo de 1836,
42,NaN,Andrés de Santa Cruz y Calaumana,6 de agosto de 1836 -,2.ª,Designación por la Asamblea de Huaura[61],Supremo Protector del Nor-Perú,NaN,6 de agosto de 1836 -,None,6 de agosto de 1836,
44,NaN,Juan Pío de Tristán y Moscoso,24 de enero - abril de 1837,1.ª,Delegado por Santa Cruz.[11],Presidente del Consejo de Gobierno,NaN,24 de enero - abril de 1837,None,24 de enero de 1837,abril de 1837
49,NaN,Agustín Gamarra Messia,24 de agosto de 1838 -,2.ª,Proclamación por cabildo abierto en Lima duran...,Presidente Provisorio,NaN,24 de agosto de 1838 -,None,24 de agosto de 1838,
50,NaN,Agustín Gamarra Messia,15 de agosto de 1839 -,2.ª (cont.),Designado por el Congreso General de Huancayo[75],Presidente Provisorio,NaN,15 de agosto de 1839 -,None,15 de agosto de 1839,
52,NaN,Antonio Gutiérrez de la Fuente,17 de octubre-17 de nov. 1837,4.ª,Cabildo abierto en Arequipa (Ejército Restaura...,Jefe Supremo de la República,NaN,17 de octubre-17 de nov. 1837,None,17 de octubre de 1837,17 de nov. 1837
53,NaN,Antonio Gutiérrez de la Fuente,22 de marzo-6 de dic. 1839,5.ª,Encargado del mando en Lima y los departamento...,Jefe Superior político y militar del Norte,NaN,22 de marzo-6 de dic. 1839,None,22 de marzo de 1839,6 de dic. 1839
55,NaN,Manuel Menéndez Gorozabel,28 de agosto-23 de sept. 1840,1.ª,Encargado interino por enfermedad de Gamarra.[...,Encargado del Poder Ejecutivo,NaN,28 de agosto-23 de sept. 1840,None,28 de agosto de 1840,23 de sept. 1840
57,NaN,Manuel Menéndez Gorozabel,13 de julio-18 de nov. 1841,3.ª,Encargado por salida de Gamarra rumbo a Bolivi...,Encargado del Poder Ejecutivo,NaN,13 de julio-18 de nov. 1841,None,13 de julio de 1841,18 de nov. 1841
61,NaN,Juan Francisco de Vidal La Hoz,28 de julio de 1842 -,2.ª,"Segundo vicepresidente del Consejo de Estado, ...",Encargado del Poder Ejecutivo,NaN,28 de julio de 1842 -,None,28 de julio de 1842,
62,NaN,Juan Francisco de Vidal La Hoz,17 de octubre de 1842 -,2.ª (cont.),Victoria contra Torrico en la batalla de Agua ...,Encargado del Poder Ejecutivo (Presidente tran...,NaN,17 de octubre de 1842 -,None,17 de octubre de 1842,
77,NaN,Ramón Castilla y Marquesado,1 de mayo de 1854 -,3.ª,Autoproclamación en el Sur en reacción a escán...,Presidente Provisorio,NaN,1 de mayo de 1854 -,None,1 de mayo de 1854,
78,NaN,Ramón Castilla y Marquesado,5 de enero de 1855 -,3.ª (cont.),Triunfo de la revolución liberal en la batalla...,Presidente Provisorio,NaN,5 de enero de 1855 -,None,5 de enero de 1855,
90,NaN,Mariano Ignacio Prado Ochoa,28 de noviembre de 1865 -,1.ª,Autoproclamación tras revolución nacionalista[...,Jefe Supremo Provisorio,NaN,28 de noviembre de 1865 -,None,28 de noviembre de 1865,
91,NaN,Mariano Ignacio Prado Ochoa,15 de febrero de 1867 -,1.ª (cont.),Designado por el Congreso[113],Presidente Provisorio,NaN,15 de febrero de 1867 -,None,15 de febrero de 1867,
94,NaN,Pedro Diez Canseco Corbacho,23 de septiembre de 1867 -,3.ª,Autoproclamación en Arequipa (2.º vicepresiden...,Encargado del Poder Ejecutivo,NaN,23 de septiembre de 1867 -,None,23 de septiembre de 1867,
112,NaN,Miguel Iglesias Pino de Arce,31 de agosto de 1882 -,Única,Autoproclamación en Cajamarca (Grito de Montán...,Jefe Supremo,(Militar),31 de agosto de 1882 -,None,31 de agosto de 1882,
113,NaN,Miguel Iglesias Pino de Arce,30 de diciembre de 1882 -,Única (cont.),Elegido por la Asamblea de Montán (Cajamarca)[...,Presidente Regenerador,(Militar),30 de diciembre de 1882 -,None,30 de diciembre de 1882,
130,NaN,Óscar Raimundo Benavides Larrea,4 de febrero de 1914 -,1.ª,NaN,Presidente de la Junta de Gobierno,(Militar),4 de febrero de 1914 -,None,4 de febrero de 1914,
133,NaN,Augusto Bernardino Leguía y Salcedo,4 de julio de 1919 -,2.ª,"Golpe de Estado tras Elecciones, siendo entonc...",Presidente Provisorio,-,4 de julio de 1919 -,None,4 de julio de 1919,
134,NaN,Augusto Bernardino Leguía y Salcedo,12 de octubre de 1919 -,2.ª (cont.),Ratificación de elección previa al Golpe.[165],Presidente Constitucional,PDR,12 de octubre de 1919 -,None,12 de octubre de 1919,
135,NaN,Augusto Bernardino Leguía y Salcedo,12 de octubre de 1924 -,3.ª (cont.),Elecciones (único candidato),Presidente Constitucional,PDR,12 de octubre de 1924 -,None,12 de octubre de 1924,
149,NaN,Manuel Arturo Odría Amoretti,27 de octubre de 1948 -,1.ª,Golpe de Estado[184][185],Presidente de la Junta Militar de Gobierno,(Militar),27 de octubre de 1948 -,None,27 de octubre de 1948,
161,NaN,Alberto Kenya Fujimori Inomoto[n 14],28 de julio de 1990 -,1.ª,Elecciones[197],Presidente Constitucional,C90,28 de julio de 1990 -,None,28 de julio de 1990,
162,NaN,Alberto Kenya Fujimori Inomoto[n 14],5 de abril de 1992 -,1.ª (cont.),Autogolpe de Estado[198][199],Presidente del Gobierno de Emergencia y Recons...,C90,5 de abril de 1992 -,None,5 de abril de 1992,
163,NaN,Alberto Kenya Fujimori Inomoto[n 14],9 de enero de 1993 -,1.ª (cont.),Ratificado por el Congreso Constituyente[200][...,Presidente Constitucional,C90,9 de enero de 1993 -,None,9 de enero de 1993,
164,NaN,Alberto Kenya Fujimori Inomoto[n 14],28 de julio de 1995 -,2.ª (cont.),Elecciones[202],Presidente Constitucional,C90-NM,28 de julio de 1995 -,None,28 de julio de 1995,
177,NaN,José María Balcázar Zelada,18 de febrero de 2026 - En el cargo,Única,Sucesión constitucional tras censura de Jerí; ...,Presidente Constitucional,PL,18 de febrero de 2026 - En el cargo,None,18 de febrero de 2026,En el cargo

In [35]:
presisAll.loc[8,"FinGob"]="16 de agosto de 1823"
presisAll.loc[9,"FinGob"]="18 de noviembre de 1823"


presisAll.loc[41,"FinGob"]="20 de febrero de 1839"
presisAll.loc[42,"FinGob"]="20 de febrero de 1839"

presisAll.loc[44,"FinGob"]="10 de abril de 1837"

presisAll.loc[49,"FinGob"]="15 de agosto de 1839"
presisAll.loc[50,"FinGob"]="11 de julio de 1840"

presisAll.loc[52,"FinGob"]="17 de noviembre de 1837"
presisAll.loc[53,"FinGob"]="6 de diciembre de 1839"

presisAll.loc[55,"FinGob"]="23 de septiembre de 1840"
presisAll.loc[56,"FinGob"]="28 de junio de 1841"
presisAll.loc[57,"FinGob"]="18 de noviembre de 1841"

presisAll.loc[61,"FinGob"]="16 de agosto de 1842"
presisAll.loc[62,"FinGob"]="28 de octubre de 1842"

presisAll.loc[73,"FinGob"]="7 de octubre de 1844"

presisAll.loc[77,"FinGob"]="5 de enero de 1855"
presisAll.loc[78,"FinGob"]="24 de octubre de 1858"

In [36]:
presisAll[presisAll.FinGob.str.split(r'\s*de\s*', expand=False).str.len()!=3]

,Retrato,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
90,NaN,Mariano Ignacio Prado Ochoa,28 de noviembre de 1865 -,1.ª,Autoproclamación tras revolución nacionalista[...,Jefe Supremo Provisorio,NaN,28 de noviembre de 1865 -,None,28 de noviembre de 1865,
91,NaN,Mariano Ignacio Prado Ochoa,15 de febrero de 1867 -,1.ª (cont.),Designado por el Congreso[113],Presidente Provisorio,NaN,15 de febrero de 1867 -,None,15 de febrero de 1867,
94,NaN,Pedro Diez Canseco Corbacho,23 de septiembre de 1867 -,3.ª,Autoproclamación en Arequipa (2.º vicepresiden...,Encargado del Poder Ejecutivo,NaN,23 de septiembre de 1867 -,None,23 de septiembre de 1867,
112,NaN,Miguel Iglesias Pino de Arce,31 de agosto de 1882 -,Única,Autoproclamación en Cajamarca (Grito de Montán...,Jefe Supremo,(Militar),31 de agosto de 1882 -,None,31 de agosto de 1882,
113,NaN,Miguel Iglesias Pino de Arce,30 de diciembre de 1882 -,Única (cont.),Elegido por la Asamblea de Montán (Cajamarca)[...,Presidente Regenerador,(Militar),30 de diciembre de 1882 -,None,30 de diciembre de 1882,
130,NaN,Óscar Raimundo Benavides Larrea,4 de febrero de 1914 -,1.ª,NaN,Presidente de la Junta de Gobierno,(Militar),4 de febrero de 1914 -,None,4 de febrero de 1914,
133,NaN,Augusto Bernardino Leguía y Salcedo,4 de julio de 1919 -,2.ª,"Golpe de Estado tras Elecciones, siendo entonc...",Presidente Provisorio,-,4 de julio de 1919 -,None,4 de julio de 1919,
134,NaN,Augusto Bernardino Leguía y Salcedo,12 de octubre de 1919 -,2.ª (cont.),Ratificación de elección previa al Golpe.[165],Presidente Constitucional,PDR,12 de octubre de 1919 -,None,12 de octubre de 1919,
135,NaN,Augusto Bernardino Leguía y Salcedo,12 de octubre de 1924 -,3.ª (cont.),Elecciones (único candidato),Presidente Constitucional,PDR,12 de octubre de 1924 -,None,12 de octubre de 1924,
149,NaN,Manuel Arturo Odría Amoretti,27 de octubre de 1948 -,1.ª,Golpe de Estado[184][185],Presidente de la Junta Militar de Gobierno,(Militar),27 de octubre de 1948 -,None,27 de octubre de 1948,
161,NaN,Alberto Kenya Fujimori Inomoto[n 14],28 de julio de 1990 -,1.ª,Elecciones[197],Presidente Constitucional,C90,28 de julio de 1990 -,None,28 de julio de 1990,
162,NaN,Alberto Kenya Fujimori Inomoto[n 14],5 de abril de 1992 -,1.ª (cont.),Autogolpe de Estado[198][199],Presidente del Gobierno de Emergencia y Recons...,C90,5 de abril de 1992 -,None,5 de abril de 1992,
163,NaN,Alberto Kenya Fujimori Inomoto[n 14],9 de enero de 1993 -,1.ª (cont.),Ratificado por el Congreso Constituyente[200][...,Presidente Constitucional,C90,9 de enero de 1993 -,None,9 de enero de 1993,
164,NaN,Alberto Kenya Fujimori Inomoto[n 14],28 de julio de 1995 -,2.ª (cont.),Elecciones[202],Presidente Constitucional,C90-NM,28 de julio de 1995 -,None,28 de julio de 1995,
177,NaN,José María Balcázar Zelada,18 de febrero de 2026 - En el cargo,Única,Sucesión constitucional tras censura de Jerí; ...,Presidente Constitucional,PL,18 de febrero de 2026 - En el cargo,None,18 de febrero de 2026,En el cargo

In [37]:
presisAll.loc[90,"FinGob"]="15 de febrero de 1867"
presisAll.loc[91,"FinGob"]="31 de agosto de 1867"

presisAll.loc[94,"FinGob"]="7 de enero de 1868"

presisAll.loc[104,"FinGob"]="2 de diciembre de 1879"

presisAll.loc[112,"FinGob"]="30 de diciembre de 1882"
presisAll.loc[113,"FinGob"]="1 de marzo de 1884"

presisAll.loc[130,"FinGob"]="15 de mayo de 1914"

presisAll.loc[133,"FinGob"]="12 de octubre de 1919"
presisAll.loc[134,"FinGob"]="12 de octubre de 1924"
presisAll.loc[135,"FinGob"]="12 de octubre de 1929"

presisAll.loc[149,"FinGob"]="1 de junio de 1950"

In [38]:
presisAll[presisAll.FinGob.str.split(r'\s*de\s*', expand=False).str.len()!=3]

,Retrato,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
161,NaN,Alberto Kenya Fujimori Inomoto[n 14],28 de julio de 1990 -,1.ª,Elecciones[197],Presidente Constitucional,C90,28 de julio de 1990 -,None,28 de julio de 1990,
162,NaN,Alberto Kenya Fujimori Inomoto[n 14],5 de abril de 1992 -,1.ª (cont.),Autogolpe de Estado[198][199],Presidente del Gobierno de Emergencia y Recons...,C90,5 de abril de 1992 -,None,5 de abril de 1992,
163,NaN,Alberto Kenya Fujimori Inomoto[n 14],9 de enero de 1993 -,1.ª (cont.),Ratificado por el Congreso Constituyente[200][...,Presidente Constitucional,C90,9 de enero de 1993 -,None,9 de enero de 1993,
164,NaN,Alberto Kenya Fujimori Inomoto[n 14],28 de julio de 1995 -,2.ª (cont.),Elecciones[202],Presidente Constitucional,C90-NM,28 de julio de 1995 -,None,28 de julio de 1995,
177,NaN,José María Balcázar Zelada,18 de febrero de 2026 - En el cargo,Única,Sucesión constitucional tras censura de Jerí; ...,Presidente Constitucional,PL,18 de febrero de 2026 - En el cargo,None,18 de febrero de 2026,En el cargo

In [39]:
presisAll.loc[161,"FinGob"]="5 de abril de 1992"
presisAll.loc[162,"FinGob"]="9 de enero de 1993"
presisAll.loc[163,"FinGob"]="28 de julio de 1995"
presisAll.loc[164,"FinGob"]="28 de julio de 2000"
presisAll.loc[177,"FinGob"]=None

In [40]:
presisAll[presisAll.FinGob.str.split(r'\s*de\s*', expand=False).str.len()!=3]

,Retrato,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
177,NaN,José María Balcázar Zelada,18 de febrero de 2026 - En el cargo,Única,Sucesión constitucional tras censura de Jerí; ...,Presidente Constitucional,PL,18 de febrero de 2026 - En el cargo,None,18 de febrero de 2026,None

In [41]:
import pandas as pd

# The regex pattern: looks for anything that isn't letters/numbers, whitespace, or a hyphen
pattern = r'[^\w\s\-]'

# Check both columns (using na=False to safely handle any missing values)
has_punctuation = (
    presisAll['InicioGob'].str.contains(pattern, regex=True, na=False) | 
    presisAll['FinGob'].str.contains(pattern, regex=True, na=False)
)

# Display the matching rows
presisAll[has_punctuation][['InicioGob', 'FinGob']]

                 InicioGob             FinGob
110    10 de julio de 1881  6 de nov. de 1881
151  29 de octubre de 1948  1 de nov. de 1948

In [42]:
presisAll.loc[110,"FinGob"]="6 de noviembre de 1881"
presisAll.loc[151,"FinGob"]="1 de noviembre de 1948"

In [43]:
presisAll[['InicioGob', 'FinGob']] = presisAll[['InicioGob', 'FinGob']].apply(lambda x: x.str.strip())

In [44]:
presisAll[['InicioGob', 'FinGob']]

                    InicioGob                    FinGob
0         3 de agosto de 1821  20 de septiembre de 1822
1         19 de enero de 1822      21 de agosto de 1822
2    21 de septiembre de 1822     27 de febrero de 1823
3       27 de febrero de 1823     28 de febrero de 1823
4       28 de febrero de 1823       23 de junio de 1823
..                        ...                       ...
173   17 de noviembre de 2020       28 de julio de 2021
174       28 de julio de 2021    7 de diciembre de 2022
175    7 de diciembre de 2022     10 de octubre de 2025
176     10 de octubre de 2025     17 de febrero de 2026
177     18 de febrero de 2026                      None

[178 rows x 2 columns]

In [45]:
presisAll.drop(columns=['Retrato'], inplace=True)

In [46]:
presisAll.Vez.value_counts()

Vez
Única            55
1.ª              37
2.ª              36
3.ª              12
1.ª (cont.)       9
4.ª               7
3.ª (cont.)       6
2.ª (cont.)       6
Única (cont.)     4
2.º               2
5.ª               1
1.º               1
-                 1
4.ª (cont.)       1
Name: count, dtype: int64

In [47]:
presisAll[presisAll.Vez=='-']

,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
108,Patricio Lynch,17 de enero de 1881 - 23 de octubre de 1883,-,Jefe político y militar chileno de la ocupació...,-,-,17 de enero de 1881 - 23 de octubre de 1883,None,17 de enero de 1881,23 de octubre de 1883

In [48]:
presisAll.loc[108,"Vez"]=0
presisAll.loc[108,"Título"]="Jefe político y militar por Chile"
presisAll.loc[108,"Partido"]="Chile_invasión"

In [49]:
presisAll[presisAll.Vez.str.contains('cont.',na=False)]

,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
10,José Bernardo de Tagle y Portocarrero,18 de noviembre de 1823 - 10 de febrero de 1824,3.ª (cont.),Ratificado según el flamante texto constitucio...,Presidente Constitucional de la República,NaN,18 de noviembre de 1823 - 10 de febrero de 1824,None,18 de noviembre de 1823,10 de febrero de 1824
18,Andrés de Santa Cruz y Calaumana,27 de enero - 9 de junio de 1827,1.ª (cont.),Gobernante de facto tras la revuelta que puso ...,Presidente del Consejo de Gobierno[n 8],NaN,27 de enero - 9 de junio de 1827,None,27 de enero de 1827,9 de junio de 1827
24,Agustín Gamarra Messia,19 de diciembre de 1829 - 19 de diciembre de 1833,1.ª (cont.),Primeras elecciones[39],Presidente de la República,NaN,19 de diciembre de 1829 - 19 de diciembre de 1833,None,19 de diciembre de 1829,19 de diciembre de 1833
50,Agustín Gamarra Messia,15 de agosto de 1839 -,2.ª (cont.),Designado por el Congreso General de Huancayo[75],Presidente Provisorio,NaN,15 de agosto de 1839 -,None,15 de agosto de 1839,11 de julio de 1840
51,Agustín Gamarra Messia,10 de julio de 1840 - 18 de noviembre de 1841 (†),2.ª (cont.),Elecciones[76],Presidente de la República,NaN,10 de julio de 1840 - 18 de noviembre de 1841,†),10 de julio de 1840,18 de noviembre de 1841
58,Manuel Menéndez Gorozabel,18 de noviembre de 1841 - 16 de agosto de 1842,3.ª (cont.),Sucesión constitucional (presidente del Consej...,Encargado del Poder Ejecutivo (Presidente tran...,NaN,18 de noviembre de 1841 - 16 de agosto de 1842,None,18 de noviembre de 1841,16 de agosto de 1842
62,Juan Francisco de Vidal La Hoz,17 de octubre de 1842 -,2.ª (cont.),Victoria contra Torrico en la batalla de Agua ...,Encargado del Poder Ejecutivo (Presidente tran...,NaN,17 de octubre de 1842 -,None,17 de octubre de 1842,28 de octubre de 1842
63,Juan Francisco de Vidal La Hoz,28 de octubre de 1842 - 15 de marzo de 1843,2.ª (cont.),Ratificado por el Congreso ante la negativa de...,Encargado del Poder Ejecutivo (Presidente tran...,NaN,28 de octubre de 1842 - 15 de marzo de 1843,None,28 de octubre de 1842,15 de marzo de 1843
72,Domingo Elías Carbajo,17 de junio - 10 de agosto de 1844,1.ª (cont.),Autoproclamación en Lima para restaurar el ord...,Jefe Supremo,NaN,17 de junio - 10 de agosto de 1844,None,17 de junio de 1844,10 de agosto de 1844
78,Ramón Castilla y Marquesado,5 de enero de 1855 -,3.ª (cont.),Triunfo de la revolución liberal en la batalla...,Presidente Provisorio,NaN,5 de enero de 1855 -,None,5 de enero de 1855,24 de octubre de 1858
79,Ramón Castilla y Marquesado,24 de octubre de 1858 - 24 de octubre de 1862,3.ª (cont.),Elecciones[102],Presidente de la República,NaN,24 de octubre de 1858 - 24 de octubre de 1862,None,24 de octubre de 1858,24 de octubre de 1862
91,Mariano Ignacio Prado Ochoa,15 de febrero de 1867 -,1.ª (cont.),Designado por el Congreso[113],Presidente Provisorio,NaN,15 de febrero de 1867 -,None,15 de febrero de 1867,31 de agosto de 1867
92,Mariano Ignacio Prado Ochoa,31 de agosto de 1867- 7 de enero de 1868[114],1.ª (cont.),Elecciones[115] (fraude electoral)[n 12],Presidente de la República,NaN,31 de agosto de 1867- 7 de enero de 1868,114],31 de agosto de 1867,7 de enero de 1868
107,José Nicolás Baltazar Fernández de Piérola y V...,29 de julio - 28 de noviembre de 1881,1.ª (cont.),Designado por la Asamblea Nacional de Ayacucho...,Presidente de la República,-,29 de julio - 28 de noviembre de 1881,None,29 de julio de 1881,28 de noviembre de 1881
110,Francisco García-Calderón Landa,10 de julio-6 de nov. de 1881,Única (cont.),Ratificado por el Congreso de Chorrillos y rec...,Presidente Provisorio,-,10 de julio-6 de nov. de 1881,None,10 de julio de 1881,6 de noviembre de 1881
113,Miguel Iglesias Pino de Arce,30 de diciembre de 1882 -,Única (cont.),Elegido por la Asamblea de Montán (Cajamarca)[...,Presidente Regenerador,(Militar),30 de diciembre de 1882 -,None,30 de diciembre de 1882,1 de marzo de 1884
114,Miguel Iglesias Pino de Arce,1 de marzo de 1884 - 3 de diciembre de 1885,Única (cont.),Ratificado por la Asamblea Constituyente[146][...,Presidente Provisorio,(Militar),1 de marzo de 1884 - 3 de diciembre de 1885,None,1 de marzo de 1884,3 de diciembre de 1885
126,Serapio Calderón Lazo de la Vega,7 de mayo - 24 de septiembre de 1904,Única (cont.),Sucesión constitucinoal (2.º Vicepresidente) t...,Encargado del Poder Ejecutivo (Presidente tran...,Partido Civil,7 de mayo - 24 de septiembre de 1904,None,7 de mayo de 1904,24 de septiembre de 1904
131,Óscar Raimundo Benavides Larrea,15 de mayo de 1914 - 18 de agosto de 1915,1.ª (cont.),NaN,Presidente Provisorio,(Militar),15 de mayo de 1914 - 18 de agosto de 1915,None,15 de mayo de 1914,18 de agosto de 1915
134,Augusto Bernardino Leguía y Salcedo,12 de octubre de 1919 -,2.ª (cont.),Ratificación de elección previa al Golpe.[165],Presidente Constitucional,PDR,12 de octubre de 1919 -,None,12 de octubre de 1919,12 de octubre de 1924
135,Augusto Bernardino Leguía y Salcedo,12 de octubre de 1924 -,3.ª (cont.),Elecciones (único candidato),Presidente Constitucional,PDR,12 de octubre de 1924 -,None,12 de octubre de 1924,12 de octubre de 1929
136,Augusto Bernardino Leguía y Salcedo,12 de octubre de 1929 - 25 de agosto de 1930,4.ª (cont.),Elecciones (único candidato),Presidente Constitucional,PDR,12 de octubre de 1929 - 25 de agosto de 1930,None,12 de octubre de 1929,25 de agosto de 1930
162,Alberto Kenya Fujimori Inomoto[n 14],5 de abril de 1992 -,1.ª (cont.),Autogolpe de Estado[198][199],Presidente del Gobierno de Emergencia y Recons...,C90,5 de abril de 1992 -,None,5 de abril de 1992,9 de enero de 1993
163,Alberto Kenya Fujimori Inomoto[n 14],9 de enero de 1993 -,1.ª (cont.),Ratificado por el Congreso Constituyente[200][...,Presidente Constitucional,C90,9 de enero de 1993 -,None,9 de enero de 1993,28 de julio de 1995
164,Alberto Kenya Fujimori Inomoto[n 14],28 de julio de 1995 -,2.ª (cont.),Elecciones[202],Presidente Constitucional,C90-NM,28 de julio de 1995 -,None,28 de julio de 1995,28 de julio de 2000
165,Alberto Kenya Fujimori Inomoto[n 14],28 de julio - 21 de noviembre de 2000,3.ª (cont.),Elecciones[203] (fraude electoral),Presidente Constitucional,Perú 2000,28 de julio - 21 de noviembre de 2000,None,28 de julio de 2000,21 de noviembre de 2000

In [50]:
presisAll[presisAll.Nombre.str.contains('Bernardo')]

,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
1,José Bernardo de Tagle y Portocarrero,19 de enero - 21 de agosto de 1822,1.ª,"Encargado interino, por viaje de San Martín a ...",Supremo Delegado,NaN,19 de enero - 21 de agosto de 1822,None,19 de enero de 1822,21 de agosto de 1822
3,José Bernardo de Tagle y Portocarrero,27-28 de febrero de 1823,2.ª,Elegido provisionalmente por el Congreso tras ...,Encargado del Poder Ejecutivo,NaN,27-28 de febrero de 1823,None,27 de febrero de 1823,28 de febrero de 1823
8,José Bernardo de Tagle y Portocarrero,17 de julio de 1823 -,3.ª,"Delegado por Sucre,[19] ratificado por el Cong...",Jefe Supremo político y militar,NaN,17 de julio de 1823 -,None,17 de julio de 1823,16 de agosto de 1823
9,José Bernardo de Tagle y Portocarrero,16 de agosto de 1823 -,3.ª,Nombrado presidente por el Congreso.[21],Presidente de la República,NaN,16 de agosto de 1823 -,None,16 de agosto de 1823,18 de noviembre de 1823
10,José Bernardo de Tagle y Portocarrero,18 de noviembre de 1823 - 10 de febrero de 1824,3.ª (cont.),Ratificado según el flamante texto constitucio...,Presidente Constitucional de la República,NaN,18 de noviembre de 1823 - 10 de febrero de 1824,None,18 de noviembre de 1823,10 de febrero de 1824

In [51]:
presisAll.loc[8,"FinGob"]='10 de febrero de 1824'
presisAll.loc[8,"Vez"]=3
presisAll.drop(index=[9,10],inplace=True)
presisAll.reset_index(drop=True,inplace=True)

In [52]:
presisAll[presisAll.Nombre.str.contains('Santa Cruz y Calaumana')]

,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
15,Andrés de Santa Cruz y Calaumana,29 de junio de 1826 - 27 de enero de 1827,1.ª,"Encargado del mando.[28] Nombrado ""autoridad s...",Presidente del Consejo de Gobierno,NaN,29 de junio de 1826 - 27 de enero de 1827,None,29 de junio de 1826,27 de enero de 1827
16,Andrés de Santa Cruz y Calaumana,27 de enero - 9 de junio de 1827,1.ª (cont.),Gobernante de facto tras la revuelta que puso ...,Presidente del Consejo de Gobierno[n 8],NaN,27 de enero - 9 de junio de 1827,None,27 de enero de 1827,9 de junio de 1827
39,Andrés de Santa Cruz y Calaumana,17 de marzo de 1836 -,2.ª,Designación por la Asamblea de Sicuani[60],Supremo Protector del Sud-Perú,NaN,17 de marzo de 1836 -,None,17 de marzo de 1836,20 de febrero de 1839
40,Andrés de Santa Cruz y Calaumana,6 de agosto de 1836 -,2.ª,Designación por la Asamblea de Huaura[61],Supremo Protector del Nor-Perú,NaN,6 de agosto de 1836 -,None,6 de agosto de 1836,20 de febrero de 1839
41,Andrés de Santa Cruz y Calaumana,28 de octubre de 1836 - 20 de febrero de 1839[62],2.ª,Designación por el Congreso de Tacna[63] y rat...,Protector de la Confederación Perú-Boliviana,NaN,28 de octubre de 1836 - 20 de febrero de 1839,62],28 de octubre de 1836,20 de febrero de 1839

In [53]:
presisAll.loc[15,"FinGob"]='9 de junio de 1827'
presisAll.loc[15,"Vez"]=1


presisAll.drop(index=[16,40,41],inplace=True)
presisAll.reset_index(drop=True,inplace=True)

In [54]:
presisAll[presisAll.Nombre.str.contains('Gamarra Messia')]

,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
20,Agustín Gamarra Messia,31 de agosto de 1829 - 19 de diciembre de 1829,1.ª,Elegido por el Congreso tras la deposición de ...,Presidente provisorio,NaN,31 de agosto de 1829 - 19 de diciembre de 1829,None,31 de agosto de 1829,19 de diciembre de 1829
21,Agustín Gamarra Messia,19 de diciembre de 1829 - 19 de diciembre de 1833,1.ª (cont.),Primeras elecciones[39],Presidente de la República,NaN,19 de diciembre de 1829 - 19 de diciembre de 1833,None,19 de diciembre de 1829,19 de diciembre de 1833
44,Agustín Gamarra Messia,24 de agosto de 1838 -,2.ª,Proclamación por cabildo abierto en Lima duran...,Presidente Provisorio,NaN,24 de agosto de 1838 -,None,24 de agosto de 1838,15 de agosto de 1839
45,Agustín Gamarra Messia,15 de agosto de 1839 -,2.ª (cont.),Designado por el Congreso General de Huancayo[75],Presidente Provisorio,NaN,15 de agosto de 1839 -,None,15 de agosto de 1839,11 de julio de 1840
46,Agustín Gamarra Messia,10 de julio de 1840 - 18 de noviembre de 1841 (†),2.ª (cont.),Elecciones[76],Presidente de la República,NaN,10 de julio de 1840 - 18 de noviembre de 1841,†),10 de julio de 1840,18 de noviembre de 1841

In [55]:
presisAll.loc[20,"FinGob"]='19 de diciembre de 1833'
presisAll.loc[20,"Vez"]=1

presisAll.loc[44,"FinGob"]='18 de noviembre de 1841'
presisAll.loc[44,"Vez"]=2

presisAll.drop(index=[21,45,46],inplace=True)
presisAll.reset_index(drop=True,inplace=True)

In [56]:
presisAll[presisAll.Nombre.str.contains('Gorozabel')]

,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
47,Manuel Menéndez Gorozabel,28 de agosto-23 de sept. 1840,1.ª,Encargado interino por enfermedad de Gamarra.[...,Encargado del Poder Ejecutivo,NaN,28 de agosto-23 de sept. 1840,None,28 de agosto de 1840,23 de septiembre de 1840
48,Manuel Menéndez Gorozabel,17 de marzo-28 de junio de 1841,2.ª,Encargado por salida de Gamarra durante guerra...,Encargado del Poder Ejecutivo,NaN,17 de marzo-28 de junio de 1841,None,17 de marzo de 1841,28 de junio de 1841
49,Manuel Menéndez Gorozabel,13 de julio-18 de nov. 1841,3.ª,Encargado por salida de Gamarra rumbo a Bolivi...,Encargado del Poder Ejecutivo,NaN,13 de julio-18 de nov. 1841,None,13 de julio de 1841,18 de noviembre de 1841
50,Manuel Menéndez Gorozabel,18 de noviembre de 1841 - 16 de agosto de 1842,3.ª (cont.),Sucesión constitucional (presidente del Consej...,Encargado del Poder Ejecutivo (Presidente tran...,NaN,18 de noviembre de 1841 - 16 de agosto de 1842,None,18 de noviembre de 1841,16 de agosto de 1842
66,Manuel Menéndez Gorozabel,7 de octubre de 1844 - 20 de abril de 1845,4.ª,Restauración constitucional transitoria tras r...,Encargado del Poder Ejecutivo (Presidente tran...,NaN,7 de octubre de 1844 - 20 de abril de 1845,None,7 de octubre de 1844,20 de abril de 1845

In [57]:
presisAll.loc[49,"FinGob"]='16 de agosto de 1842'
presisAll.loc[49,"Vez"]=3

presisAll.drop(index=[50],inplace=True)
presisAll.reset_index(drop=True,inplace=True)

In [58]:
presisAll[presisAll.Vez.str.contains('cont.',na=False)]

,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
53,Juan Francisco de Vidal La Hoz,17 de octubre de 1842 -,2.ª (cont.),Victoria contra Torrico en la batalla de Agua ...,Encargado del Poder Ejecutivo (Presidente tran...,NaN,17 de octubre de 1842 -,None,17 de octubre de 1842,28 de octubre de 1842
54,Juan Francisco de Vidal La Hoz,28 de octubre de 1842 - 15 de marzo de 1843,2.ª (cont.),Ratificado por el Congreso ante la negativa de...,Encargado del Poder Ejecutivo (Presidente tran...,NaN,28 de octubre de 1842 - 15 de marzo de 1843,None,28 de octubre de 1842,15 de marzo de 1843
63,Domingo Elías Carbajo,17 de junio - 10 de agosto de 1844,1.ª (cont.),Autoproclamación en Lima para restaurar el ord...,Jefe Supremo,NaN,17 de junio - 10 de agosto de 1844,None,17 de junio de 1844,10 de agosto de 1844
69,Ramón Castilla y Marquesado,5 de enero de 1855 -,3.ª (cont.),Triunfo de la revolución liberal en la batalla...,Presidente Provisorio,NaN,5 de enero de 1855 -,None,5 de enero de 1855,24 de octubre de 1858
70,Ramón Castilla y Marquesado,24 de octubre de 1858 - 24 de octubre de 1862,3.ª (cont.),Elecciones[102],Presidente de la República,NaN,24 de octubre de 1858 - 24 de octubre de 1862,None,24 de octubre de 1858,24 de octubre de 1862
82,Mariano Ignacio Prado Ochoa,15 de febrero de 1867 -,1.ª (cont.),Designado por el Congreso[113],Presidente Provisorio,NaN,15 de febrero de 1867 -,None,15 de febrero de 1867,31 de agosto de 1867
83,Mariano Ignacio Prado Ochoa,31 de agosto de 1867- 7 de enero de 1868[114],1.ª (cont.),Elecciones[115] (fraude electoral)[n 12],Presidente de la República,NaN,31 de agosto de 1867- 7 de enero de 1868,114],31 de agosto de 1867,7 de enero de 1868
98,José Nicolás Baltazar Fernández de Piérola y V...,29 de julio - 28 de noviembre de 1881,1.ª (cont.),Designado por la Asamblea Nacional de Ayacucho...,Presidente de la República,-,29 de julio - 28 de noviembre de 1881,None,29 de julio de 1881,28 de noviembre de 1881
101,Francisco García-Calderón Landa,10 de julio-6 de nov. de 1881,Única (cont.),Ratificado por el Congreso de Chorrillos y rec...,Presidente Provisorio,-,10 de julio-6 de nov. de 1881,None,10 de julio de 1881,6 de noviembre de 1881
104,Miguel Iglesias Pino de Arce,30 de diciembre de 1882 -,Única (cont.),Elegido por la Asamblea de Montán (Cajamarca)[...,Presidente Regenerador,(Militar),30 de diciembre de 1882 -,None,30 de diciembre de 1882,1 de marzo de 1884
105,Miguel Iglesias Pino de Arce,1 de marzo de 1884 - 3 de diciembre de 1885,Única (cont.),Ratificado por la Asamblea Constituyente[146][...,Presidente Provisorio,(Militar),1 de marzo de 1884 - 3 de diciembre de 1885,None,1 de marzo de 1884,3 de diciembre de 1885
117,Serapio Calderón Lazo de la Vega,7 de mayo - 24 de septiembre de 1904,Única (cont.),Sucesión constitucinoal (2.º Vicepresidente) t...,Encargado del Poder Ejecutivo (Presidente tran...,Partido Civil,7 de mayo - 24 de septiembre de 1904,None,7 de mayo de 1904,24 de septiembre de 1904
122,Óscar Raimundo Benavides Larrea,15 de mayo de 1914 - 18 de agosto de 1915,1.ª (cont.),NaN,Presidente Provisorio,(Militar),15 de mayo de 1914 - 18 de agosto de 1915,None,15 de mayo de 1914,18 de agosto de 1915
125,Augusto Bernardino Leguía y Salcedo,12 de octubre de 1919 -,2.ª (cont.),Ratificación de elección previa al Golpe.[165],Presidente Constitucional,PDR,12 de octubre de 1919 -,None,12 de octubre de 1919,12 de octubre de 1924
126,Augusto Bernardino Leguía y Salcedo,12 de octubre de 1924 -,3.ª (cont.),Elecciones (único candidato),Presidente Constitucional,PDR,12 de octubre de 1924 -,None,12 de octubre de 1924,12 de octubre de 1929
127,Augusto Bernardino Leguía y Salcedo,12 de octubre de 1929 - 25 de agosto de 1930,4.ª (cont.),Elecciones (único candidato),Presidente Constitucional,PDR,12 de octubre de 1929 - 25 de agosto de 1930,None,12 de octubre de 1929,25 de agosto de 1930
153,Alberto Kenya Fujimori Inomoto[n 14],5 de abril de 1992 -,1.ª (cont.),Autogolpe de Estado[198][199],Presidente del Gobierno de Emergencia y Recons...,C90,5 de abril de 1992 -,None,5 de abril de 1992,9 de enero de 1993
154,Alberto Kenya Fujimori Inomoto[n 14],9 de enero de 1993 -,1.ª (cont.),Ratificado por el Congreso Constituyente[200][...,Presidente Constitucional,C90,9 de enero de 1993 -,None,9 de enero de 1993,28 de julio de 1995
155,Alberto Kenya Fujimori Inomoto[n 14],28 de julio de 1995 -,2.ª (cont.),Elecciones[202],Presidente Constitucional,C90-NM,28 de julio de 1995 -,None,28 de julio de 1995,28 de julio de 2000
156,Alberto Kenya Fujimori Inomoto[n 14],28 de julio - 21 de noviembre de 2000,3.ª (cont.),Elecciones[203] (fraude electoral),Presidente Constitucional,Perú 2000,28 de julio - 21 de noviembre de 2000,None,28 de julio de 2000,21 de noviembre de 2000

In [59]:
presisAll[presisAll.Nombre.str.contains('Vidal')]

,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
36,Juan Francisco de Vidal La Hoz,30 de diciembre de 1835 - 8 de enero de 1836,1.ª,"Presidente del Consejo de Gobierno, ocupó Lima...",Encargado del Ejecutivo,NaN,30 de diciembre de 1835 - 8 de enero de 1836,None,30 de diciembre de 1835,8 de enero de 1836
52,Juan Francisco de Vidal La Hoz,28 de julio de 1842 -,2.ª,"Segundo vicepresidente del Consejo de Estado, ...",Encargado del Poder Ejecutivo,NaN,28 de julio de 1842 -,None,28 de julio de 1842,16 de agosto de 1842
53,Juan Francisco de Vidal La Hoz,17 de octubre de 1842 -,2.ª (cont.),Victoria contra Torrico en la batalla de Agua ...,Encargado del Poder Ejecutivo (Presidente tran...,NaN,17 de octubre de 1842 -,None,17 de octubre de 1842,28 de octubre de 1842
54,Juan Francisco de Vidal La Hoz,28 de octubre de 1842 - 15 de marzo de 1843,2.ª (cont.),Ratificado por el Congreso ante la negativa de...,Encargado del Poder Ejecutivo (Presidente tran...,NaN,28 de octubre de 1842 - 15 de marzo de 1843,None,28 de octubre de 1842,15 de marzo de 1843

In [60]:
presisAll.loc[53,"FinGob"]='15 de marzo de 1843'
presisAll.loc[53,"Vez"]=3

presisAll.drop(index=[54],inplace=True)
presisAll.reset_index(drop=True,inplace=True)

In [61]:
presisAll[presisAll.Nombre.str.contains('Carbajo')]

,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
59,Domingo Elías Carbajo,30 de noviembre de 1843 - 17 de junio de 1844,1.ª,Prefecto de Lima encargado del departamento en...,Encargado de la Administración Directorial,NaN,30 de noviembre de 1843 - 17 de junio de 1844,None,30 de noviembre de 1843,17 de junio de 1844
62,Domingo Elías Carbajo,17 de junio - 10 de agosto de 1844,1.ª (cont.),Autoproclamación en Lima para restaurar el ord...,Jefe Supremo,NaN,17 de junio - 10 de agosto de 1844,None,17 de junio de 1844,10 de agosto de 1844

In [62]:
presisAll.loc[59,"FinGob"]='10 de agosto de 1844'
presisAll.loc[59,"Vez"]=1

presisAll.drop(index=[62],inplace=True)
presisAll.reset_index(drop=True,inplace=True)

In [63]:
presisAll[presisAll.Nombre.str.contains('Ramón Castilla')]

,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
61,Ramón Castilla y Marquesado,17 de febrero - 11 de diciembre de 1844[94],1.ª,Sucesor designado de Nieto tras su fallecimien...,Presidente de la Suprema Junta de Gobierno Pro...,NaN,17 de febrero - 11 de diciembre de 1844,94],17 de febrero de 1844,11 de diciembre de 1844
64,Ramón Castilla y Marquesado,20 de abril de 1845 - 20 de abril de 1851,2.ª,Elecciones[98],Presidente Constitucional,NaN,20 de abril de 1845 - 20 de abril de 1851,None,20 de abril de 1845,20 de abril de 1851
66,Ramón Castilla y Marquesado,1 de mayo de 1854 -,3.ª,Autoproclamación en el Sur en reacción a escán...,Presidente Provisorio,NaN,1 de mayo de 1854 -,None,1 de mayo de 1854,5 de enero de 1855
67,Ramón Castilla y Marquesado,5 de enero de 1855 -,3.ª (cont.),Triunfo de la revolución liberal en la batalla...,Presidente Provisorio,NaN,5 de enero de 1855 -,None,5 de enero de 1855,24 de octubre de 1858
68,Ramón Castilla y Marquesado,24 de octubre de 1858 - 24 de octubre de 1862,3.ª (cont.),Elecciones[102],Presidente de la República,NaN,24 de octubre de 1858 - 24 de octubre de 1862,None,24 de octubre de 1858,24 de octubre de 1862
75,Ramón Castilla y Marquesado,3-9 de abril de 1863,4.ª,De facto encargado del mando por ser la máxima...,Encargado del Poder Ejecutivo,NaN,3-9 de abril de 1863,None,3 de abril de 1863,9 de abril de 1863

In [64]:
presisAll.loc[66,"FinGob"]='24 de octubre de 1862'
presisAll.loc[66,"Vez"]=3

presisAll.drop(index=[67,68],inplace=True)
presisAll.reset_index(drop=True,inplace=True)

In [65]:
presisAll[presisAll.Nombre.str.contains('Mariano Ignacio Prado')]

,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
77,Mariano Ignacio Prado Ochoa,28 de noviembre de 1865 -,1.ª,Autoproclamación tras revolución nacionalista[...,Jefe Supremo Provisorio,NaN,28 de noviembre de 1865 -,None,28 de noviembre de 1865,15 de febrero de 1867
78,Mariano Ignacio Prado Ochoa,15 de febrero de 1867 -,1.ª (cont.),Designado por el Congreso[113],Presidente Provisorio,NaN,15 de febrero de 1867 -,None,15 de febrero de 1867,31 de agosto de 1867
79,Mariano Ignacio Prado Ochoa,31 de agosto de 1867- 7 de enero de 1868[114],1.ª (cont.),Elecciones[115] (fraude electoral)[n 12],Presidente de la República,NaN,31 de agosto de 1867- 7 de enero de 1868,114],31 de agosto de 1867,7 de enero de 1868
90,Mariano Ignacio Prado Ochoa,2 de agosto de 1876 - 23 de diciembre de 1879,2.ª,Elecciones[131],Presidente Constitucional,Partido Civil,2 de agosto de 1876 - 23 de diciembre de 1879,None,2 de agosto de 1876,23 de diciembre de 1879

In [66]:
presisAll.loc[77,"FinGob"]='7 de enero de 1868'
presisAll.loc[77,"Vez"]=1

presisAll.drop(index=[78,79],inplace=True)
presisAll.reset_index(drop=True,inplace=True)

In [67]:
presisAll[presisAll.Nombre.str.contains('Baltazar Fernández')]

,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
91,José Nicolás Baltazar Fernández de Piérola y V...,23 de diciembre de 1879 - 28 de julio de 1881,1.ª,Autoproclamación[136] y Cabildo Abierto de Lim...,Jefe Supremo,-,23 de diciembre de 1879 - 28 de julio de 1881,None,23 de diciembre de 1879,28 de julio de 1881
92,José Nicolás Baltazar Fernández de Piérola y V...,29 de julio - 28 de noviembre de 1881,1.ª (cont.),Designado por la Asamblea Nacional de Ayacucho...,Presidente de la República,-,29 de julio - 28 de noviembre de 1881,None,29 de julio de 1881,28 de noviembre de 1881
107,José Nicolás Baltazar Fernández de Piérola y V...,8 de septiembre de 1895 - 8 de septiembre de 1899,2.ª,"Elecciones[155] (único candidato, de facto gol...",Presidente Constitucional,Partido Demócrata,8 de septiembre de 1895 - 8 de septiembre de 1899,None,8 de septiembre de 1895,8 de septiembre de 1899

In [68]:
presisAll.loc[91,"FinGob"]='28 de noviembre de 1881'
presisAll.loc[91,"Vez"]=1

presisAll.drop(index=[92],inplace=True)
presisAll.reset_index(drop=True,inplace=True)

In [69]:
presisAll[presisAll.Nombre.str.contains('Francisco García')]

,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
93,Francisco García-Calderón Landa,12 de marzo-10 de julio de 1881,Única,Elegido en Cabildo Abierto (Magdalena)[139],Presidente Provisorio,-,12 de marzo-10 de julio de 1881,None,12 de marzo de 1881,10 de julio de 1881
94,Francisco García-Calderón Landa,10 de julio-6 de nov. de 1881,Única (cont.),Ratificado por el Congreso de Chorrillos y rec...,Presidente Provisorio,-,10 de julio-6 de nov. de 1881,None,10 de julio de 1881,6 de noviembre de 1881

In [70]:
presisAll.loc[93,"FinGob"]='6 de noviembre de 1881'
presisAll.loc[93,"Vez"]=1

presisAll.drop(index=[94],inplace=True)
presisAll.reset_index(drop=True,inplace=True)

In [71]:
presisAll[presisAll.Vez.str.contains('cont.',na=False)]

,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
96,Miguel Iglesias Pino de Arce,30 de diciembre de 1882 -,Única (cont.),Elegido por la Asamblea de Montán (Cajamarca)[...,Presidente Regenerador,(Militar),30 de diciembre de 1882 -,None,30 de diciembre de 1882,1 de marzo de 1884
97,Miguel Iglesias Pino de Arce,1 de marzo de 1884 - 3 de diciembre de 1885,Única (cont.),Ratificado por la Asamblea Constituyente[146][...,Presidente Provisorio,(Militar),1 de marzo de 1884 - 3 de diciembre de 1885,None,1 de marzo de 1884,3 de diciembre de 1885
109,Serapio Calderón Lazo de la Vega,7 de mayo - 24 de septiembre de 1904,Única (cont.),Sucesión constitucinoal (2.º Vicepresidente) t...,Encargado del Poder Ejecutivo (Presidente tran...,Partido Civil,7 de mayo - 24 de septiembre de 1904,None,7 de mayo de 1904,24 de septiembre de 1904
114,Óscar Raimundo Benavides Larrea,15 de mayo de 1914 - 18 de agosto de 1915,1.ª (cont.),NaN,Presidente Provisorio,(Militar),15 de mayo de 1914 - 18 de agosto de 1915,None,15 de mayo de 1914,18 de agosto de 1915
117,Augusto Bernardino Leguía y Salcedo,12 de octubre de 1919 -,2.ª (cont.),Ratificación de elección previa al Golpe.[165],Presidente Constitucional,PDR,12 de octubre de 1919 -,None,12 de octubre de 1919,12 de octubre de 1924
118,Augusto Bernardino Leguía y Salcedo,12 de octubre de 1924 -,3.ª (cont.),Elecciones (único candidato),Presidente Constitucional,PDR,12 de octubre de 1924 -,None,12 de octubre de 1924,12 de octubre de 1929
119,Augusto Bernardino Leguía y Salcedo,12 de octubre de 1929 - 25 de agosto de 1930,4.ª (cont.),Elecciones (único candidato),Presidente Constitucional,PDR,12 de octubre de 1929 - 25 de agosto de 1930,None,12 de octubre de 1929,25 de agosto de 1930
145,Alberto Kenya Fujimori Inomoto[n 14],5 de abril de 1992 -,1.ª (cont.),Autogolpe de Estado[198][199],Presidente del Gobierno de Emergencia y Recons...,C90,5 de abril de 1992 -,None,5 de abril de 1992,9 de enero de 1993
146,Alberto Kenya Fujimori Inomoto[n 14],9 de enero de 1993 -,1.ª (cont.),Ratificado por el Congreso Constituyente[200][...,Presidente Constitucional,C90,9 de enero de 1993 -,None,9 de enero de 1993,28 de julio de 1995
147,Alberto Kenya Fujimori Inomoto[n 14],28 de julio de 1995 -,2.ª (cont.),Elecciones[202],Presidente Constitucional,C90-NM,28 de julio de 1995 -,None,28 de julio de 1995,28 de julio de 2000
148,Alberto Kenya Fujimori Inomoto[n 14],28 de julio - 21 de noviembre de 2000,3.ª (cont.),Elecciones[203] (fraude electoral),Presidente Constitucional,Perú 2000,28 de julio - 21 de noviembre de 2000,None,28 de julio de 2000,21 de noviembre de 2000

In [72]:
presisAll[presisAll.Nombre.str.contains('Miguel Iglesias')]

,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
95,Miguel Iglesias Pino de Arce,31 de agosto de 1882 -,Única,Autoproclamación en Cajamarca (Grito de Montán...,Jefe Supremo,(Militar),31 de agosto de 1882 -,None,31 de agosto de 1882,30 de diciembre de 1882
96,Miguel Iglesias Pino de Arce,30 de diciembre de 1882 -,Única (cont.),Elegido por la Asamblea de Montán (Cajamarca)[...,Presidente Regenerador,(Militar),30 de diciembre de 1882 -,None,30 de diciembre de 1882,1 de marzo de 1884
97,Miguel Iglesias Pino de Arce,1 de marzo de 1884 - 3 de diciembre de 1885,Única (cont.),Ratificado por la Asamblea Constituyente[146][...,Presidente Provisorio,(Militar),1 de marzo de 1884 - 3 de diciembre de 1885,None,1 de marzo de 1884,3 de diciembre de 1885

In [73]:
presisAll.loc[95,"FinGob"]='3 de diciembre de 1885'
presisAll.loc[95,"Vez"]=1

presisAll.drop(index=[96,97],inplace=True)
presisAll.reset_index(drop=True,inplace=True)

In [74]:
presisAll[presisAll.Nombre.str.contains('Serapio')]

,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
106,Serapio Calderón Lazo de la Vega,18 de abril-7 de mayo de 1904,Única,2.º Vicepresidente encargado del mando por enf...,Encargado del Poder Ejecutivo,Partido Civil,18 de abril-7 de mayo de 1904,None,18 de abril de 1904,7 de mayo de 1904
107,Serapio Calderón Lazo de la Vega,7 de mayo - 24 de septiembre de 1904,Única (cont.),Sucesión constitucinoal (2.º Vicepresidente) t...,Encargado del Poder Ejecutivo (Presidente tran...,Partido Civil,7 de mayo - 24 de septiembre de 1904,None,7 de mayo de 1904,24 de septiembre de 1904

In [75]:
presisAll.loc[106,"FinGob"]='24 de septiembre de 1904'
presisAll.loc[106,"Vez"]=1

presisAll.drop(index=[107],inplace=True)
presisAll.reset_index(drop=True,inplace=True)

In [76]:
presisAll[presisAll.Nombre.str.contains('Benavides')]

,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
110,Óscar Raimundo Benavides Larrea,4 de febrero de 1914 -,1.ª,NaN,Presidente de la Junta de Gobierno,(Militar),4 de febrero de 1914 -,None,4 de febrero de 1914,15 de mayo de 1914
111,Óscar Raimundo Benavides Larrea,15 de mayo de 1914 - 18 de agosto de 1915,1.ª (cont.),NaN,Presidente Provisorio,(Militar),15 de mayo de 1914 - 18 de agosto de 1915,None,15 de mayo de 1914,18 de agosto de 1915
125,Óscar Raimundo Benavides Larrea,30 de abril de 1933 - 8 de diciembre de 1939,2.ª,Elección por el Congreso tras el asesinato de ...,Presidente Constitucional,(Militar),30 de abril de 1933 - 8 de diciembre de 1939,None,30 de abril de 1933,8 de diciembre de 1939

In [77]:
presisAll.loc[110,"FinGob"]='18 de agosto de 1915'
presisAll.loc[110,"Vez"]=1

presisAll.drop(index=[111],inplace=True)
presisAll.reset_index(drop=True,inplace=True)

In [78]:
presisAll[presisAll.Nombre.str.contains('Leguía')]

,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
108,Augusto Bernardino Leguía y Salcedo,24 de septiembre de 1908 - 24 de septiembre de...,1.ª,Elecciones[161] (único candidato),Presidente Constitucional,Partido Civil,24 de septiembre de 1908 - 24 de septiembre de...,None,24 de septiembre de 1908,24 de septiembre de 1912
112,Augusto Bernardino Leguía y Salcedo,4 de julio de 1919 -,2.ª,"Golpe de Estado tras Elecciones, siendo entonc...",Presidente Provisorio,-,4 de julio de 1919 -,None,4 de julio de 1919,12 de octubre de 1919
113,Augusto Bernardino Leguía y Salcedo,12 de octubre de 1919 -,2.ª (cont.),Ratificación de elección previa al Golpe.[165],Presidente Constitucional,PDR,12 de octubre de 1919 -,None,12 de octubre de 1919,12 de octubre de 1924
114,Augusto Bernardino Leguía y Salcedo,12 de octubre de 1924 -,3.ª (cont.),Elecciones (único candidato),Presidente Constitucional,PDR,12 de octubre de 1924 -,None,12 de octubre de 1924,12 de octubre de 1929
115,Augusto Bernardino Leguía y Salcedo,12 de octubre de 1929 - 25 de agosto de 1930,4.ª (cont.),Elecciones (único candidato),Presidente Constitucional,PDR,12 de octubre de 1929 - 25 de agosto de 1930,None,12 de octubre de 1929,25 de agosto de 1930

In [79]:
presisAll.loc[112,"FinGob"]='25 de agosto de 1930'
presisAll.loc[112,"Vez"]=2

presisAll.drop(index=[113,114,115],inplace=True)
presisAll.reset_index(drop=True,inplace=True)

In [80]:
presisAll[presisAll.Nombre.str.contains('Fujimori')]

,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
137,Alberto Kenya Fujimori Inomoto[n 14],28 de julio de 1990 -,1.ª,Elecciones[197],Presidente Constitucional,C90,28 de julio de 1990 -,None,28 de julio de 1990,5 de abril de 1992
138,Alberto Kenya Fujimori Inomoto[n 14],5 de abril de 1992 -,1.ª (cont.),Autogolpe de Estado[198][199],Presidente del Gobierno de Emergencia y Recons...,C90,5 de abril de 1992 -,None,5 de abril de 1992,9 de enero de 1993
139,Alberto Kenya Fujimori Inomoto[n 14],9 de enero de 1993 -,1.ª (cont.),Ratificado por el Congreso Constituyente[200][...,Presidente Constitucional,C90,9 de enero de 1993 -,None,9 de enero de 1993,28 de julio de 1995
140,Alberto Kenya Fujimori Inomoto[n 14],28 de julio de 1995 -,2.ª (cont.),Elecciones[202],Presidente Constitucional,C90-NM,28 de julio de 1995 -,None,28 de julio de 1995,28 de julio de 2000
141,Alberto Kenya Fujimori Inomoto[n 14],28 de julio - 21 de noviembre de 2000,3.ª (cont.),Elecciones[203] (fraude electoral),Presidente Constitucional,Perú 2000,28 de julio - 21 de noviembre de 2000,None,28 de julio de 2000,21 de noviembre de 2000

In [81]:
presisAll.loc[137,"FinGob"]='21 de noviembre de 2000'
presisAll.loc[137,"Vez"]=1

presisAll.drop(index=[138,139,140,141],inplace=True)
presisAll.reset_index(drop=True,inplace=True)

In [82]:
# big check

In [83]:
presisAll[presisAll.Vez.str.contains('cont.',na=False)]

Empty DataFrame
Columns: [Nombre, Mandato, Vez, Asunción, Título, Partido, Periodo, temp, InicioGob, FinGob]
Index: []

In [84]:
presisAll.Vez.value_counts()

Vez
Única    52
2.ª      32
1.ª      30
1        10
3.ª       8
4.ª       7
3         4
2         2
2.º       2
5.ª       1
1.º       1
0         1
Name: count, dtype: int64

In [85]:
presisAll.loc[presisAll.Vez=='Única',:]

,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob
0,José de San Martín y Matorras,3 de agosto de 1821 - 20 de septiembre de 1822,Única,Cabildo abierto en Lima.[3][n 5],Protector del Perú,NaN,3 de agosto de 1821 - 20 de septiembre de 1822,None,3 de agosto de 1821,20 de septiembre de 1822
5,Francisco Valdivieso y Prada,23 de junio - 17 de julio de 1823,Única,Designado provisionalmente por el Congreso tra...,Encargado interino del despacho del Gobierno,NaN,23 de junio - 17 de julio de 1823,None,23 de junio de 1823,17 de julio de 1823
6,Antonio José de Sucre y Alcalá,23 de junio - 17 de julio de 1823,Única,Designado provisionalmente por el Congreso par...,Jefe Supremo militar,NaN,23 de junio - 17 de julio de 1823,None,23 de junio de 1823,17 de julio de 1823
9,Simón José Antonio de la Santísima Trinidad Bo...,10 de febrero de 1824 - 9 de diciembre de 1826,Única,Nombrado dictador por el Congreso en margen de...,Suprema autoridad política y militar (dictador),NaN,10 de febrero de 1824 - 9 de diciembre de 1826,None,10 de febrero de 1824,9 de diciembre de 1826
10,Simón José Antonio de la Santísima Trinidad Bo...,9 de diciembre de 1826 - 27 de enero de 1827,Única,Técnicamente presidente según la Constitución ...,Presidente Vitalicio de la República,NaN,9 de diciembre de 1826 - 27 de enero de 1827,None,9 de diciembre de 1826,27 de enero de 1827
23,Juan Bautista Eléspuru,16-18 de abril de 1831,Única,De facto gobernante interino en su calidad de ...,Prefecto de Lima,NaN,16-18 de abril de 1831,None,16 de abril de 1831,18 de abril de 1831
26,Manuel Tellería Vicuña,27 de septiembre - 31 de octubre de 1832,Única,Presidente del Senado encargado del mando dura...,Encargado del Mando,NaN,27 de septiembre - 31 de octubre de 1832,None,27 de septiembre de 1832,31 de octubre de 1832
27,José Braulio del Camporredondo Cisneros,30 de julio - 22 de noviembre de 1833,Única,Vicepresidente del Senado encargado en la ause...,Encargado del Mando,NaN,30 de julio - 22 de noviembre de 1833,None,30 de julio de 1833,22 de noviembre de 1833
29,Pedro Pablo Bermúdez Ascarza,4 de enero - 24 de abril de 1834,Única,Autoproclamado tras perder las elecciones;[49]...,Jefe Supremo Provisorio,NaN,4 de enero - 24 de abril de 1834,None,4 de enero de 1834,24 de abril de 1834
32,Felipe Santiago Salaverry del Solar,25 de febrero de 1835 - 7 de febrero de 1836 (...,Única,Autoproclamado;[54] derrocó el gobierno de Orb...,Jefe Supremo,NaN,25 de febrero de 1835 - 7 de febrero de 1836,18 de febrero de 1836 †),25 de febrero de 1835,7 de febrero de 1836
33,Juan Ángel Bujanda,6 de abril - 17 de mayo de 1835,Única,Encargado del gobierno en Lima por autorizació...,Encargado del Ejecutivo,NaN,6 de abril - 17 de mayo de 1835,None,6 de abril de 1835,17 de mayo de 1835
34,Juan José Salas,28 de septiembre - 14 de octubre de 1835,Única,"Vicepresidente del Consejo de Gobierno, encarg...",Encargado del Ejecutivo,NaN,28 de septiembre - 14 de octubre de 1835,None,28 de septiembre de 1835,14 de octubre de 1835
41,Ramón Herrera y Rodado[71][68],17 de septiembre de 1837 - 12 de octubre de 1838,Única,NaN,NaN,NaN,17 de septiembre de 1837 - 12 de octubre de 1838,None,17 de septiembre de 1837,12 de octubre de 1838
50,Juan Crisóstomo Torrico y Bargas,16 de agosto - 17 de octubre de 1842,Única,Golpe de Estado[85],Jefe Supremo,NaN,16 de agosto - 17 de octubre de 1842,None,16 de agosto de 1842,17 de octubre de 1842
56,Eleuterio Aramburú,19-21 de marzo de 1843,Única,Comandante general de la guarnición de Lima; d...,Comandante General,NaN,19-21 de marzo de 1843,None,19 de marzo de 1843,21 de marzo de 1843
60,Domingo Nieto y Márquez,3 de septiembre de 1843 - 17 de febrero de 184...,Única,"Autoproclamación en el Sur, principiando la re...",Presidente de la Suprema Junta de Gobierno Pro...,NaN,3 de septiembre de 1843 - 17 de febrero de 1844,†),3 de septiembre de 1843,17 de febrero de 1844
67,José Miguel Medina Elera,17 de julio de 1854 - 5 de enero de 1855,Única,Delegado por el Presidente Echenique en su cal...,Encargado del Poder Ejecutivo,NaN,17 de julio de 1854 - 5 de enero de 1855,None,17 de julio de 1854,5 de enero de 1855
69,José María Raygada y Gallo,1 de abril de 1857 - 28 de julio de 1858,Única,Delegado por el Presidente Castilla en su cali...,Encargado del Mando,NaN,1 de abril de 1857 - 28 de julio de 1858,None,1 de abril de 1857,28 de julio de 1858
71,Juan Manuel del Mar Bernedo,29 de septiembre de 1859 - 22 de marzo de 1860,Única,Vicepresidente encargado del Ejecutivo mientra...,Encargado del Poder Ejecutivo,NaN,29 de septiembre de 1859 - 22 de marzo de 1860,None,29 de septiembre de 1859,22 de marzo de 1860
83,José Balta y Montero,2 de agosto de 1868 - 22 de julio de 1872 (26 ...,Única,Elecciones[124],Presidente Constitucional,NaN,2 de agosto de 1868 - 22 de julio de 1872,26 de julio de 1872 †),2 de agosto de 1868,22 de julio de 1872
84,Tomás Gutiérrez,22-26 de julio de 1872 (†),Única,Golpe de Estado[125][126][127],Jefe Supremo,NaN,22-26 de julio de 1872,†),22 de julio de 1872,26 de julio de 1872
85,Mariano Herencia-Zevallos y Larrauri,26 de julio - 2 de agosto de 1872,Única,Sucesión constitucional (1.º vicepresidente de...,Encargado del Poder Ejecutivo,NaN,26 de julio - 2 de agosto de 1872,None,26 de julio de 1872,2 de agosto de 1872
86,Manuel Justo Pardo y Lavalle,2 de agosto de 1872 - 2 de agosto de 1876,Única,Elecciones[129],Presidente Constitucional,Partido Civil,2 de agosto de 1872 - 2 de agosto de 1876,None,2 de agosto de 1872,2 de agosto de 1876
87,Manuel Costas Arce,28 de noviembre de 1874 - 18 de enero de 1875,Única,"Por ausencia del presidente Pardo, en su calid...",Encargado del Poder Ejecutivo,Partido Civil,28 de noviembre de 1874 - 18 de enero de 1875,None,28 de noviembre de 1874,18 de enero de 1875
94,Juan Lizardo Montero Flores,6 de noviembre de 1881 - 28 de octubre de 1883...,Única,Sucesión constitucional (Vicepresidente) tras ...,Encargado del Poder Ejecutivo (Presidente tran...,Partido Civil,6 de noviembre de 1881 - 28 de octubre de 1883,141],6 de noviembre de 1881,28 de octubre de 1883
97,Manuel Antonio Arenas Merino,3 de diciembre - 3 de junio de 1886,Única,Presidente del Consejo de Ministros encargado ...,Presidente de la Junta Provisional de Gobierno,-,3 de diciembre - 3 de junio de 1886,None,3 de diciembre de 1886,3 de junio de 1886
99,Remigio Morales Bermúdez,10 de agosto de 1890 - 1 de abril de 1894 (†),Única,Elecciones[151],Presidente Constitucional,Partido Constitucional,10 de agosto de 1890 - 1 de abril de 1894,†),10 de agosto de 1890,1 de abril de 1894
100,Justiniano Borgoño Castañeda,1 de abril - 10 de agosto de 1894,Única,Sucesión constitucional[152] (2.º Vicepresidente),Encargado del Poder Ejecutivo (Presidente tran...,Partido Constitucional,1 de abril - 10 de agosto de 1894,None,1 de abril de 1894,10 de agosto de 1894
104,José Gabriel Eduardo Octavio López de Romaña y...,8 de septiembre de 1899 - 8 de septiembre de 1903,Única,Elecciones[156],Presidente Constitucional,Partido Civil- Partido Demócrata,8 de septiembre de 1899 - 8 de septiembre de 1903,None,8 de septiembre de 1899,8 de septiembre de 1903
109,Guillermo Enrique Billinghurst Angulo,24 de septiembre de 1912 - 4 de febrero de 1914,Única,Elecciones[162],Presidente Constitucional,Partido Demócrata,24 de septiembre de 1912 - 4 de febrero de 1914,None,24 de septiembre de 1912,4 de febrero de 1914
113,Manuel María Ponce Brousset,25-27 de agosto de 1930,Única,Designado por la Junta Militar tras la revuelt...,Presidente de la Junta Militar de Gobierno,(Militar),25-27 de agosto de 1930,None,25 de agosto de 1930,27 de agosto de 1930
115,Francisco Mariano Holguín Maldonado,1 de marzo de 1931 (6 horas),Única,Designación presidencial transitoria tras renu...,Presidente de la Asamblea de Notables,(Religioso),1 de marzo de 1931 - 1 de marzo de 1931,6 horas),1 de marzo de 1931,1 de marzo de 1931
116,Ricardo Leoncio Elías Arias,1-5 de marzo de 1931,Única,"Elección transitoria por Junta de Notables, po...",Presidente de la Junta Provisoria de Gobierno,(Militar),1-5 de marzo de 1931,None,1 de marzo de 1931,5 de marzo de 1931
117,Gustavo Adolfo Jiménez Saldías,5-11 de marzo de 1931,Única,Golpe de Estado[174],Presidente de la Junta Transitoria de Gobierno,(Militar),5-11 de marzo de 1931,None,5 de marzo de 1931,11 de marzo de 1931
118,David Samanez Ocampo y Sobrino,11 de marzo - 8 de diciembre de 1931,Única,Designación transitoria tras renuncia de Jimén...,Presidente de la Junta Nacional Gobierno,-,11 de marzo - 8 de diciembre de 1931,None,11 de marzo de 1931,8 de diciembre de 1931
123,Alfredo Solf y Muro,3-31 de mayo de 1942,Única,Encargado interino durante el viaje de Manuel ...,-,-,3-31 de mayo de 1942,None,3 de mayo de 1942,31 de mayo de 1942
124,José Luis Pablo Bustamante y Rivero,28 de julio de 1945 - 29 de octubre de 1948,Única,Elecciones[183],Presidente Constitucional,FDN,28 de julio de 1945 - 29 de octubre de 1948,None,28 de julio de 1945,29 de octubre de 1948
130,Ricardo Pío Pérez Godoy,18 de julio de 1962 - 3 de marzo de 1963,Única,Golpe de Estado[190],Presidente de la Junta Militar de Gobierno,(Militar),18 de julio de 1962 - 3 de marzo de 1963,None,18 de julio de 1962,3 de marzo de 1963
131,Nicolás Eduardo Lindley López,3 de marzo de 1963 - 28 de julio de 1963,Única,Relevo institucional (segundo al mando).,Presidente de la Junta Militar de Gobierno,(Militar),3 de marzo de 1963 - 28 de julio de 1963,None,3 de marzo de 1963,28 de julio de 1963
133,Juan Francisco Velasco Alvarado,3 de octubre de 1968 - 29 de agosto de 1975,Única,Golpe de Estado[192],Presidente de la República (Gobierno Revolucio...,(Militar),3 de octubre de 1968 - 29 de agosto de 1975,None,3 de octubre de 1968,29 de agosto de 1975
134,Francisco Remigio Morales-Bermúdez Cerrutti,30 de agosto de 1975 - 28 de julio de 1980,Única,Golpe de Estado[193],Presidente de la República (Gobierno Revolucio...,(Militar),30 de agosto de 1975 - 28 de julio de 1980,None,30 de agosto de 1975,28 de julio de 1980
138,Valentín Toribio Demetrio Agustín Paniagua Cor...,22 de noviembre de 2000 - 28 de julio de 2001,Única,Sucesión constitucional (Presidente del Congre...,Presidente Constitucional,AP,22 de noviembre de 2000 - 28 de julio de 2001,None,22 de noviembre de 2000,28 de julio de 2001
139,Alejandro Celestino Toledo Manrique,28 de julio de 2001 - 28 de julio de 2006,Única,Elecciones[210],Presidente Constitucional,Perú Posible,28 de julio de 2001 - 28 de julio de 2006,None,28 de julio de 2001,28 de julio de 2006
141,Ollanta Moisés Humala Tasso,28 de julio de 2011 - 28 de julio de 2016,Única,Elecciones[212],Presidente Constitucional,PNP/Gana Perú,28 de julio de 2011 - 28 de julio de 2016,None,28 de julio de 2011,28 de julio de 2016
142,Pedro Pablo Kuczynski Godard,28 de julio de 2016 - 23 de marzo de 2018,Única,Elecciones[213][214][215],Presidente Constitucional,PPK,28 de julio de 2016 - 23 de marzo de 2018,None,28 de julio de 2016,23 de marzo de 2018
143,Martín Alberto Vizcarra Cornejo,23 de marzo de 2018 - 9 de noviembre de 2020,Única,Sucesión constitucional tras renuncia de PPK (...,Presidente Constitucional,Independiente,23 de marzo de 2018 - 9 de noviembre de 2020,None,23 de marzo de 2018,9 de noviembre de 2020
144,Manuel Arturo Merino de Lama,10-15 de noviembre de 2020,Única,Sucesión constitucional tras vacancia de Vizca...,Presidente Constitucional[n 15],AP,10-15 de noviembre de 2020,None,10 de noviembre de 2020,15 de noviembre de 2020
145,Francisco Rafael Sagasti Hochhausler,17 de noviembre de 2020 - 28 de julio de 2021,Única,Sucesión constitucional tras renuncia de Merin...,Presidente Constitucional,PM,17 de noviembre de 2020 - 28 de julio de 2021,None,17 de noviembre de 2020,28 de julio de 2021
146,José Pedro Castillo Terrones,28 de julio de 2021 - 7 de diciembre de 2022,Única,Elecciones[234],Presidente Constitucional,PL Independiente,28 de julio de 2021 - 7 de diciembre de 2022,None,28 de julio de 2021,7 de diciembre de 2022
147,Dina Ercilia Boluarte Zegarra,7 de diciembre de 2022 - 10 de octubre de 2025,Única,Sucesión constitucional tras vacancia de Casti...,Presidente Constitucional,Independiente,7 de diciembre de 2022 - 10 de octubre de 2025,None,7 de diciembre de 2022,10 de octubre de 2025
148,José Enrique Jerí Oré,10 de octubre de 2025 - 17 de febrero de 2026,Única,Sucesión constitucional tras vacancia de Bolua...,Presidente Constitucional,SP,10 de octubre de 2025 - 17 de febrero de 2026,None,10 de octubre de 2025,17 de febrero de 2026
149,José María Balcázar Zelada,18 de febrero de 2026 - En el cargo,Única,Sucesión constitucional tras censura de Jerí; ...,Presidente Constitucional,PL,18 de febrero de 2026 - En el cargo,None,18 de febrero de 2026,None

In [86]:
presisAll.loc[presisAll["Vez"] == "Única", "Vez"] = 1

In [87]:
presisAll.Vez.value_counts()

Vez
1      62
2.ª    32
1.ª    30
3.ª     8
4.ª     7
3       4
2       2
2.º     2
5.ª     1
1.º     1
0       1
Name: count, dtype: int64

In [88]:
# 1. Extract only the digits from the column
presisAll["Vez"] = presisAll["Vez"].astype(str).str.extract(r"(\d+)")

# 2. Convert the column to numeric integers (handles any potential missing values as NaN)
presisAll["Vez"] = pd.to_numeric(presisAll["Vez"])
presisAll.Vez.value_counts()

Vez
1    93
2    36
3    12
4     7
5     1
0     1
Name: count, dtype: int64

In [89]:
presisAll.Partido.value_counts(dropna=False)

Partido
NaN                                 86
(Militar)                           16
Partido Civil                       11
-                                    7
Partido Constitucional               4
AP                                   4
Partido Demócrata                    2
Independiente                        2
APRA                                 2
C90                                  1
SP                                   1
PL Independiente                     1
PM                                   1
PPK                                  1
PNP/Gana Perú                        1
Perú Posible                         1
Partido Restaurado                   1
MDP                                  1
FDN                                  1
Coalición Conservadora               1
UR                                   1
(Religioso)                          1
Partido Civil- Partido Demócrata     1
Chile_invasión                       1
PL                                   1
Name: count, dtype: int64

In [92]:
presisAll[presisAll.Partido.isnull()]['Nombre'].to_list()

['José de San Martín y Matorras',
 'José Bernardo de Tagle y Portocarrero',
 'José Domingo de la Mar Cortázar',
 'José Bernardo de Tagle y Portocarrero',
 'José Mariano de la Riva-Agüero y Sánchez-Boquete',
 'Francisco Valdivieso y Prada',
 'Antonio José de Sucre y Alcalá',
 'José Mariano de la Riva-Agüero y Sánchez-Boquete',
 'José Bernardo de Tagle y Portocarrero',
 'Simón José Antonio de la Santísima Trinidad Bolívar Ponte y Palacios Blanco',
 'Simón José Antonio de la Santísima Trinidad Bolívar Ponte y Palacios Blanco',
 'José Domingo de la Mar Cortázar',
 'José Domingo de la Mar Cortázar',
 'José Hipólito Unanue y Pavón',
 'José Hipólito Unanue y Pavón',
 'Andrés de Santa Cruz y Calaumana',
 'José Domingo de la Mar Cortázar',
 'Manuel Salazar y Baquíjano',
 'Manuel Salazar y Baquíjano',
 'Antonio Gutiérrez de la Fuente',
 'Agustín Gamarra Messia',
 'Antonio Gutiérrez de la Fuente',
 'Antonio Gutiérrez de la Fuente',
 'Juan Bautista Eléspuru',
 'Andrés Reyes y Buitrón',
 'Andrés Reyes y Buitrón',
 'Manuel Tellería Vicuña',
 'José Braulio del Camporredondo Cisneros',
 'Luis José de Orbegoso y Moncada',
 'Pedro Pablo Bermúdez Ascarza',
 'Manuel Salazar y Baquíjano',
 'Manuel Salazar y Baquíjano',
 'Felipe Santiago Salaverry del Solar',
 'Juan Ángel Bujanda',
 'Juan José Salas',
 'Juan Bautista de Lavalle y Zugasti',
 'Juan Francisco de Vidal La Hoz',
 'Andrés de Santa Cruz y Calaumana',
 'Juan Pío de Tristán y Moscoso',
 'Luis José de Orbegoso[65]',
 'José de la Riva-Agüero[69]',
 'Ramón Herrera y Rodado[71][68]',
 'Juan Pío de Tristán y Moscoso[72]',
 'Agustín Gamarra Messia',
 'Antonio Gutiérrez de la Fuente',
 'Antonio Gutiérrez de la Fuente',
 'Manuel Ignacio de Vivanco Iturralde',
 'Manuel Menéndez Gorozabel',
 'Manuel Menéndez Gorozabel',
 'Manuel Menéndez Gorozabel',
 'Juan Crisóstomo Torrico y Bargas',
 'Juan Bautista de Lavalle y Zugasti',
 'Juan Francisco de Vidal La Hoz',
 'Juan Francisco de Vidal La Hoz',
 'Justo Modesto Figuerola de Estrada',
 'Manuel Ignacio de Vivanco Iturralde',
 'Eleuterio Aramburú',
 'José Rufino Pompeyo Echenique Benavente',
 'Juan Antonio Pezet y Rodríguez de la Piedra',
 'Domingo Elías Carbajo',
 'Domingo Nieto y Márquez',
 'Ramón Castilla y Marquesado',
 'Justo Modesto Figuerola de Estrada',
 'Manuel Menéndez Gorozabel',
 'Ramón Castilla y Marquesado',
 'José Rufino Pompeyo Echenique Benavente',
 'Ramón Castilla y Marquesado',
 'José Miguel Medina Elera',
 'Manuel Ignacio de Vivanco Iturralde',
 'José María Raygada y Gallo',
 'Miguel de San Román y Meza',
 'Juan Manuel del Mar Bernedo',
 'Miguel de San Román y Meza',
 'Ramón Castilla y Marquesado',
 'Pedro Diez Canseco Corbacho',
 'Juan Antonio Pezet y Rodríguez de la Piedra',
 'Pedro Diez Canseco Corbacho',
 'Mariano Ignacio Prado Ochoa',
 'Luis La Puerta de Mendoza',
 'Pedro Diez Canseco Corbacho',
 'Pedro Diez Canseco Corbacho',
 'Antonio Gutiérrez de la Fuente',
 'Francisco Diez-Canseco Corbacho',
 'José Balta y Montero',
 'Tomás Gutiérrez',
 'Mariano Herencia-Zevallos y Larrauri']

In [93]:
#1mil,2, abog,3med,4teo,5emp

raw_text = """
 'José de San Martín y Matorras',1
 'José Bernardo de Tagle y Portocarrero',1
 'José Domingo de la Mar Cortázar',1
 'José Bernardo de Tagle y Portocarrero',1
 'José Mariano de la Riva-Agüero y Sánchez-Boquete',1
 'Francisco Valdivieso y Prada',2
 'Antonio José de Sucre y Alcalá',1
 'José Mariano de la Riva-Agüero y Sánchez-Boquete',1
 'José Bernardo de Tagle y Portocarrero',1
 'Simón José Antonio de la Santísima Trinidad Bolívar Ponte y Palacios Blanco',1
 'Simón José Antonio de la Santísima Trinidad Bolívar Ponte y Palacios Blanco',1
 'José Domingo de la Mar Cortázar',1
 'José Domingo de la Mar Cortázar',1
 'José Hipólito Unanue y Pavón',3
 'José Hipólito Unanue y Pavón',3
 'Andrés de Santa Cruz y Calaumana',1
 'José Domingo de la Mar Cortázar',1
 'Manuel Salazar y Baquíjano',1
 'Manuel Salazar y Baquíjano',1
 'Antonio Gutiérrez de la Fuente',1
 'Agustín Gamarra Messia',1
 'Antonio Gutiérrez de la Fuente',1
 'Antonio Gutiérrez de la Fuente',1
 'Juan Bautista Eléspuru',1
 'Andrés Reyes y Buitrón',1
 'Andrés Reyes y Buitrón',1
 'Manuel Tellería Vicuña',2
 'José Braulio del Camporredondo Cisneros',4
 'Luis José de Orbegoso y Moncada',1
 'Pedro Pablo Bermúdez Ascarza',1
 'Manuel Salazar y Baquíjano',1
 'Manuel Salazar y Baquíjano',1
 'Felipe Santiago Salaverry del Solar',1
 'Juan Ángel Bujanda',1
 'Juan José Salas',1
 'Juan Bautista de Lavalle y Zugasti',1
 'Juan Francisco de Vidal La Hoz',1
 'Andrés de Santa Cruz y Calaumana',1
 'Juan Pío de Tristán y Moscoso',1
 'Luis José de Orbegoso[65]',1
 'José de la Riva-Agüero[69]',1
 'Ramón Herrera y Rodado[71][68]',1
 'Juan Pío de Tristán y Moscoso[72]',1
 'Agustín Gamarra Messia',1
 'Antonio Gutiérrez de la Fuente',1
 'Antonio Gutiérrez de la Fuente',1
 'Manuel Ignacio de Vivanco Iturralde',1
 'Manuel Menéndez Gorozabel',5
 'Manuel Menéndez Gorozabel',5
 'Manuel Menéndez Gorozabel',5
 'Juan Crisóstomo Torrico y Bargas',1
 'Juan Bautista de Lavalle y Zugasti',1
 'Juan Francisco de Vidal La Hoz',1
 'Juan Francisco de Vidal La Hoz',1
 'Justo Modesto Figuerola de Estrada',2
 'Manuel Ignacio de Vivanco Iturralde',1
 'Eleuterio Aramburú',1
 'José Rufino Pompeyo Echenique Benavente',1
 'Juan Antonio Pezet y Rodríguez de la Piedra',1
 'Domingo Elías Carbajo',5
 'Domingo Nieto y Márquez',1
 'Ramón Castilla y Marquesado',1
 'Justo Modesto Figuerola de Estrada',1
 'Manuel Menéndez Gorozabel',5
 'Ramón Castilla y Marquesado',1
 'José Rufino Pompeyo Echenique Benavente',1
 'Ramón Castilla y Marquesado',1
 'José Miguel Medina Elera',1
 'Manuel Ignacio de Vivanco Iturralde',1
 'José María Raygada y Gallo',1
 'Miguel de San Román y Meza',1
 'Juan Manuel del Mar Bernedo',2
 'Miguel de San Román y Meza',1
 'Ramón Castilla y Marquesado',1
 'Pedro Diez Canseco Corbacho',1
 'Juan Antonio Pezet y Rodríguez de la Piedra',1
 'Pedro Diez Canseco Corbacho',1
 'Mariano Ignacio Prado Ochoa',1
 'Luis La Puerta de Mendoza',1
 'Pedro Diez Canseco Corbacho',1
 'Pedro Diez Canseco Corbacho',1
 'Antonio Gutiérrez de la Fuente',1
 'Francisco Diez-Canseco Corbacho',1
 'José Balta y Montero',1
 'Tomás Gutiérrez',1
 'Mariano Herencia-Zevallos y Larrauri',1"""


# Split by line, split by comma, take the right side, and convert to integer
numbers_only = [int(line.split(',')[-1].strip()) for line in raw_text.strip().split('\n')]

print(numbers_only)

[1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 5, 5, 1, 1, 1, 1, 2, 1, 1, 1, 1, 5, 1, 1, 1, 5, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [94]:
presisAll[~presisAll.Partido.isnull()]['Nombre'].to_list()

['Manuel Justo Pardo y Lavalle',
 'Manuel Costas Arce',
 'Mariano Ignacio Prado Ochoa',
 'Luis La Puerta de Mendoza',
 'Luis La Puerta de Mendoza',
 'José Nicolás Baltazar Fernández de Piérola y Villena',
 'Patricio Lynch',
 'Francisco García-Calderón Landa',
 'Juan Lizardo Montero Flores',
 'Miguel Iglesias Pino de Arce',
 'Andrés Avelino Cáceres Dorregaray',
 'Manuel Antonio Arenas Merino',
 'Andrés Avelino Cáceres Dorregaray',
 'Remigio Morales Bermúdez',
 'Justiniano Borgoño Castañeda',
 'Andrés Avelino Cáceres Dorregaray',
 'Manuel González de Candamo e Iriarte',
 'José Nicolás Baltazar Fernández de Piérola y Villena',
 'José Gabriel Eduardo Octavio López de Romaña y Alvizuri',
 'Manuel González de Candamo e Iriarte',
 'Serapio Calderón Lazo de la Vega',
 'José Simón Pardo y Barreda',
 'Augusto Bernardino Leguía y Salcedo',
 'Guillermo Enrique Billinghurst Angulo',
 'Óscar Raimundo Benavides Larrea',
 'José Simón Pardo y Barreda',
 'Augusto Bernardino Leguía y Salcedo',
 'Manuel María Ponce Brousset',
 'Luis Miguel Sánchez Cerro',
 'Francisco Mariano Holguín Maldonado',
 'Ricardo Leoncio Elías Arias',
 'Gustavo Adolfo Jiménez Saldías',
 'David Samanez Ocampo y Sobrino',
 'Luis Miguel Sánchez Cerro',
 'Gustavo Adolfo Jiménez Saldías',
 'Óscar Raimundo Benavides Larrea',
 'Manuel Carlos Prado y Ugarteche',
 'Alfredo Solf y Muro',
 'José Luis Pablo Bustamante y Rivero',
 'Manuel Arturo Odría Amoretti',
 'Manuel Arturo Odría Amoretti',
 'Zenón Noriega Agüero',
 'Zenón Noriega Agüero',
 'Manuel Carlos Prado y Ugarteche',
 'Ricardo Pío Pérez Godoy',
 'Nicolás Eduardo Lindley López',
 'Fernando Sergio Marcelo Marcos Belaúnde Terry',
 'Juan Francisco Velasco Alvarado',
 'Francisco Remigio Morales-Bermúdez Cerrutti',
 'Fernando Sergio Marcelo Marcos Belaúnde Terry',
 'Alan Gabriel Ludwig García Pérez',
 'Alberto Kenya Fujimori Inomoto[n 14]',
 'Valentín Toribio Demetrio Agustín Paniagua Corazao',
 'Alejandro Celestino Toledo Manrique',
 'Alan Gabriel Ludwig García Pérez',
 'Ollanta Moisés Humala Tasso',
 'Pedro Pablo Kuczynski Godard',
 'Martín Alberto Vizcarra Cornejo',
 'Manuel Arturo Merino de Lama',
 'Francisco Rafael Sagasti Hochhausler',
 'José Pedro Castillo Terrones',
 'Dina Ercilia Boluarte Zegarra',
 'José Enrique Jerí Oré',
 'José María Balcázar Zelada']

In [97]:

# 6eco 7 ing 8arq
raw_text2 = """
'Manuel Justo Pardo y Lavalle',6
 'Manuel Costas Arce',5
 'Mariano Ignacio Prado Ochoa',1
 'Luis La Puerta de Mendoza',1
 'Luis La Puerta de Mendoza',1
 'José Nicolás Baltazar Fernández de Piérola y Villena',5
 'Patricio Lynch',1
 'Francisco García-Calderón Landa',2
 'Juan Lizardo Montero Flores',1
 'Miguel Iglesias Pino de Arce',1
 'Andrés Avelino Cáceres Dorregaray',1
 'Manuel Antonio Arenas Merino',2
 'Andrés Avelino Cáceres Dorregaray',1
 'Remigio Morales Bermúdez',1
 'Justiniano Borgoño Castañeda',1
 'Andrés Avelino Cáceres Dorregaray',1
 'Manuel González de Candamo e Iriarte',5
 'José Nicolás Baltazar Fernández de Piérola y Villena',5
 'José Gabriel Eduardo Octavio López de Romaña y Alvizuri',7
 'Manuel González de Candamo e Iriarte',5
 'Serapio Calderón Lazo de la Vega',2
 'José Simón Pardo y Barreda',2
 'Augusto Bernardino Leguía y Salcedo',5
 'Guillermo Enrique Billinghurst Angulo',5
 'Óscar Raimundo Benavides Larrea',1
 'José Simón Pardo y Barreda',2
 'Augusto Bernardino Leguía y Salcedo',5
 'Manuel María Ponce Brousset',1
 'Luis Miguel Sánchez Cerro',1
 'Francisco Mariano Holguín Maldonado',4
 'Ricardo Leoncio Elías Arias',2
 'Gustavo Adolfo Jiménez Saldías',1
 'David Samanez Ocampo y Sobrino',5
 'Luis Miguel Sánchez Cerro',1
 'Gustavo Adolfo Jiménez Saldías',1
 'Óscar Raimundo Benavides Larrea',1
 'Manuel Carlos Prado y Ugarteche',7
 'Alfredo Solf y Muro',2
 'José Luis Pablo Bustamante y Rivero',2
 'Manuel Arturo Odría Amoretti',1
 'Manuel Arturo Odría Amoretti',1
 'Zenón Noriega Agüero',1
 'Zenón Noriega Agüero',1
 'Manuel Carlos Prado y Ugarteche',7
 'Ricardo Pío Pérez Godoy',1
 'Nicolás Eduardo Lindley López',1
 'Fernando Sergio Marcelo Marcos Belaúnde Terry',8
 'Juan Francisco Velasco Alvarado',1
 'Francisco Remigio Morales-Bermúdez Cerrutti',1
 'Fernando Sergio Marcelo Marcos Belaúnde Terry',8
 'Alan Gabriel Ludwig García Pérez',1
 'Alberto Kenya Fujimori Inomoto[n 14]',7
 'Valentín Toribio Demetrio Agustín Paniagua Corazao',2
 'Alejandro Celestino Toledo Manrique',6
 'Alan Gabriel Ludwig García Pérez',2
 'Ollanta Moisés Humala Tasso',1
 'Pedro Pablo Kuczynski Godard',6
 'Martín Alberto Vizcarra Cornejo',7
 'Manuel Arturo Merino de Lama',5
 'Francisco Rafael Sagasti Hochhausler',7
 'José Pedro Castillo Terrones',9
 'Dina Ercilia Boluarte Zegarra',2
 'José Enrique Jerí Oré',2
 'José María Balcázar Zelada,2 
"""

# Split by line, split by comma, take the right side, and convert to integer
numbers_only2 = [int(line.split(',')[-1].strip()) for line in raw_text2.strip().split('\n')]

print(numbers_only2)

[6, 5, 1, 1, 1, 5, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 5, 5, 7, 5, 2, 2, 5, 5, 1, 2, 5, 1, 1, 4, 2, 1, 5, 1, 1, 1, 7, 2, 2, 1, 1, 1, 1, 7, 1, 1, 8, 1, 1, 8, 1, 7, 2, 6, 2, 1, 6, 7, 5, 7, 9, 2, 2, 2]

In [103]:
presisAll['perfil']=numbers_only + numbers_only2

presisAll['perfil']=presisAll['perfil'].replace({1:"militar",2:"abogado",3:"medico",4:'teologo o sacerdote',5:"empresario",6:'economista', 7:"ingeniero", 8:"arquitecto",
                             9:"maestro"})

In [105]:
presisAll['perfil'].value_counts()

perfil
militar                102
abogado                 17
empresario              15
ingeniero                6
economista               3
medico                   2
teologo o sacerdote      2
arquitecto               2
maestro                  1
Name: count, dtype: int64

In [106]:
from datetime import datetime
import locale
import pandas as pd

# Set Spanish locale
locale.setlocale(locale.LC_TIME, "es_ES.UTF-8")

# Updated lambda function: Checks if x is valid before attempting to parse
spanish_cellToGoodDates = lambda x: (
    datetime.strptime(x, "%d de %B de %Y")
    if pd.notna(x) and isinstance(x, str)
    else None
)

# Apply parsing safely across the columns
presisAll[["startGob", "endGob"]] = presisAll[["InicioGob", "FinGob"]].map(
    spanish_cellToGoodDates
)

presisAll

,Nombre,Mandato,Vez,Asunción,Título,Partido,Periodo,temp,InicioGob,FinGob,perfil,startGob,endGob
0,José de San Martín y Matorras,3 de agosto de 1821 - 20 de septiembre de 1822,1,Cabildo abierto en Lima.[3][n 5],Protector del Perú,NaN,3 de agosto de 1821 - 20 de septiembre de 1822,None,3 de agosto de 1821,20 de septiembre de 1822,militar,1821-08-03,1822-09-20
1,José Bernardo de Tagle y Portocarrero,19 de enero - 21 de agosto de 1822,1,"Encargado interino, por viaje de San Martín a ...",Supremo Delegado,NaN,19 de enero - 21 de agosto de 1822,None,19 de enero de 1822,21 de agosto de 1822,militar,1822-01-19,1822-08-21
2,José Domingo de la Mar Cortázar,21 de septiembre de 1822 - 27 de febrero de 1823,1,Elección por el Congreso de entre sus miembros...,Presidente de la Suprema Junta Gubernativa del...,NaN,21 de septiembre de 1822 - 27 de febrero de 1823,None,21 de septiembre de 1822,27 de febrero de 1823,militar,1822-09-21,1823-02-27
3,José Bernardo de Tagle y Portocarrero,27-28 de febrero de 1823,2,Elegido provisionalmente por el Congreso tras ...,Encargado del Poder Ejecutivo,NaN,27-28 de febrero de 1823,None,27 de febrero de 1823,28 de febrero de 1823,militar,1823-02-27,1823-02-28
4,José Mariano de la Riva-Agüero y Sánchez-Boquete,28 de febrero - 23 de junio de 1823,1,Impuesto por los militares tras el Motín de Ba...,Presidente de la República,NaN,28 de febrero - 23 de junio de 1823,None,28 de febrero de 1823,23 de junio de 1823,militar,1823-02-28,1823-06-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,Francisco Rafael Sagasti Hochhausler,17 de noviembre de 2020 - 28 de julio de 2021,1,Sucesión constitucional tras renuncia de Merin...,Presidente Constitucional,PM,17 de noviembre de 2020 - 28 de julio de 2021,None,17 de noviembre de 2020,28 de julio de 2021,ingeniero,2020-11-17,2021-07-28
146,José Pedro Castillo Terrones,28 de julio de 2021 - 7 de diciembre de 2022,1,Elecciones[234],Presidente Constitucional,PL Independiente,28 de julio de 2021 - 7 de diciembre de 2022,None,28 de julio de 2021,7 de diciembre de 2022,maestro,2021-07-28,2022-12-07
147,Dina Ercilia Boluarte Zegarra,7 de diciembre de 2022 - 10 de octubre de 2025,1,Sucesión constitucional tras vacancia de Casti...,Presidente Constitucional,Independiente,7 de diciembre de 2022 - 10 de octubre de 2025,None,7 de diciembre de 2022,10 de octubre de 2025,abogado,2022-12-07,2025-10-10
148,José Enrique Jerí Oré,10 de octubre de 2025 - 17 de febrero de 2026,1,Sucesión constitucional tras vacancia de Bolua...,Presidente Constitucional,SP,10 de octubre de 2025 - 17 de febrero de 2026,None,10 de octubre de 2025,17 de febrero de 2026,abogado,2025-10-10,2026-02-17
149,José María Balcázar Zelada,18 de febrero de 2026 - En el cargo,1,Sucesión constitucional tras censura de Jerí; ...,Presidente Constitucional,PL,18 de febrero de 2026 - En el cargo,None,18 de febrero de 2026,None,abogado,2026-02-18,NaT

In [107]:
presisAll.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Nombre     150 non-null    object
 1   Mandato    150 non-null    object
 2   Vez        150 non-null    int64
 3   Asunción   145 non-null    object
 4   Título     146 non-null    object
 5   Partido    64 non-null     object
 6   Periodo    150 non-null    object
 7   temp       15 non-null     object
 8   InicioGob  150 non-null    object
 9   FinGob     149 non-null    object
 10  perfil     150 non-null    object
 11  startGob   150 non-null    datetime64[ns]
 12  endGob     149 non-null    datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(10)
memory usage: 15.4+ KB

In [108]:
presisAll.to_pickle('presisAll.pkl')
presisAll.columns

Index(['Nombre', 'Mandato', 'Vez', 'Asunción', 'Título', 'Partido', 'Periodo',
       'temp', 'InicioGob', 'FinGob', 'perfil', 'startGob', 'endGob'],
      dtype='object')

In [ ]:
selectCols=['Nombre', 'Vez', 'Asunción', 'Título', 'Partido', 'startGob', 'endGob']
PresisPeru=presisAll.loc[:,selectCols]

PresisPeru.info()

In [ ]:
PresisPeru.Vez.value_counts()

In [ ]:
PresisPeru[PresisPeru.Vez=='-']

In [ ]:
PresisPeru.to_pickle('PresisPeru.pkl')

In [ ]:
# import pandas as pd

presisFull=pd.read_pickle('presisFull.pkl')

In [ ]:
presisFull=pd.read_pickle('presisFull.pkl')

In [ ]:
presisFull