In [41]:
# coding: utf-8

import pandas as pd
from urllib.parse import quote

# Pull tables from Wikipedia
base  = "https://es.wikipedia.org/wiki/" 
path  = "Anexo:Ministros_de_Salud_del_Perú"
url   = base + quote(path)          # Per%C3%BA

# Add a User-Agent header to mimic a browser and avoid 403 Forbidden error
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
saludTables = pd.read_html(url, flavor="bs4",
                      attrs={"class": "wikitable sortable"}, storage_options={"User-Agent": 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'})

In [42]:
len(saludTables)

1

In [43]:
saludTables[0].head()

  Titular                              Partido          Presidente  \
   Imagen                       Nombre Partido          Presidente
0     NaN    Armando Montes de Peralta     NaN  Óscar R. Benavides
1     NaN     Fortunato Quesada Larrea     NaN  Óscar R. Benavides
2     NaN     Roque A. Saldías Maninat     NaN  Óscar R. Benavides
3     NaN               Rafael Escardó     NaN  Óscar R. Benavides
4     NaN  Guillermo Almenara Irigoyen     NaN  Óscar R. Benavides

                    Período
                     Inicio                     Final
0      9 de octubre de 1935       12 de abril de 1936
1       13 de abril de 1936  23 de septiembre de 1936
2  24 de septiembre de 1936    2 de noviembre de 1937
3    3 de noviembre de 1937       19 de abril de 1938
4       30 de abril de 1938    7 de diciembre de 1939

In [44]:
saluda=saludTables[0]
saluda.columns

MultiIndex([(   'Titular',     'Imagen'),
            (   'Titular',     'Nombre'),
            (   'Partido',    'Partido'),
            ('Presidente', 'Presidente'),
            (   'Período',     'Inicio'),
            (   'Período',      'Final')],
           )

In [45]:
saluda.columns=[b for a,b in saluda.columns]

In [46]:
salud=saluda.copy()
salud.drop(columns=["Imagen"],inplace=True)

# date text cleaning

In [47]:
salud[salud["Inicio"].isnull()]

   Nombre Partido Presidente Inicio Final
83    NaN     NaN        NaN    NaN   NaN

In [48]:
salud=salud[~salud["Inicio"].isnull()]

In [49]:
salud[salud["Final"].isnull()]

Empty DataFrame
Columns: [Nombre, Partido, Presidente, Inicio, Final]
Index: []

In [50]:
salud.reset_index(drop=True,inplace=True)
salud.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Nombre      83 non-null     object
 1   Partido     50 non-null     object
 2   Presidente  83 non-null     object
 3   Inicio      83 non-null     object
 4   Final       83 non-null     object
dtypes: object(5)
memory usage: 3.4+ KB

In [51]:
salud[salud.Inicio.str.contains(r"del|\[",regex=True)]

,Nombre,Partido,Presidente,Inicio,Final
67,Zulema Tomás Gonzáles,Independiente,Martín Vizcarra,7 de enero de 2019[1],15 de noviembre de 2019[2]
68,Elizabeth Hinostroza Pereyra,Independiente,Martín Vizcarra,18 de noviembre de 2019[3],20 de marzo de 2020[4]
69,Víctor Zamora Mesía,Frente Amplio,Martín Vizcarra,20 de marzo de 2020[5],15 de julio de 2020[6]
70,Pilar Mazzetti Soler,Independiente,Martín Vizcarra,15 de julio de 2020[7],10 de noviembre de 2020[8]
71,Abel Salinas Rivas,Partido Aprista Peruano,Manuel Merino,11 de noviembre de 2020[9],15 de noviembre de 2020[10]
72,Pilar Mazzetti Soler,Independiente,Francisco Sagasti,18 de noviembre de 2020[11],12 de febrero de 2021[12]
73,Óscar Ugarte Ubilluz,Juntos por el Perú,Francisco Sagasti,13 de febrero de 2021[13],28 de julio de 2021[14]
74,Hernando Cevallos Flores,Frente Amplio,Pedro Castillo,29 de julio de 2021[14],8 de febrero de 2022
82,Juan Carlos Velasco Guerrero,Independiente,José María Balcázar,11 de marzo de 2026[15],En el cargo

In [52]:
salud['Inicio']=salud['Inicio'].str.replace(r'\[.*\]', '', regex=True)

In [53]:
salud[salud.Final.str.contains(r"del|\[",regex=True)]

,Nombre,Partido,Presidente,Inicio,Final
67,Zulema Tomás Gonzáles,Independiente,Martín Vizcarra,7 de enero de 2019,15 de noviembre de 2019[2]
68,Elizabeth Hinostroza Pereyra,Independiente,Martín Vizcarra,18 de noviembre de 2019,20 de marzo de 2020[4]
69,Víctor Zamora Mesía,Frente Amplio,Martín Vizcarra,20 de marzo de 2020,15 de julio de 2020[6]
70,Pilar Mazzetti Soler,Independiente,Martín Vizcarra,15 de julio de 2020,10 de noviembre de 2020[8]
71,Abel Salinas Rivas,Partido Aprista Peruano,Manuel Merino,11 de noviembre de 2020,15 de noviembre de 2020[10]
72,Pilar Mazzetti Soler,Independiente,Francisco Sagasti,18 de noviembre de 2020,12 de febrero de 2021[12]
73,Óscar Ugarte Ubilluz,Juntos por el Perú,Francisco Sagasti,13 de febrero de 2021,28 de julio de 2021[14]

In [54]:

salud['Final']=salud['Final'].str.replace(r'\[.*\]', '', regex=True)

In [55]:
salud[salud["Inicio"].str.split("de").apply(len)!=3]

Empty DataFrame
Columns: [Nombre, Partido, Presidente, Inicio, Final]
Index: []

In [56]:
salud[salud["Final"].str.split("de").apply(len)!=3]

,Nombre,Partido,Presidente,Inicio,Final
82,Juan Carlos Velasco Guerrero,Independiente,José María Balcázar,11 de marzo de 2026,En el cargo

In [57]:
salud.loc[82,"Final"]=None

In [58]:
salud[salud.Inicio=='']

Empty DataFrame
Columns: [Nombre, Partido, Presidente, Inicio, Final]
Index: []

In [60]:
salud[salud.Final=='']

Empty DataFrame
Columns: [Nombre, Partido, Presidente, Inicio, Final]
Index: []

In [61]:
salud.loc[241,"Final"]=None

In [62]:
import numpy as np
from datetime import datetime, timedelta
import locale

# 1. Configurar locale (con fallback por si estás en Windows)
try:
    locale.setlocale(locale.LC_TIME, "es_ES.UTF-8")
except locale.Error:
    locale.setlocale(locale.LC_TIME, "Spanish_Spain.1252") # Windows

# Tu función lambda (agregamos validación por si hay NaN)
str_to_date = lambda x: datetime.strptime(x, "%d de %B de %Y") if pd.notna(x) else pd.NaT

salud[["Inicio", "Final"]] = salud[["Inicio", "Final"]].apply(lambda x: x.str.strip())

# Date format

In [63]:
# 2. Convertir a datetime
salud['fecha_start'] = salud['Inicio'].apply(str_to_date)
salud['fecha_end'] = salud['Final'].apply(str_to_date)

In [64]:
salud.info()

<class 'pandas.core.frame.DataFrame'>
Index: 84 entries, 0 to 241
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Nombre       83 non-null     object
 1   Partido      50 non-null     object
 2   Presidente   83 non-null     object
 3   Inicio       83 non-null     object
 4   Final        82 non-null     object
 5   fecha_start  83 non-null     datetime64[ns]
 6   fecha_end    82 non-null     datetime64[ns]
dtypes: datetime64[ns](2), object(5)
memory usage: 7.3+ KB

In [65]:
salud['cartera']='salud'

In [67]:
salud.rename(columns={'Final':"Fin"},inplace=True)

In [68]:
salud.to_pickle("salud.pkl")