In [2]:
# coding: utf-8

import pandas as pd
from urllib.parse import quote

# Pull tables from Wikipedia
base  = "https://es.wikipedia.org/wiki/"
path  = "Anexo:Presidentes_del_Consejo_de_Ministros_del_Perú"
url   = base + quote(path)          # Per%C3%BA

# Add a User-Agent header to mimic a browser and avoid 403 Forbidden error
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
primeTables = pd.read_html(url, flavor="bs4",
                      attrs={"class": "wikitable sortable"}, storage_options={"User-Agent": 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'})

In [3]:
len(primeTables)

3

In [4]:
prime0=primeTables[0].copy()
prime0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   (Titular, Imagen)       0 non-null      float64
 1   (Titular, Nombre)       79 non-null     object
 2   (Partido, Partido)      0 non-null      float64
 3   (Partido, Partido.1)    38 non-null     object
 4   (Gobierno, Gobierno)    0 non-null      float64
 5   (Gobierno, Gobierno.1)  79 non-null     object
 6   (Inicio, Inicio)        79 non-null     object
 7   (Fin, Fin)              79 non-null     object
dtypes: float64(3), object(5)
memory usage: 5.1+ KB

In [5]:
prime1=primeTables[1].copy()
prime1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112 entries, 0 to 111
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   (Titular, Imagen)       0 non-null      float64
 1   (Titular, Nombre)       111 non-null    object
 2   (Partido, Partido)      0 non-null      float64
 3   (Partido, Partido.1)    87 non-null     object
 4   (Gobierno, Gobierno)    0 non-null      float64
 5   (Gobierno, Gobierno.1)  111 non-null    object
 6   (Inicio, Inicio)        111 non-null    object
 7   (Fin, Fin)              110 non-null    object
dtypes: float64(3), object(5)
memory usage: 7.1+ KB

In [6]:
prime2=primeTables[2].copy()
prime2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 9 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   (Titular, Imagen)                         0 non-null      float64
 1   (Titular, Nombre)                         42 non-null     object
 2   (Partido, Partido)                        0 non-null      float64
 3   (Partido, Partido.1)                      42 non-null     object
 4   (Gobierno, Gobierno)                      0 non-null      float64
 5   (Gobierno, Gobierno.1)                    42 non-null     object
 6   (Inicio, Inicio)                          42 non-null     object
 7   (Fin, Fin)                                41 non-null     object
 8   (Tiempo en el cargo, Tiempo en el cargo)  42 non-null     object
dtypes: float64(3), object(6)
memory usage: 3.3+ KB

In [7]:
prime0.columns=[b for a,b in prime0.columns]
prime1.columns=[b for a,b in prime1.columns]
prime2.columns=[b for a,b in prime2.columns]

prime0.columns,prime1.columns,prime2.columns

(Index(['Imagen', 'Nombre', 'Partido', 'Partido.1', 'Gobierno', 'Gobierno.1',
        'Inicio', 'Fin'],
       dtype='object'),
 Index(['Imagen', 'Nombre', 'Partido', 'Partido.1', 'Gobierno', 'Gobierno.1',
        'Inicio', 'Fin'],
       dtype='object'),
 Index(['Imagen', 'Nombre', 'Partido', 'Partido.1', 'Gobierno', 'Gobierno.1',
        'Inicio', 'Fin', 'Tiempo en el cargo'],
       dtype='object'))

In [8]:
prime012=pd.concat([prime0,prime1,prime2],ignore_index=True)

In [9]:
# prime012=prime012[~prime012.isnull().all(axis=1)]
prime012.dropna(how='all',axis=0,inplace=True)

In [10]:
# Returns True if 'del' is in 'Inicio' OR 'del' is in 'Fin'
mask = prime012['Inicio'].str.contains('del', na=False) | prime012['Fin'].str.contains('del', na=False)

# Use the mask to filter your DataFrame
prime012[mask]

,Imagen,Nombre,Partido,Partido.1,Gobierno,Gobierno.1,Inicio,Fin,Tiempo en el cargo
192,NaN,Javier Pérez de Cuéllar de la Guerra,NaN,Unión por el Perú,NaN,Valentín Paniagua,22 de noviembre de 2000,28 de julio del 2001,8 meses y 6 días

In [11]:
prime012.loc[192,'Fin']='28 de octubre de 2001'

In [12]:
mask = prime012['Inicio'].str.contains(r'\[', na=False) | prime012['Fin'].str.contains(r'\[', na=False)
prime012[mask]

,Imagen,Nombre,Partido,Partido.1,Gobierno,Gobierno.1,Inicio,Fin,Tiempo en el cargo
218,NaN,Ántero Flores-Aráoz Esparza,NaN,Independiente,NaN,Manuel Merino,11 de noviembre de 2020[9],17 de noviembre de 2020,6 días
219,NaN,Violeta Bermúdez Valdivia,NaN,Independiente,NaN,Francisco Sagasti,18 de noviembre de 2020[10],28 de julio de 2021,8 meses y 7 días
220,NaN,Guido Bellido Ugarte,NaN,Perú Libre,NaN,Pedro Castillo,29 de julio de 2021[11],6 de octubre de 2021,2 meses y 8 días
222,NaN,Héctor Valer Pinto,NaN,Somos Perú,NaN,Pedro Castillo,1 de febrero de 2022,8 de febrero de 2022[12],7 días

In [13]:
columns_to_clean = prime012.columns

# Apply the fix only to those columns
prime012[columns_to_clean] = prime012[columns_to_clean].replace(r'\[\d+\]', '', regex=True)

In [14]:
prime012.reset_index(drop=True,inplace=False)

,Imagen,Nombre,Partido,Partido.1,Gobierno,Gobierno.1,Inicio,Fin,Tiempo en el cargo
0,NaN,José María Raygada y Gallo,NaN,Militar,NaN,Ramón Castilla (2.º gob.),14 de febrero de 1857,13 de mayo de 1858,NaN
1,NaN,Manuel Ortiz de Zevallos y García,NaN,NaN,NaN,Ramón Castilla (2.º gob.),13 de mayo de 1858,13 de julio de 1858,NaN
2,NaN,Miguel de San Román y Meza,NaN,Militar,NaN,Ramón Castilla (2.º gob.),13 de julio de 1858,24 de octubre de 1858,NaN
3,NaN,Miguel del Carpio y Melgar,NaN,NaN,NaN,Ramón Castilla (2.º gob.),1859,9 de junio de 1860,NaN
4,NaN,Juan Antonio Pezet Rodríguez,NaN,Militar,NaN,Ramón Castilla (2.º gob.),9 de junio de 1860,1862,NaN
...,...,...,...,...,...,...,...,...,...
227,NaN,Eduardo Arana Ysa,NaN,Independiente,NaN,José Jerí,10 de octubre de 2025,12 de octubre de 2025,4 meses y 29 días
228,NaN,Ernesto Álvarez Miranda,NaN,Partido Popular Cristiano,NaN,José Jerí,14 de octubre de 2025,17 de febrero de 2026,4 meses y 10 días
229,NaN,Ernesto Álvarez Miranda,NaN,Partido Popular Cristiano,NaN,José María Balcázar,18 de febrero de 2026,24 de febrero de 2026,4 meses y 10 días
230,NaN,Denisse Miralles Miralles,NaN,Independiente,NaN,José María Balcázar,24 de febrero de 2026,17 de marzo de 2026,21 días
231,NaN,Luis Arroyo Sánchez,NaN,Independiente,NaN,José María Balcázar,17 de marzo de 2026,NaN,2 meses y 18 días

# Time to get dates right

In [15]:
cols_to_check = ["Inicio", "Fin"]

# Apply the condition to both columns at once
mask = prime012[cols_to_check].apply(lambda x: x.str.split("de").str.len().fillna(0) != 3).any(axis=1)

prime012[mask]

,Imagen,Nombre,Partido,Partido.1,Gobierno,Gobierno.1,Inicio,Fin,Tiempo en el cargo
3,NaN,Miguel del Carpio y Melgar,NaN,NaN,NaN,Ramón Castilla (2.º gob.),1859,9 de junio de 1860,NaN
4,NaN,Juan Antonio Pezet Rodríguez,NaN,Militar,NaN,Ramón Castilla (2.º gob.),9 de junio de 1860,1862,NaN
5,NaN,Juan Antonio Ribeyro Estada,NaN,NaN,NaN,Ramón Castilla (2.º gob.),1862,24 de octubre de 1862,NaN
41,NaN,Camilo N. Carrillo Martínez,NaN,Marino,NaN,Lizardo Montero Flores,4 de septiembre de 1882,enero de 1883,NaN
42,NaN,Manuel Velarde Seoane,NaN,Militar,NaN,Lizardo Montero Flores,enero de 1883,abril de 1883,NaN
43,NaN,Mariano Nicolás Valcárcel,NaN,NaN,NaN,Lizardo Montero Flores,abril de 1883,octubre de 1883,NaN
87,NaN,José Pardo y Barreda,NaN,Partido Civil,NaN,Manuel Candamo Iriarte,8 de septiembre de 1903,18 de abril de 1904 14 de mayo de 1904,NaN
135,NaN,Carlos Arenas y Loayza,NaN,24 de diciembre de 1934,NaN,Óscar R. Benavides (2.º gob.),18 de mayo de 1935,NaN,NaN
147,NaN,Roque Saldías Maninat,NaN,Marino,NaN,Manuel A. Odría,9 de agosto de 1954,junio de 1956,NaN
148,NaN,Juan Mendoza Rodríguez,NaN,Militar,NaN,Manuel A. Odría,junio de 1956,28 de julio de 1956,NaN
233,NaN,Luis Arroyo Sánchez,NaN,Independiente,NaN,José María Balcázar,17 de marzo de 2026,NaN,2 meses y 18 días

In [16]:
prime012.loc[3,'Inicio']='31 de agosto de 1859'
prime012.loc[4,'Fin']="25 de enero de 1862"
prime012.loc[5,'Inicio']="25 de enero de 1862"

prime012.loc[41,'Fin']='10 de enero de 1883'
prime012.loc[42,'Inicio']='10 de enero de 1883'
prime012.loc[42,'Fin']='1 de abril de 1883'
prime012.loc[43,'Inicio']='1 de abril de 1883'
prime012.loc[43,'Fin']='1 de octubre de 1883'
prime012.loc[87,'Fin']='18 de abril de 1904'

prime012.loc[135,'Inicio']='24 de diciembre de 1934'
prime012.loc[135,'Fin']='18 de mayo de 1935'
prime012.loc[135,'Partido']=None


prime012.loc[147,'Fin']='15 de junio de 1956'
prime012.loc[148,'Inicio']='15 de junio de 1956'

prime012.loc[233,'Fin']=None

In [17]:
prime012[prime012.iloc[:,[6,7]].isna().any(axis=1)]

,Imagen,Nombre,Partido,Partido.1,Gobierno,Gobierno.1,Inicio,Fin,Tiempo en el cargo
233,NaN,Luis Arroyo Sánchez,NaN,Independiente,NaN,José María Balcázar,17 de marzo de 2026,None,2 meses y 18 días

In [18]:

# Finds rows where 'Nombre' contains anything that is NOT a letter or a space
prime012[prime012['Nombre'].str.contains(r'(', regex=False,na=False)]

,Imagen,Nombre,Partido,Partido.1,Gobierno,Gobierno.1,Inicio,Fin,Tiempo en el cargo
54,NaN,Raymundo Morales Arias (interino),NaN,NaN,NaN,Andrés Avelino Cáceres (1.º gob.),4 de octubre de 1887,8 de noviembre de 1887,NaN
60,NaN,Alberto Elmore Fernández de Córdoba (interino),NaN,NaN,NaN,Remigio Morales Bermúdez,25 de julio de 1891,14 de agosto de 1891,NaN
63,NaN,Federico Herrera (interino),NaN,Partido Constitucional,NaN,Remigio Morales Bermúdez,14 de octubre de 1891,27 de noviembre de 1891,NaN
65,NaN,Juan Ibarra y Ortiz (interino),NaN,Militar,NaN,Remigio Morales Bermúdez,14 de abril de 1892,2 de mayo de 1892,NaN
88,NaN,José Pardo y Barreda (continuación),NaN,Partido Civil,NaN,Serapio Calderón Chirinos,18 de abril de 1904,14 de mayo de 1904,NaN
131,NaN,José Matías Manzanilla Barrientos (continuación),NaN,NaN,NaN,Óscar R. Benavides (2.º gob.),30 de abril de 1933,29 de junio de 1933,NaN

In [19]:
import locale
from datetime import date, timedelta

# Set Spanish locale (use es_ES.utf8 or es_ES.UTF-8 depending on OS) - windows: "Spanish_Spain" or "Spanish_Spain.1252"
locale.setlocale(locale.LC_TIME, "es_ES.UTF-8")

from datetime import datetime


# Tu función lambda (agregamos validación por si hay NaN)
str_to_date = lambda x: datetime.strptime(x, "%d de %B de %Y") if pd.notna(x) else pd.NaT

# Apply parsing with datetime and locale
prime012[['fecha_start','fecha_end']]=prime012[['Inicio','Fin']].map(str_to_date)

In [20]:
prime012.info()

<class 'pandas.core.frame.DataFrame'>
Index: 232 entries, 0 to 233
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Imagen              0 non-null      float64
 1   Nombre              232 non-null    object
 2   Partido             0 non-null      float64
 3   Partido.1           167 non-null    object
 4   Gobierno            0 non-null      float64
 5   Gobierno.1          232 non-null    object
 6   Inicio              232 non-null    object
 7   Fin                 231 non-null    object
 8   Tiempo en el cargo  42 non-null     object
 9   fecha_start         232 non-null    datetime64[ns]
 10  fecha_end           231 non-null    datetime64[ns]
dtypes: datetime64[ns](2), float64(3), object(6)
memory usage: 29.9+ KB

In [21]:
prime012.drop(columns=['Imagen','Partido','Gobierno','Tiempo en el cargo'],inplace=True)
prime012.rename(columns={'Partido.1':'Partido','Gobierno.1':'Gobierno'},inplace=True)
prime012.info()

<class 'pandas.core.frame.DataFrame'>
Index: 232 entries, 0 to 233
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Nombre       232 non-null    object
 1   Partido      167 non-null    object
 2   Gobierno     232 non-null    object
 3   Inicio       232 non-null    object
 4   Fin          231 non-null    object
 5   fecha_start  232 non-null    datetime64[ns]
 6   fecha_end    231 non-null    datetime64[ns]
dtypes: datetime64[ns](2), object(5)
memory usage: 22.6+ KB

In [22]:
prime012.Partido.value_counts()

Partido
Militar                           38
Independiente                     36
Partido Civil                     13
Partido Constitucional            12
Partido Aprista Peruano            8
Acción Popular                     8
Marino                             7
Partido Demócrata                  6
Partido Democrático Reformista     5
Cambio 90 - Nueva Mayoría          4
Unión Revolucionaria               3
Movimiento Democrático Peruano     3
Cambio 90                          2
Perú Libre                         2
Peruanos por el Kambio             2
Perú Posible                       2
Partido Popular Cristiano          2
Frente Democrático Nacional        2
Partido Demócrata Cristiano        1
Clérigo                            1
Aviador                            1
Unión por el Perú                  1
Partido Humanista Peruano          1
Partido Nacionalista Peruano       1
24 de diciembre de 1934            1
Alianza para el Progreso           1
Partido Nacional Democrático       1
Frente Amplio                      1
Somos Perú                         1
Marino (r)                         1
Name: count, dtype: int64

In [23]:
prime012['fue_Militar']=prime012.Partido.str.contains(r'Milita|Aviad|Marin')
prime012['fue_Militar'].value_counts()

fue_Militar
False    120
True      47
Name: count, dtype: int64

In [24]:
prime012.loc[prime012.Nombre.str.contains(r'Freire|Lorenzo|Justin|Velard|Isaac|Dancua|Martos|Arroyo'),'fue_Militar']=True

In [25]:
prime012['fue_Militar'].value_counts()

fue_Militar
False    115
True      55
Name: count, dtype: int64

In [26]:
prime012['cartera']='PCM'
prime012.rename(columns={'Gobierno':'Presidente'},inplace=True)

In [28]:
prime012[prime012.fecha_start>prime012.fecha_end]

,Nombre,Partido,Presidente,Inicio,Fin,fecha_start,fecha_end,fue_Militar,cartera
19,Pedro Paz Soldán y Ureta,NaN,Mariano Ignacio Prado (1.º gob.),12 de octubre de 1868,8 de enero de 1868,1868-10-12,1868-01-08,NaN,PCM

In [29]:
prime012.loc[19,'Inicio']='12 de octubre de 1867'

In [30]:
prime012[['fecha_start','fecha_end']]=prime012[['Inicio','Fin']].map(str_to_date)

In [31]:
prime012.to_pickle('pcm_basic.pkl')

In [43]:
prime012['deFacto']=False
prime012['Provisorio']=False
prime012['replaceVice']=False

In [44]:
prime012.loc[prime012.Gobierno.str.contains(r'Ignacio')]

,Titular,Partido,Gobierno,Inicio,Fin,start,end,Militar,deFacto,Provisorio,replaceVice
15,Mariano Ignacio Prado Ochoa[3],Militar,Mariano Ignacio Prado (I),26 de noviembre de 1865,15 de febrero de 1867,1865-11-26,1867-02-15,True,False,False,False
16,Pedro José Tordoya[4],Clérigo,Mariano Ignacio Prado (I),2 de marzo de 1867,26 de abril de 1867,1867-03-02,1867-04-26,False,False,False,False
17,Pedro Paz Soldán y Ureta,NaN,Mariano Ignacio Prado (I),3 de junio de 1867,1 de septiembre de 1867,1867-06-03,1867-09-01,NaN,False,False,False
18,Luis La Puerta[5],Militar,Mariano Ignacio Prado (I),1 de septiembre de 1867,12 de octubre de 1867,1867-09-01,1867-10-12,True,False,False,False
19,Pedro Paz Soldán y Ureta,NaN,Mariano Ignacio Prado (I),12 de octubre de 1867,8 de enero de 1868,1867-10-12,1868-01-08,NaN,False,False,False
30,Antonio Arenas Merino,NaN,Mariano Ignacio Prado (II),2 de agosto de 1876,26 de agosto de 1876,1876-08-02,1876-08-26,NaN,False,False,False
31,Teodoro La Rosa,NaN,Mariano Ignacio Prado (II),26 de agosto de 1876,1 de junio de 1877,1876-08-26,1877-06-01,NaN,False,False,False
32,Juan Buendía y Noriega,Militar,Mariano Ignacio Prado (II),4 de junio de 1877,13 de mayo de 1878,1877-06-04,1878-05-13,True,False,False,False
33,José Jorge Loayza,NaN,Mariano Ignacio Prado (II),18 de junio de 1878,16 de diciembre de 1878,1878-06-18,1878-12-16,NaN,False,False,False
34,Manuel Yrigoyen Arias,NaN,Mariano Ignacio Prado (II),17 de diciembre de 1878,19 de mayo de 1879,1878-12-17,1879-05-19,NaN,False,False,False
35,Manuel de Mendiburu Bonet,Militar,Mariano Ignacio Prado (II),19 de mayo de 1879,16 de octubre de 1879,1879-05-19,1879-10-16,True,False,False,False
36,Manuel González de la Cotera,Militar,Mariano Ignacio Prado (II),16 de octubre de 1879,23 de diciembre de 1879,1879-10-16,1879-12-23,True,False,False,False

In [45]:
prime012.loc[[15,16,17],'deFacto']=True

In [46]:
prime012.loc[prime012.Gobierno.str.contains(r'Pedro Diez')]

,Titular,Partido,Gobierno,Inicio,Fin,start,end,Militar,deFacto,Provisorio,replaceVice
7,Juan Antonio Ribeyro Estada,NaN,Pedro Diez Canseco,10 de abril de 1863,5 de agosto de 1863,1863-04-10,1863-08-05,NaN,False,False,False
13,Juan Antonio Ugarteche Posadas[2],Militar,Pedro Diez Canseco,26 de septiembre de 1865,6 de noviembre de 1865,1865-09-26,1865-11-06,True,False,False,False
14,Francisco Javier Mariátegui,NaN,Pedro Diez Canseco,6 de noviembre de 1865,28 de noviembre de 1865,1865-11-06,1865-11-28,NaN,False,False,False
20,Antonio Arenas Merino,NaN,Pedro Diez Canseco,22 de enero de 1868,7 de febrero de 1868,1868-01-22,1868-02-07,NaN,False,False,False
21,Antonio Gutiérrez de la Fuente,Militar,Pedro Diez Canseco,7 de febrero de 1868,2 de agosto de 1868,1868-02-07,1868-08-02,True,False,False,False

In [47]:
prime012.loc[prime012.Gobierno.str.contains(r'Pedro Diez'),'replaceVice']=True

In [48]:
prime012.loc[prime012.Gobierno.str.contains(r'Herencia'),'replaceVice']=True

In [49]:
prime012.loc[prime012.Gobierno.str.contains(r'Pezet'),]

,Titular,Partido,Gobierno,Inicio,Fin,start,end,Militar,deFacto,Provisorio,replaceVice
8,Juan Antonio Ribeyro Estada,NaN,Juan Antonio Pezet,5 de agosto de 1863,11 de agosto de 1864,1863-08-05,1864-08-11,NaN,False,False,False
9,Manuel Costas Arce,NaN,Juan Antonio Pezet,11 de agosto de 1864,14 de octubre de 1864,1864-08-11,1864-10-14,NaN,False,False,False
10,José Allende,Militar,Juan Antonio Pezet,14 de octubre de 1864,3 de abril de 1865,1864-10-14,1865-04-03,True,False,False,False
11,Manuel Ignacio de Vivanco,Militar,Juan Antonio Pezet,3 de abril de 1865,12 de julio de 1865,1865-04-03,1865-07-12,True,False,False,False
12,Pedro José Calderón,NaN,Juan Antonio Pezet,12 de julio de 1865,6 de noviembre de 1865,1865-07-12,1865-11-06,NaN,False,False,False

In [50]:
prime012.loc[prime012.Gobierno.str.contains(r'Pezet'),'replaceVice']=True

In [51]:
prime012.loc[prime012.Gobierno.str.contains(r'Landa'),'Provisorio']=True

In [52]:
prime012.loc[prime012.Gobierno.str.contains(r'Piérola'),]#'Provisorio']=True

,Titular,Partido,Gobierno,Inicio,Fin,start,end,Militar,deFacto,Provisorio,replaceVice
39,Aurelio García y García,Marino,Nicolás de Piérola (provisorio),30 de octubre de 1881,28 de noviembre de 1881,1881-10-30,1881-11-28,True,False,False,False
73,Antonio Bentín y La Fuente,Partido Demócrata,Nicolás de Piérola,8 de septiembre de 1895,28 de noviembre de 1895,1895-09-08,1895-11-28,False,False,False,False
74,Manuel Antonio Barinaga,NaN,Nicolás de Piérola,30 de noviembre de 1895,5 de agosto de 1896,1895-11-30,1896-08-05,NaN,False,False,False
75,Manuel Pablo Olaechea Guerrero,Partido Demócrata,Nicolás de Piérola,8 de agosto de 1896,3 de noviembre de 1897,1896-08-08,1897-11-03,False,False,False,False
76,Alejandro López de Romaña Alvizuri,Partido Demócrata,Nicolás de Piérola,25 de noviembre de 1897,23 de diciembre de 1897,1897-11-25,1897-12-23,False,False,False,False
77,Enrique de la Riva Agüero,NaN,Nicolás de Piérola,23 de diciembre de 1897,13 de mayo de 1898,1897-12-23,1898-05-13,NaN,False,False,False
78,José Jorge Loayza,NaN,Nicolás de Piérola,16 de mayo de 1898,8 de septiembre de 1899,1898-05-16,1899-09-08,NaN,False,False,False

In [53]:
prime012.loc[39,'Provisorio']=True

In [54]:
prime012.loc[prime012.Gobierno.str.contains(r'Lizardo'),]#'Provisorio']=True

,Titular,Partido,Gobierno,Inicio,Fin,start,end,Militar,deFacto,Provisorio,replaceVice
40,Juan Manuel Arbaiza,NaN,Lizardo Montero Flores,4 de enero de 1882,4 de septiembre de 1882,1882-01-04,1882-09-04,NaN,False,False,False
41,Camilo N. Carrillo Martínez,Marino,Lizardo Montero Flores,4 de septiembre de 1882,10 de enero de 1883,1882-09-04,1883-01-10,True,False,False,False
42,Manuel Velarde Seoane,Militar,Lizardo Montero Flores,10 de enero de 1883,1 de abril de 1883,1883-01-10,1883-04-01,True,False,False,False
43,Mariano Nicolás Valcárcel,NaN,Lizardo Montero Flores,1 de abril de 1883,1 de octubre de 1883,1883-04-01,1883-10-01,NaN,False,False,False

In [55]:
prime012.loc[prime012.Gobierno.str.contains(r'Lizardo'),'Provisorio']=True

In [56]:
prime012.loc[prime012.Gobierno.str.contains(r'Iglesias'),'deFacto']=True

In [57]:
prime012.loc[prime012.Gobierno.str.contains(r'Consejo')]#,'deFacto']=True

,Titular,Partido,Gobierno,Inicio,Fin,start,end,Militar,deFacto,Provisorio,replaceVice
48,Antonio Arenas Merino[6],NaN,Consejo de Ministros,3 de diciembre de 1885,3 de junio de 1886,1885-12-03,1886-06-03,NaN,False,False,False

In [58]:
prime012.loc[48,['Gobierno','Provisorio']]=['Antonio Arenas Merino',True]

In [59]:
prime012.loc[prime012.Gobierno.str.contains(r'Justin'),'replaceVice']=True

In [60]:
prime012.loc[prime012.Gobierno.str.contains(r'Serap'),'replaceVice']=True

In [61]:
prime012.loc[prime012.Gobierno.str.contains(r'Leguía'),]#'replaceVice']=True

,Titular,Partido,Gobierno,Inicio,Fin,start,end,Militar,deFacto,Provisorio,replaceVice
92,Eulogio I. Romero Salcedo,NaN,Augusto Leguía,24 de septiembre de 1908,8 de junio de 1909,1908-09-24,1909-06-08,NaN,False,False,False
93,Rafael Villanueva Cortez,NaN,Augusto Leguía,8 de junio de 1909,14 de marzo de 1910,1909-06-08,1910-03-14,NaN,False,False,False
94,Javier Prado y Ugarteche,Partido Civil,Augusto Leguía,14 de marzo de 1910,3 de agosto de 1910,1910-03-14,1910-08-03,False,False,False,False
95,Germán Schreiber Waddington,Partido Civil,Augusto Leguía,3 de agosto de 1910,21 de octubre de 1910,1910-08-03,1910-10-21,False,False,False,False
96,José Salvador Cavero Ovalle,Partido Constitucional,Augusto Leguía,3 de noviembre de 1910,27 de diciembre de 1910,1910-11-03,1910-12-27,False,False,False,False
97,Enrique C. Basadre Stevenson,NaN,Augusto Leguía,27 de diciembre de 1910,31 de agosto de 1911,1910-12-27,1911-08-31,NaN,False,False,False
98,Agustín Guillermo Ganoza y Cavero,Partido Civil,Augusto Leguía,31 de agosto de 1911,24 de septiembre de 1912,1911-08-31,1912-09-24,False,False,False,False
113,Mariano Cornejo Zenteno,NaN,Augusto Leguía,4 de julio de 1919,25 de agosto de 1919,1919-07-04,1919-08-25,NaN,False,False,False
114,Melitón F. Porras Osores,NaN,Augusto Leguía,25 de agosto de 1919,6 de diciembre de 1919,1919-08-25,1919-12-06,NaN,False,False,False
115,Germán Leguía y Martínez,Partido Democrático Reformista,Augusto Leguía,6 de diciembre de 1919,7 de octubre de 1922,1919-12-06,1922-10-07,False,False,False,False
116,Julio Ego-Aguirre Dongo,Partido Democrático Reformista,Augusto Leguía,7 de octubre de 1922,12 de octubre de 1924,1922-10-07,1924-10-12,False,False,False,False
117,Alejandrino Maguiña,Partido Democrático Reformista,Augusto Leguía,12 de octubre de 1924,7 de diciembre de 1926,1924-10-12,1926-12-07,False,False,False,False
118,Pedro José Rada y Gamio,Partido Democrático Reformista,Augusto Leguía,7 de diciembre de 1926,12 de octubre de 1929,1926-12-07,1929-10-12,False,False,False,False
119,Benjamín Huamán de los Heros,Partido Democrático Reformista,Augusto Leguía,12 de octubre de 1929,24 de agosto de 1930,1929-10-12,1930-08-24,False,False,False,False
120,Fernando Sarmiento Ramírez,Militar,Augusto Leguía,24 de agosto de 1930,25 de agosto de 1930,1930-08-24,1930-08-25,True,False,False,False

In [62]:
prime012.loc[[113,114,115,116],'deFacto']=True

In [63]:
prime012.loc[prime012.Gobierno.str.contains(r'Benavides'),]#'replaceVice']=True

,Titular,Partido,Gobierno,Inicio,Fin,start,end,Militar,deFacto,Provisorio,replaceVice
104,Pedro E. Muñiz Sevilla,Militar,Óscar R. Benavides (I),16 de mayo de 1914,1 de agosto de 1914,1914-05-16,1914-08-01,True,False,False,False
105,Melitón Carvajal Ambulodegui,Marino (r),Óscar R. Benavides (I),1 de agosto de 1914,22 de agosto de 1914,1914-08-01,1914-08-22,True,False,False,False
106,Aurelio Sousa y Matute,Partido Demócrata,Óscar R. Benavides (I),22 de agosto de 1914,11 de noviembre de 1914,1914-08-22,1914-11-11,False,False,False,False
107,Germán Schreiber Waddington,Partido Civil,Óscar R. Benavides (I),11 de noviembre de 1914,19 de febrero de 1915,1914-11-11,1915-02-19,False,False,False,False
108,Carlos Isaac Abril Galindo,NaN,Óscar R. Benavides (I),19 de febrero de 1915,18 de agosto de 1915,1915-02-19,1915-08-18,True,False,False,False
130,José Matías Manzanilla Barrientos (continuación),NaN,Óscar R. Benavides (II),30 de abril de 1933,29 de junio de 1933,1933-04-30,1933-06-29,NaN,False,False,False
131,Jorge Prado Ugarteche,NaN,Óscar R. Benavides (II),29 de junio de 1933,24 de noviembre de 1933,1933-06-29,1933-11-24,NaN,False,False,False
132,José de la Riva-Agüero y Osma,Partido Nacional Democrático,Óscar R. Benavides (II),24 de noviembre de 1933,18 de mayo de 1934,1933-11-24,1934-05-18,False,False,False,False
133,Alberto Rey de Castro y Romaña,NaN,Óscar R. Benavides (II),18 de mayo de 1934,24 de diciembre de 1934,1934-05-18,1934-12-24,NaN,False,False,False
134,Carlos Arenas y Loayza,None,Óscar R. Benavides (II),24 de diciembre de 1934,18 de mayo de 1935,1934-12-24,1935-05-18,None,False,False,False
135,Manuel E. Rodríguez Dávila,Militar,Óscar R. Benavides (II),18 de mayo de 1935,13 de abril de 1936,1935-05-18,1936-04-13,True,False,False,False
136,Ernesto Montagne Markholz,Militar,Óscar R. Benavides (II),13 de abril de 1936,19 de abril de 1939,1936-04-13,1939-04-19,True,False,False,False
137,Manuel Ugarteche Jiménez,NaN,Óscar R. Benavides (II),20 de abril de 1939,8 de diciembre de 1939,1939-04-20,1939-12-08,NaN,False,False,False

In [64]:
prime012.loc[prime012.Gobierno.str.contains('Benavides (I)',regex=False),'deFacto']=True

In [65]:
prime012.loc[prime012.Gobierno.str.contains('Benavides (II)',regex=False),'Provisorio']=True

In [66]:
prime012.loc[prime012.Gobierno.str.contains('Militar de Gobierno',regex=False)]#,'Provisorio']=True

,Titular,Partido,Gobierno,Inicio,Fin,start,end,Militar,deFacto,Provisorio,replaceVice
121,Gustavo Jiménez Saldías,Militar,Junta Militar de Gobierno,28 de agosto de 1930,24 de noviembre de 1930,1930-08-28,1930-11-24,True,False,False,False
122,Antonio Beingolea Balarezo,Marino,Junta Militar de Gobierno,24 de noviembre de 1930,1 de marzo de 1931,1930-11-24,1931-03-01,True,False,False,False

In [67]:
prime012.loc[prime012.Gobierno.str.contains('Militar de Gobierno',regex=False),['Gobierno','deFacto']]=['Luis Miguel Sánchez Cerro',True]

In [68]:
prime012.loc[prime012.Gobierno.str.contains('Junta Militar',regex=False),['Gobierno','deFacto']]=['Ricardo Pérez Godoy',True]

In [69]:
prime012.loc[prime012.Gobierno.str.contains(r'Velasco|Francisco Morales',regex=True),'deFacto']=True

In [70]:
prime012.loc[prime012.Gobierno.str.contains('Fujimori',regex=True)]#,'deFacto']=True

,Titular,Partido,Gobierno,Inicio,Fin,start,end,Militar,deFacto,Provisorio,replaceVice
177,Juan Carlos Hurtado Miller,Independiente[8],Alberto Fujimori,28 de julio de 1990,20 de febrero de 1991,1990-07-28,1991-02-20,False,False,False,False
178,Carlos Torres y Torres Lara,Independiente,Alberto Fujimori,15 de febrero de 1991,6 de noviembre de 1991,1991-02-15,1991-11-06,False,False,False,False
179,Alfonso de los Heros Pérez-Albela,Independiente,Alberto Fujimori,6 de noviembre de 1991,6 de abril de 1992,1991-11-06,1992-04-06,False,False,False,False
180,Óscar de la Puente Raygada,Independiente,Alberto Fujimori,6 de abril de 1992,28 de agosto de 1993,1992-04-06,1993-08-28,False,False,False,False
181,Alfonso Bustamante y Bustamante,Cambio 90,Alberto Fujimori,28 de agosto de 1993,17 de febrero de 1994,1993-08-28,1994-02-17,False,False,False,False
182,Efraín Goldenberg Schreiber,Cambio 90,Alberto Fujimori,17 de febrero de 1994,28 de julio de 1995,1994-02-17,1995-07-28,False,False,False,False
183,Dante Córdova Blanco,Cambio 90 - Nueva Mayoría,Alberto Fujimori,27 de julio de 1995,3 de abril de 1996,1995-07-27,1996-04-03,False,False,False,False
184,Alberto Pandolfi Arbulú,Cambio 90 - Nueva Mayoría,Alberto Fujimori,3 de abril de 1996,4 de junio de 1998,1996-04-03,1998-06-04,False,False,False,False
185,Javier Valle-Riestra González-Olaechea,Partido Aprista Peruano,Alberto Fujimori,4 de junio de 1998,21 de agosto de 1998,1998-06-04,1998-08-21,False,False,False,False
186,Alberto Pandolfi Arbulú,Cambio 90 - Nueva Mayoría,Alberto Fujimori,21 de agosto de 1998,4 de junio de 1999,1998-08-21,1999-06-04,False,False,False,False
187,Víctor Joy Way Rojas,Cambio 90 - Nueva Mayoría,Alberto Fujimori,3 de enero de 1999,10 de octubre de 1999,1999-01-03,1999-10-10,False,False,False,False
188,Alberto Bustamante Belaúnde,Independiente,Alberto Fujimori,10 de octubre de 1999,29 de julio de 2000,1999-10-10,2000-07-29,False,False,False,False
189,Federico Salas-Guevara Schultz,Independiente,Alberto Fujimori,29 de julio de 2000,21 de noviembre de 2000,2000-07-29,2000-11-21,False,False,False,False

In [71]:
prime012.loc[[180,181,182],'deFacto']=True

In [72]:
prime012.loc[prime012.Gobierno.str.contains('Paniagua',regex=True),'Provisorio']=True

In [73]:
prime012.loc[prime012.Gobierno.str.contains('Vizcarra',regex=True),'replaceVice']=True

In [74]:
prime012.loc[prime012.Gobierno.str.contains('Manuel Me',regex=True),'Provisorio']=True

In [75]:
prime012.loc[prime012.Gobierno.str.contains('Sagasti',regex=True),'Provisorio']=True

In [76]:
prime012.loc[prime012.Gobierno.str.contains('Dina',regex=True),'replaceVice']=True

In [77]:
prime012.loc[prime012.Gobierno.str.contains('Jerí',regex=True),'Provisorio']=True

In [78]:
prime012.loc[prime012.Gobierno.str.contains('Balcá',regex=False),'Provisorio']=True

In [79]:
prime012.to_pickle('statusMinistro_y_Gobs.pkl')

In [1]:
import pandas as pd

prime012=pd.read_pickle('statusMinistro_y_Gobs.pkl')

In [2]:
prime012.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Titular      232 non-null    object
 1   Partido      166 non-null    object
 2   Gobierno     232 non-null    object
 3   Inicio       232 non-null    object
 4   Fin          232 non-null    object
 5   start        232 non-null    datetime64[ns]
 6   end          232 non-null    datetime64[ns]
 7   Militar      169 non-null    object
 8   deFacto      232 non-null    bool
 9   Provisorio   232 non-null    bool
 10  replaceVice  232 non-null    bool
dtypes: bool(3), datetime64[ns](2), object(6)
memory usage: 15.3+ KB

In [3]:
import pandas as pd

# 1. Find the first column where the value is True
prime012['regime'] = prime012[['deFacto', 'Provisorio', 'replaceVice']].idxmax(axis=1)

# 2. If a row is False across all three columns, set it to "constitutional"
all_false = ~prime012[['deFacto', 'Provisorio', 'replaceVice']].any(axis=1)
prime012.loc[all_false, 'regime'] = 'constitutional'

# 3. (Optional) Convert the new column to an actual pandas Category type
prime012['regime'] = prime012['regime'].astype('category')

In [4]:
prime012['regime'].value_counts()

regime
constitutional    154
deFacto            30
Provisorio         24
replaceVice        24
Name: count, dtype: int64

In [6]:
prime012.drop(columns=['deFacto','Provisorio','replaceVice'],inplace=True)
prime012.to_excel("premieres.xlsx")

In [86]:
pd.crosstab(prime012['Militar'], prime012['regime'])

regime   Provisorio  constitutional  deFacto  replaceVice
Militar
False             9              87        8           10
True              7              26       17            5

In [260]:
prime012[prime012['Titular'].duplicated(keep=False)].sort_values(by='Titular').iloc[:20]

,Titular,Partido,Gobierno,Inicio,Fin,start,end
184,Alberto Pandolfi Arbulú,Cambio 90 - Nueva Mayoría,Alberto Fujimori,3 de abril de 1996,4 de junio de 1998,1996-04-03,1998-06-04
186,Alberto Pandolfi Arbulú,Cambio 90 - Nueva Mayoría,Alberto Fujimori,21 de agosto de 1998,4 de junio de 1999,1998-08-21,1999-06-04
30,Antonio Arenas Merino,NaN,Mariano Ignacio Prado (II),2 de agosto de 1876,26 de agosto de 1876,1876-08-02,1876-08-26
20,Antonio Arenas Merino,NaN,Pedro Diez Canseco,22 de enero de 1868,7 de febrero de 1868,1868-01-22,1868-02-07
55,Aurelio Denegri Valega,NaN,Andrés Avelino Cáceres (I),8 de noviembre de 1887,8 de marzo de 1889,1887-11-08,1889-03-08
37,Aurelio Denegri Valega,Partido Civil,Francisco García Calderón Landa,12 de marzo de 1881,18 de julio de 1881,1881-03-12,1881-07-18
102,Aurelio Sousa y Matute,NaN,Guillermo Billinghurst Angulo,17 de junio de 1913,27 de julio de 1913,1913-06-17,1913-07-27
106,Aurelio Sousa y Matute,Partido Demócrata,Óscar R. Benavides (I),22 de agosto de 1914,11 de noviembre de 1914,1914-08-22,1914-11-11
38,Camilo N. Carrillo Martínez,Marino,Francisco García Calderón Landa,18 de julio de 1881,6 de noviembre de 1881,1881-07-18,1881-11-06
41,Camilo N. Carrillo Martínez,Marino,Lizardo Montero Flores,4 de septiembre de 1882,10 de enero de 1883,1882-09-04,1883-01-10
67,Carlos María Elías de la Quintana,Partido Constitucional,Remigio Morales Bermúdez,30 de junio de 1892,3 de marzo de 1893,1892-06-30,1893-03-03
53,Carlos María Elías de la Quintana,Partido Constitucional,Andrés Avelino Cáceres (I),12 de septiembre de 1887,5 de octubre de 1887,1887-09-12,1887-10-05
83,Cesáreo Chacaltana Reyes,Partido Civil,Eduardo López de Romaña,11 de septiembre de 1901,9 de agosto de 1902,1901-09-11,1902-08-09
71,Cesáreo Chacaltana Reyes,NaN,Andrés Avelino Cáceres (II),10 de agosto de 1894,16 de noviembre de 1894,1894-08-10,1894-11-16
204,César Villanueva Arévalo,Independiente,Ollanta Humala,31 de octubre de 2013,24 de febrero de 2014,2013-10-31,2014-02-24
211,César Villanueva Arévalo,Alianza para el Progreso,Martín Vizcarra,2 de abril de 2018,8 de marzo de 2019,2018-04-02,2019-03-08
227,Eduardo Arana Ysa,Independiente,José Jerí,10 de octubre de 2025,12 de octubre de 2025,2025-10-10,2025-10-12
226,Eduardo Arana Ysa,Independiente,Dina Boluarte,14 de mayo de 2025,10 de octubre de 2025,2025-05-14,2025-10-10
100,Enrique Varela Vidaurre,Militar,Guillermo Billinghurst Angulo,24 de diciembre de 1912,24 de febrero de 1913,1912-12-24,1913-02-24
103,Enrique Varela Vidaurre,Militar,Guillermo Billinghurst Angulo,27 de julio de 1913,4 de febrero de 1914,1913-07-27,1914-02-04

In [ ]:
prime012['spell_duration'] = (prime012['end'] - prime012['start']).dt.days
prime012

In [114]:
# True if the NEXT row is the same person OR the PREVIOUS row was the same person
is_consecutive = (prime012['Titular'] == prime012['Titular'].shift(-1)) | \
                 (prime012['Titular'] == prime012['Titular'].shift(1))

# Show only the back-to-back periods with their original index intact
prime012[is_consecutive]

,Titular,Partido,Gobierno,Inicio,Fin,start,end,spell_duration
7,Juan Antonio Ribeyro Estada,NaN,Pedro Diez Canseco,10 de abril de 1863,5 de agosto de 1863,1863-04-10,1863-08-05,117
8,Juan Antonio Ribeyro Estada,NaN,Juan Antonio Pezet,5 de agosto de 1863,11 de agosto de 1864,1863-08-05,1864-08-11,372
208,Mercedes Aráoz Fernández,Peruanos por el Kambio,Pedro Pablo Kuczynski,17 de septiembre de 2017,23 de marzo de 2018,2017-09-17,2018-03-23,187
209,Mercedes Aráoz Fernández,Peruanos por el Kambio,Martín Vizcarra,23 de marzo de 2018,2 de abril de 2018,2018-03-23,2018-04-02,10
225,Eduardo Arana Ysa,Independiente,Dina Boluarte,14 de mayo de 2025,10 de octubre de 2025,2025-05-14,2025-10-10,149
226,Eduardo Arana Ysa,Independiente,José Jerí,10 de octubre de 2025,12 de octubre de 2025,2025-10-10,2025-10-12,2
227,Ernesto Álvarez Miranda,Partido Popular Cristiano[13],José Jerí,14 de octubre de 2025,17 de febrero de 2026,2025-10-14,2026-02-17,126
228,Ernesto Álvarez Miranda,Partido Popular Cristiano[13],José María Balcázar,18 de febrero de 2026,24 de febrero de 2026,2026-02-18,2026-02-24,6

In [35]:
bins = pd.to_datetime(['1857-02-14','1980-07-28','1990-07-28', '2000-11-21', '2025-07-28'])
prime012['era'] = pd.cut(prime012['start'], bins=bins, labels=['D.Before 1980','A. Belaunde to Garcia', 'B. Fujimori', 'C. Paniagua to Boluarte'], right=False)
prime012

,Titular,Partido,Gobierno,Inicio,Fin,start,end,spell_duration,era
0,José María Raygada y Gallo,Militar,Ramón Castilla (2.º gob.),14 de febrero de 1857,13 de mayo de 1858,1857-02-14,1858-05-13,453,D.Before 1980
1,Manuel Ortiz de Zevallos y García,NaN,Ramón Castilla (2.º gob.),13 de mayo de 1858,13 de julio de 1858,1858-05-13,1858-07-13,61,D.Before 1980
2,Miguel de San Román y Meza,Militar,Ramón Castilla (2.º gob.),13 de julio de 1858,24 de octubre de 1858,1858-07-13,1858-10-24,103,D.Before 1980
3,Miguel del Carpio y Melgar,NaN,Ramón Castilla (2.º gob.),28 de octubre de 1858,9 de junio de 1860,1858-10-28,1860-06-09,590,D.Before 1980
4,Juan Antonio Pezet Rodríguez,Militar,Ramón Castilla (2.º gob.),9 de junio de 1860,1 de enero de 1862,1860-06-09,1862-01-01,571,D.Before 1980
...,...,...,...,...,...,...,...,...,...
221,Betssy Chávez Chino,Perú Libre,Pedro Castillo,25 de noviembre de 2022,7 de diciembre de 2022,2022-11-25,2022-12-07,12,C. Paniagua to Boluarte
222,Pedro Angulo Arana,Independiente,Dina Boluarte,10 de diciembre de 2022,21 de diciembre de 2022,2022-12-10,2022-12-21,11,C. Paniagua to Boluarte
223,Alberto Otárola Peñaranda,Independiente,Dina Boluarte,21 de diciembre de 2022,5 de marzo de 2024,2022-12-21,2024-03-05,440,C. Paniagua to Boluarte
224,Gustavo Adrianzén Olaya,Independiente,Dina Boluarte,6 de marzo de 2024,13 de mayo de 2025,2024-03-06,2025-05-13,433,C. Paniagua to Boluarte
225,Eduardo Arana Ysa,Independiente,Dina Boluarte,14 de mayo de 2025,19 de mayo de 2025,2025-05-14,2025-05-19,5,C. Paniagua to Boluarte

In [38]:
prime012.to_parquet('spell_primes_all.parquet')
# prime012.to_excel('spell_primes_all.xlsx',index=False)

ModuleNotFoundError: No module named 'openpyxl'

In [39]:
primesmodel=prime012.copy()

In [40]:
primesmodel=primesmodel[primesmodel.era!='D.Before 1980']

In [41]:
primesmodel['regimeFujimori']=0
primesmodel.loc[primesmodel.era=='B. Fujimori','regimeFujimori']=1

In [42]:
primesmodel['yearEnd']=primesmodel.end.dt.year

In [43]:
primesmodel['speechDay_yearEnd']=pd.to_datetime([str(y)+'07'+'28' for y in primesmodel.yearEnd])

In [44]:
primesmodel['RadiusSpeechDay']=(primesmodel.end-primesmodel.speechDay_yearEnd).dt.days.abs()
primesmodel

,Titular,Partido,Gobierno,Inicio,Fin,start,end,spell_duration,era,regimeFujimori,yearEnd,speechDay_yearEnd,RadiusSpeechDay
167,Manuel Ulloa Elías,Acción Popular,Fernando Belaúnde Terry (II),28 de julio de 1980,9 de diciembre de 1982,1980-07-28,1982-12-09,864,A. Belaunde to Garcia,0,1982,1982-07-28,134
168,Fernando Schwalb López-Aldana,Acción Popular,Fernando Belaúnde Terry (II),9 de diciembre de 1982,10 de abril de 1984,1982-12-09,1984-04-10,488,A. Belaunde to Garcia,0,1984,1984-07-28,109
169,Sandro Mariátegui Chiappe,Acción Popular,Fernando Belaúnde Terry (II),10 de abril de 1984,13 de octubre de 1984,1984-04-10,1984-10-13,186,A. Belaunde to Garcia,0,1984,1984-07-28,77
170,Luis Pércovich Roca,Acción Popular,Fernando Belaúnde Terry (II),13 de octubre de 1984,27 de julio de 1985,1984-10-13,1985-07-27,287,A. Belaunde to Garcia,0,1985,1985-07-28,1
171,Luis Alva Castro,Partido Aprista Peruano,Alan García,28 de julio de 1985,26 de junio de 1987,1985-07-28,1987-06-26,698,A. Belaunde to Garcia,0,1987,1987-07-28,32
172,Guillermo Larco Cox,Partido Aprista Peruano,Alan García,27 de junio de 1987,13 de mayo de 1988,1987-06-27,1988-05-13,321,A. Belaunde to Garcia,0,1988,1988-07-28,76
173,Armando Villanueva del Campo,Partido Aprista Peruano,Alan García,13 de mayo de 1988,15 de mayo de 1989,1988-05-13,1989-05-15,367,A. Belaunde to Garcia,0,1989,1989-07-28,74
174,Luis Alberto Sánchez Sánchez,Partido Aprista Peruano,Alan García,15 de mayo de 1989,30 de septiembre de 1989,1989-05-15,1989-09-30,138,A. Belaunde to Garcia,0,1989,1989-07-28,64
175,Guillermo Larco Cox,Partido Aprista Peruano,Alan García,30 de septiembre de 1989,27 de julio de 1990,1989-09-30,1990-07-27,300,A. Belaunde to Garcia,0,1990,1990-07-28,1
176,Juan Carlos Hurtado Miller,Acción Popular,Alberto Fujimori,28 de julio de 1990,20 de febrero de 1991,1990-07-28,1991-02-20,207,B. Fujimori,1,1991,1991-07-28,158
177,Carlos Torres y Torres Lara,Independiente,Alberto Fujimori,15 de febrero de 1991,6 de noviembre de 1991,1991-02-15,1991-11-06,264,B. Fujimori,1,1991,1991-07-28,101
178,Alfonso de los Heros Pérez-Albela,Independiente,Alberto Fujimori,6 de noviembre de 1991,6 de abril de 1992,1991-11-06,1992-04-06,152,B. Fujimori,1,1992,1992-07-28,113
179,Óscar de la Puente Raygada,Independiente,Alberto Fujimori,6 de abril de 1992,28 de agosto de 1993,1992-04-06,1993-08-28,509,B. Fujimori,1,1993,1993-07-28,31
180,Alfonso Bustamante y Bustamante,Cambio 90,Alberto Fujimori,28 de agosto de 1993,17 de febrero de 1994,1993-08-28,1994-02-17,173,B. Fujimori,1,1994,1994-07-28,161
181,Efraín Goldenberg Schreiber,Cambio 90,Alberto Fujimori,17 de febrero de 1994,28 de julio de 1995,1994-02-17,1995-07-28,526,B. Fujimori,1,1995,1995-07-28,0
182,Dante Córdova Blanco,Cambio 90 - Nueva Mayoría,Alberto Fujimori,27 de julio de 1995,3 de abril de 1996,1995-07-27,1996-04-03,251,B. Fujimori,1,1996,1996-07-28,116
183,Alberto Pandolfi Arbulú,Cambio 90 - Nueva Mayoría,Alberto Fujimori,3 de abril de 1996,4 de junio de 1998,1996-04-03,1998-06-04,792,B. Fujimori,1,1998,1998-07-28,54
184,Javier Valle-Riestra González-Olaechea,Partido Aprista Peruano,Alberto Fujimori,4 de junio de 1998,21 de agosto de 1998,1998-06-04,1998-08-21,78,B. Fujimori,1,1998,1998-07-28,24
185,Alberto Pandolfi Arbulú,Cambio 90 - Nueva Mayoría,Alberto Fujimori,21 de agosto de 1998,4 de junio de 1999,1998-08-21,1999-06-04,287,B. Fujimori,1,1999,1999-07-28,54
186,Víctor Joy Way Rojas,Cambio 90 - Nueva Mayoría,Alberto Fujimori,3 de enero de 1999,10 de octubre de 1999,1999-01-03,1999-10-10,280,B. Fujimori,1,1999,1999-07-28,74
187,Alberto Bustamante Belaúnde,Independiente,Alberto Fujimori,10 de octubre de 1999,29 de julio de 2000,1999-10-10,2000-07-29,293,B. Fujimori,1,2000,2000-07-28,1
188,Federico Salas-Guevara Schultz,Independiente,Alberto Fujimori,29 de julio de 2000,21 de noviembre de 2000,2000-07-29,2000-11-21,115,B. Fujimori,1,2000,2000-07-28,116
189,Javier Pérez de Cuéllar de la Guerra,Unión por el Perú,Valentín Paniagua,22 de noviembre de 2000,28 de julio de 2001,2000-11-22,2001-07-28,248,C. Paniagua to Boluarte,0,2001,2001-07-28,0
190,Roberto Dañino Zapata,Independiente,Alejandro Toledo,28 de julio de 2001,11 de julio de 2002,2001-07-28,2002-07-11,348,C. Paniagua to Boluarte,0,2002,2002-07-28,17
191,Luis Solari de la Fuente,Perú Posible,Alejandro Toledo,12 de julio de 2002,23 de junio de 2003,2002-07-12,2003-06-23,346,C. Paniagua to Boluarte,0,2003,2003-07-28,35
192,Beatriz Merino Lucero,Independiente,Alejandro Toledo,23 de junio de 2003,12 de diciembre de 2003,2003-06-23,2003-12-12,172,C. Paniagua to Boluarte,0,2003,2003-07-28,137
193,Carlos Ferrero Costa,Perú Posible,Alejandro Toledo,15 de diciembre de 2003,15 de agosto de 2005,2003-12-15,2005-08-15,609,C. Paniagua to Boluarte,0,2005,2005-07-28,18
194,Pedro Pablo Kuczynski Godard,Independiente,Alejandro Toledo,16 de agosto de 2005,28 de julio de 2006,2005-08-16,2006-07-28,346,C. Paniagua to Boluarte,0,2006,2006-07-28,0
195,Jorge del Castillo Gálvez,Partido Aprista Peruano,Alan García,28 de julio de 2006,10 de octubre de 2008,2006-07-28,2008-10-10,805,C. Paniagua to Boluarte,0,2008,2008-07-28,74
196,Yehude Simón Munaro,Partido Humanista Peruano,Alan García,14 de octubre de 2008,11 de julio de 2009,2008-10-14,2009-07-11,270,C. Paniagua to Boluarte,0,2009,2009-07-28,17
197,Javier Velásquez Quesquén,Partido Aprista Peruano,Alan García,11 de julio de 2009,13 de septiembre de 2010,2009-07-11,2010-09-13,429,C. Paniagua to Boluarte,0,2010,2010-07-28,47
198,José Antonio Chang Escobedo,Independiente,Alan García,14 de septiembre de 2010,18 de marzo de 2011,2010-09-14,2011-03-18,185,C. Paniagua to Boluarte,0,2011,2011-07-28,132
199,Rosario Fernández Figueroa,Independiente,Alan García,19 de marzo de 2011,28 de julio de 2011,2011-03-19,2011-07-28,131,C. Paniagua to Boluarte,0,2011,2011-07-28,0
200,Salomón Lerner Ghitis,Independiente,Ollanta Humala,28 de julio de 2011,10 de diciembre de 2011,2011-07-28,2011-12-10,135,C. Paniagua to Boluarte,0,2011,2011-07-28,135
201,Óscar Valdés Dancuart,Independiente,Ollanta Humala,10 de diciembre de 2011,23 de julio de 2012,2011-12-10,2012-07-23,226,C. Paniagua to Boluarte,0,2012,2012-07-28,5
202,Juan Jiménez Mayor,Independiente,Ollanta Humala,23 de julio de 2012,29 de octubre de 2013,2012-07-23,2013-10-29,463,C. Paniagua to Boluarte,0,2013,2013-07-28,93
203,César Villanueva Arévalo,Independiente,Ollanta Humala,31 de octubre de 2013,24 de febrero de 2014,2013-10-31,2014-02-24,116,C. Paniagua to Boluarte,0,2014,2014-07-28,154
204,René Cornejo Díaz,Independiente,Ollanta Humala,24 de febrero de 2014,22 de julio de 2014,2014-02-24,2014-07-22,148,C. Paniagua to Boluarte,0,2014,2014-07-28,6
205,Ana Jara Velásquez,Partido Nacionalista Peruano,Ollanta Humala,22 de julio de 2014,2 de abril de 2015,2014-07-22,2015-04-02,254,C. Paniagua to Boluarte,0,2015,2015-07-28,117
206,Pedro Cateriano Bellido,Independiente,Ollanta Humala,2 de abril de 2015,28 de julio de 2016,2015-04-02,2016-07-28,483,C. Paniagua to Boluarte,0,2016,2016-07-28,0
207,Fernando Zavala Lombardi,Independiente,Pedro Pablo Kuczynski,28 de julio de 2016,15 de septiembre de 2017,2016-07-28,2017-09-15,414,C. Paniagua to Boluarte,0,2017,2017-07-28,49
208,Mercedes Aráoz Fernández,Peruanos por el Kambio,Pedro Pablo Kuczynski,17 de septiembre de 2017,23 de marzo de 2018,2017-09-17,2018-03-23,187,C. Paniagua to Boluarte,0,2018,2018-07-28,127
209,Mercedes Aráoz Fernández,Peruanos por el Kambio,Martín Vizcarra,23 de marzo de 2018,2 de abril de 2018,2018-03-23,2018-04-02,10,C. Paniagua to Boluarte,0,2018,2018-07-28,117
210,César Villanueva Arévalo,Alianza para el Progreso,Martín Vizcarra,2 de abril de 2018,8 de marzo de 2019,2018-04-02,2019-03-08,340,C. Paniagua to Boluarte,0,2019,2019-07-28,142
211,Salvador del Solar Labarthe,Independiente,Martín Vizcarra,11 de marzo de 2019,30 de septiembre de 2019,2019-03-11,2019-09-30,203,C. Paniagua to Boluarte,0,2019,2019-07-28,64
212,Vicente Zeballos Salinas,Independiente,Martín Vizcarra,30 de septiembre de 2019,15 de julio de 2020,2019-09-30,2020-07-15,289,C. Paniagua to Boluarte,0,2020,2020-07-28,13
213,Pedro Cateriano Bellido,Independiente,Martín Vizcarra,15 de julio de 2020,6 de agosto de 2020,2020-07-15,2020-08-06,22,C. Paniagua to Boluarte,0,2020,2020-07-28,9
214,Walter Martos Ruiz,Independiente,Martín Vizcarra,6 de agosto de 2020,10 de noviembre de 2020,2020-08-06,2020-11-10,96,C. Paniagua to Boluarte,0,2020,2020-07-28,105
215,Ántero Flores-Aráoz Esparza,Independiente,Manuel Merino,11 de noviembre de 2020,17 de noviembre de 2020,2020-11-11,2020-11-17,6,C. Paniagua to Boluarte,0,2020,2020-07-28,112
216,Violeta Bermúdez Valdivia,Independiente,Francisco Sagasti,18 de noviembre de 2020,28 de julio de 2021,2020-11-18,2021-07-28,252,C. Paniagua to Boluarte,0,2021,2021-07-28,0
217,Guido Bellido Ugarte,Perú Libre,Pedro Castillo,29 de julio de 2021,6 de octubre de 2021,2021-07-29,2021-10-06,69,C. Paniagua to Boluarte,0,2021,2021-07-28,70
218,Mirtha Vásquez Chuquilin,Frente Amplio,Pedro Castillo,6 de octubre de 2021,31 de enero de 2022,2021-10-06,2022-01-31,117,C. Paniagua to Boluarte,0,2022,2022-07-28,178
219,Héctor Valer Pinto,Somos Perú,Pedro Castillo,1 de febrero de 2022,8 de febrero de 2022,2022-02-01,2022-02-08,7,C. Paniagua to Boluarte,0,2022,2022-07-28,170
220,Aníbal Torres Vásquez,Independiente,Pedro Castillo,8 de febrero de 2022,24 de noviembre de 2022,2022-02-08,2022-11-24,289,C. Paniagua to Boluarte,0,2022,2022-07-28,119
221,Betssy Chávez Chino,Perú Libre,Pedro Castillo,25 de noviembre de 2022,7 de diciembre de 2022,2022-11-25,2022-12-07,12,C. Paniagua to Boluarte,0,2022,2022-07-28,132
222,Pedro Angulo Arana,Independiente,Dina Boluarte,10 de diciembre de 2022,21 de diciembre de 2022,2022-12-10,2022-12-21,11,C. Paniagua to Boluarte,0,2022,2022-07-28,146
223,Alberto Otárola Peñaranda,Independiente,Dina Boluarte,21 de diciembre de 2022,5 de marzo de 2024,2022-12-21,2024-03-05,440,C. Paniagua to Boluarte,0,2024,2024-07-28,145
224,Gustavo Adrianzén Olaya,Independiente,Dina Boluarte,6 de marzo de 2024,13 de mayo de 2025,2024-03-06,2025-05-13,433,C. Paniagua to Boluarte,0,2025,2025-07-28,76
225,Eduardo Arana Ysa,Independiente,Dina Boluarte,14 de mayo de 2025,19 de mayo de 2025,2025-05-14,2025-05-19,5,C. Paniagua to Boluarte,0,2025,2025-07-28,70

In [45]:
primesmodel['speechRadius15']=0
primesmodel.loc[primesmodel.RadiusSpeechDay<=15,'speechRadius15']=1
primesmodel['speechRadius30']=0
primesmodel.loc[primesmodel.RadiusSpeechDay<=30,'speechRadius30']=1
primesmodel.head()

,Titular,Partido,Gobierno,Inicio,Fin,start,end,spell_duration,era,regimeFujimori,yearEnd,speechDay_yearEnd,RadiusSpeechDay,speechRadius15,speechRadius30
167,Manuel Ulloa Elías,Acción Popular,Fernando Belaúnde Terry (II),28 de julio de 1980,9 de diciembre de 1982,1980-07-28,1982-12-09,864,A. Belaunde to Garcia,0,1982,1982-07-28,134,0,0
168,Fernando Schwalb López-Aldana,Acción Popular,Fernando Belaúnde Terry (II),9 de diciembre de 1982,10 de abril de 1984,1982-12-09,1984-04-10,488,A. Belaunde to Garcia,0,1984,1984-07-28,109,0,0
169,Sandro Mariátegui Chiappe,Acción Popular,Fernando Belaúnde Terry (II),10 de abril de 1984,13 de octubre de 1984,1984-04-10,1984-10-13,186,A. Belaunde to Garcia,0,1984,1984-07-28,77,0,0
170,Luis Pércovich Roca,Acción Popular,Fernando Belaúnde Terry (II),13 de octubre de 1984,27 de julio de 1985,1984-10-13,1985-07-27,287,A. Belaunde to Garcia,0,1985,1985-07-28,1,1,1
171,Luis Alva Castro,Partido Aprista Peruano,Alan García,28 de julio de 1985,26 de junio de 1987,1985-07-28,1987-06-26,698,A. Belaunde to Garcia,0,1987,1987-07-28,32,0,0

In [46]:
primesmodel['status']=1
primesmodel.loc[primesmodel.end.dt.date>today,'status']=0
primesmodel.tail()

,Titular,Partido,Gobierno,Inicio,Fin,start,end,spell_duration,era,regimeFujimori,yearEnd,speechDay_yearEnd,RadiusSpeechDay,speechRadius15,speechRadius30,status
221,Betssy Chávez Chino,Perú Libre,Pedro Castillo,25 de noviembre de 2022,7 de diciembre de 2022,2022-11-25,2022-12-07,12,C. Paniagua to Boluarte,0,2022,2022-07-28,132,0,0,1
222,Pedro Angulo Arana,Independiente,Dina Boluarte,10 de diciembre de 2022,21 de diciembre de 2022,2022-12-10,2022-12-21,11,C. Paniagua to Boluarte,0,2022,2022-07-28,146,0,0,1
223,Alberto Otárola Peñaranda,Independiente,Dina Boluarte,21 de diciembre de 2022,5 de marzo de 2024,2022-12-21,2024-03-05,440,C. Paniagua to Boluarte,0,2024,2024-07-28,145,0,0,1
224,Gustavo Adrianzén Olaya,Independiente,Dina Boluarte,6 de marzo de 2024,13 de mayo de 2025,2024-03-06,2025-05-13,433,C. Paniagua to Boluarte,0,2025,2025-07-28,76,0,0,1
225,Eduardo Arana Ysa,Independiente,Dina Boluarte,14 de mayo de 2025,19 de mayo de 2025,2025-05-14,2025-05-19,5,C. Paniagua to Boluarte,0,2025,2025-07-28,70,0,0,0

In [47]:
primesmodel.rename(columns={'Titular':'PCM','Partido':'party','Gobierno':'PresidentOfExecutive'},inplace=True)
primesmodel.reset_index(drop=True,inplace=True)
primesmodel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PCM                   59 non-null     object
 1   party                 59 non-null     object
 2   PresidentOfExecutive  59 non-null     object
 3   Inicio                59 non-null     object
 4   Fin                   59 non-null     object
 5   start                 59 non-null     datetime64[ns]
 6   end                   59 non-null     datetime64[ns]
 7   spell_duration        59 non-null     int64
 8   era                   59 non-null     category
 9   regimeFujimori        59 non-null     int64
 10  yearEnd               59 non-null     int32
 11  speechDay_yearEnd     59 non-null     datetime64[ns]
 12  RadiusSpeechDay       59 non-null     int64
 13  speechRadius15        59 non-null     int64
 14  speechRadius30        59 non-null     int64
 15  status                59 non-null     int64
dtypes: category(1), datetime64[ns](3), int32(1), int64(6), object(5)
memory usage: 7.1+ KB

In [49]:
linkLTMData='https://github.com/PULSO-PUCP/premieres/raw/refs/heads/main/df_ltm.xlsx'
primesmodel_ltm=pd.read_excel(linkLTMData,dtype={'resp_pattern':'str'})
primesmodel_ltm.tail()

,PCM,NeverElectoralParticipation,GraduateDegreeInForeignCountry,RelevantActivityPrivateSector,RelevantActivityAcademia,DifferentThanLawyer,resp_pattern,technocrat_trait_ltm
49,Betssy Chávez Chino,0,0,0,0,0,000,-0.771760
50,Pedro Angulo Arana,0,0,0,0,0,000,-0.771760
51,Alberto Otárola Peñaranda,0,0,0,0,0,000,-0.771760
52,Gustavo Adrianzén Olaya,1,1,0,0,0,110,0.839617
53,Eduardo Arana Ysa,0,0,0,0,0,000,-0.771760

In [50]:
primesmodel=primesmodel.merge(primesmodel_ltm.loc[:,['PCM','technocrat_trait_ltm']])
primesmodel

,PCM,party,PresidentOfExecutive,Inicio,Fin,start,end,spell_duration,era,regimeFujimori,yearEnd,speechDay_yearEnd,RadiusSpeechDay,speechRadius15,speechRadius30,status,technocrat_trait_ltm
0,Manuel Ulloa Elías,Acción Popular,Fernando Belaúnde Terry (II),28 de julio de 1980,9 de diciembre de 1982,1980-07-28,1982-12-09,864,A. Belaunde to Garcia,0,1982,1982-07-28,134,0,0,1,-0.233155
1,Fernando Schwalb López-Aldana,Acción Popular,Fernando Belaúnde Terry (II),9 de diciembre de 1982,10 de abril de 1984,1982-12-09,1984-04-10,488,A. Belaunde to Garcia,0,1984,1984-07-28,109,0,0,1,-0.771760
2,Sandro Mariátegui Chiappe,Acción Popular,Fernando Belaúnde Terry (II),10 de abril de 1984,13 de octubre de 1984,1984-04-10,1984-10-13,186,A. Belaunde to Garcia,0,1984,1984-07-28,77,0,0,1,-0.233155
3,Luis Pércovich Roca,Acción Popular,Fernando Belaúnde Terry (II),13 de octubre de 1984,27 de julio de 1985,1984-10-13,1985-07-27,287,A. Belaunde to Garcia,0,1985,1985-07-28,1,1,1,1,-0.233155
4,Luis Alva Castro,Partido Aprista Peruano,Alan García,28 de julio de 1985,26 de junio de 1987,1985-07-28,1987-06-26,698,A. Belaunde to Garcia,0,1987,1987-07-28,32,0,0,1,-0.771760
5,Guillermo Larco Cox,Partido Aprista Peruano,Alan García,27 de junio de 1987,13 de mayo de 1988,1987-06-27,1988-05-13,321,A. Belaunde to Garcia,0,1988,1988-07-28,76,0,0,1,-0.771760
6,Armando Villanueva del Campo,Partido Aprista Peruano,Alan García,13 de mayo de 1988,15 de mayo de 1989,1988-05-13,1989-05-15,367,A. Belaunde to Garcia,0,1989,1989-07-28,74,0,0,1,-0.771760
7,Luis Alberto Sánchez Sánchez,Partido Aprista Peruano,Alan García,15 de mayo de 1989,30 de septiembre de 1989,1989-05-15,1989-09-30,138,A. Belaunde to Garcia,0,1989,1989-07-28,64,0,0,1,-0.771760
8,Guillermo Larco Cox,Partido Aprista Peruano,Alan García,30 de septiembre de 1989,27 de julio de 1990,1989-09-30,1990-07-27,300,A. Belaunde to Garcia,0,1990,1990-07-28,1,1,1,1,-0.771760
9,Juan Carlos Hurtado Miller,Acción Popular,Alberto Fujimori,28 de julio de 1990,20 de febrero de 1991,1990-07-28,1991-02-20,207,B. Fujimori,1,1991,1991-07-28,158,0,0,1,0.839617
10,Carlos Torres y Torres Lara,Independiente,Alberto Fujimori,15 de febrero de 1991,6 de noviembre de 1991,1991-02-15,1991-11-06,264,B. Fujimori,1,1991,1991-07-28,101,0,0,1,0.839617
11,Alfonso de los Heros Pérez-Albela,Independiente,Alberto Fujimori,6 de noviembre de 1991,6 de abril de 1992,1991-11-06,1992-04-06,152,B. Fujimori,1,1992,1992-07-28,113,0,0,1,0.122620
12,Óscar de la Puente Raygada,Independiente,Alberto Fujimori,6 de abril de 1992,28 de agosto de 1993,1992-04-06,1993-08-28,509,B. Fujimori,1,1993,1993-07-28,31,0,0,1,0.122620
13,Alfonso Bustamante y Bustamante,Cambio 90,Alberto Fujimori,28 de agosto de 1993,17 de febrero de 1994,1993-08-28,1994-02-17,173,B. Fujimori,1,1994,1994-07-28,161,0,0,1,1.300456
14,Efraín Goldenberg Schreiber,Cambio 90,Alberto Fujimori,17 de febrero de 1994,28 de julio de 1995,1994-02-17,1995-07-28,526,B. Fujimori,1,1995,1995-07-28,0,1,1,1,0.517994
15,Dante Córdova Blanco,Cambio 90 - Nueva Mayoría,Alberto Fujimori,27 de julio de 1995,3 de abril de 1996,1995-07-27,1996-04-03,251,B. Fujimori,1,1996,1996-07-28,116,0,0,1,0.517994
16,Alberto Pandolfi Arbulú,Cambio 90 - Nueva Mayoría,Alberto Fujimori,3 de abril de 1996,4 de junio de 1998,1996-04-03,1998-06-04,792,B. Fujimori,1,1998,1998-07-28,54,0,0,1,1.300456
17,Javier Valle-Riestra González-Olaechea,Partido Aprista Peruano,Alberto Fujimori,4 de junio de 1998,21 de agosto de 1998,1998-06-04,1998-08-21,78,B. Fujimori,1,1998,1998-07-28,24,0,1,1,-0.771760
18,Alberto Pandolfi Arbulú,Cambio 90 - Nueva Mayoría,Alberto Fujimori,21 de agosto de 1998,4 de junio de 1999,1998-08-21,1999-06-04,287,B. Fujimori,1,1999,1999-07-28,54,0,0,1,1.300456
19,Víctor Joy Way Rojas,Cambio 90 - Nueva Mayoría,Alberto Fujimori,3 de enero de 1999,10 de octubre de 1999,1999-01-03,1999-10-10,280,B. Fujimori,1,1999,1999-07-28,74,0,0,1,0.510705
20,Alberto Bustamante Belaúnde,Independiente,Alberto Fujimori,10 de octubre de 1999,29 de julio de 2000,1999-10-10,2000-07-29,293,B. Fujimori,1,2000,2000-07-28,1,1,1,1,0.839617
21,Federico Salas-Guevara Schultz,Independiente,Alberto Fujimori,29 de julio de 2000,21 de noviembre de 2000,2000-07-29,2000-11-21,115,B. Fujimori,1,2000,2000-07-28,116,0,0,1,-0.771760
22,Javier Pérez de Cuéllar de la Guerra,Unión por el Perú,Valentín Paniagua,22 de noviembre de 2000,28 de julio de 2001,2000-11-22,2001-07-28,248,C. Paniagua to Boluarte,0,2001,2001-07-28,0,1,1,1,-0.771760
23,Roberto Dañino Zapata,Independiente,Alejandro Toledo,28 de julio de 2001,11 de julio de 2002,2001-07-28,2002-07-11,348,C. Paniagua to Boluarte,0,2002,2002-07-28,17,0,1,1,1.300456
24,Luis Solari de la Fuente,Perú Posible,Alejandro Toledo,12 de julio de 2002,23 de junio de 2003,2002-07-12,2003-06-23,346,C. Paniagua to Boluarte,0,2003,2003-07-28,35,0,0,1,-0.771760
25,Beatriz Merino Lucero,Independiente,Alejandro Toledo,23 de junio de 2003,12 de diciembre de 2003,2003-06-23,2003-12-12,172,C. Paniagua to Boluarte,0,2003,2003-07-28,137,0,0,1,0.510705
26,Carlos Ferrero Costa,Perú Posible,Alejandro Toledo,15 de diciembre de 2003,15 de agosto de 2005,2003-12-15,2005-08-15,609,C. Paniagua to Boluarte,0,2005,2005-07-28,18,0,1,1,-0.771760
27,Pedro Pablo Kuczynski Godard,Independiente,Alejandro Toledo,16 de agosto de 2005,28 de julio de 2006,2005-08-16,2006-07-28,346,C. Paniagua to Boluarte,0,2006,2006-07-28,0,1,1,1,1.300456
28,Jorge del Castillo Gálvez,Partido Aprista Peruano,Alan García,28 de julio de 2006,10 de octubre de 2008,2006-07-28,2008-10-10,805,C. Paniagua to Boluarte,0,2008,2008-07-28,74,0,0,1,-0.771760
29,Yehude Simón Munaro,Partido Humanista Peruano,Alan García,14 de octubre de 2008,11 de julio de 2009,2008-10-14,2009-07-11,270,C. Paniagua to Boluarte,0,2009,2009-07-28,17,0,1,1,-0.771760
30,Javier Velásquez Quesquén,Partido Aprista Peruano,Alan García,11 de julio de 2009,13 de septiembre de 2010,2009-07-11,2010-09-13,429,C. Paniagua to Boluarte,0,2010,2010-07-28,47,0,0,1,-0.771760
31,José Antonio Chang Escobedo,Independiente,Alan García,14 de septiembre de 2010,18 de marzo de 2011,2010-09-14,2011-03-18,185,C. Paniagua to Boluarte,0,2011,2011-07-28,132,0,0,1,1.300456
32,Rosario Fernández Figueroa,Independiente,Alan García,19 de marzo de 2011,28 de julio de 2011,2011-03-19,2011-07-28,131,C. Paniagua to Boluarte,0,2011,2011-07-28,0,1,1,1,0.517994
33,Salomón Lerner Ghitis,Independiente,Ollanta Humala,28 de julio de 2011,10 de diciembre de 2011,2011-07-28,2011-12-10,135,C. Paniagua to Boluarte,0,2011,2011-07-28,135,0,0,1,1.300456
34,Óscar Valdés Dancuart,Independiente,Ollanta Humala,10 de diciembre de 2011,23 de julio de 2012,2011-12-10,2012-07-23,226,C. Paniagua to Boluarte,0,2012,2012-07-28,5,1,1,1,-0.233155
35,Juan Jiménez Mayor,Independiente,Ollanta Humala,23 de julio de 2012,29 de octubre de 2013,2012-07-23,2013-10-29,463,C. Paniagua to Boluarte,0,2013,2013-07-28,93,0,0,1,0.839617
36,César Villanueva Arévalo,Independiente,Ollanta Humala,31 de octubre de 2013,24 de febrero de 2014,2013-10-31,2014-02-24,116,C. Paniagua to Boluarte,0,2014,2014-07-28,154,0,0,1,-0.771760
37,René Cornejo Díaz,Independiente,Ollanta Humala,24 de febrero de 2014,22 de julio de 2014,2014-02-24,2014-07-22,148,C. Paniagua to Boluarte,0,2014,2014-07-28,6,1,1,1,0.122620
38,Ana Jara Velásquez,Partido Nacionalista Peruano,Ollanta Humala,22 de julio de 2014,2 de abril de 2015,2014-07-22,2015-04-02,254,C. Paniagua to Boluarte,0,2015,2015-07-28,117,0,0,1,-0.771760
39,Pedro Cateriano Bellido,Independiente,Ollanta Humala,2 de abril de 2015,28 de julio de 2016,2015-04-02,2016-07-28,483,C. Paniagua to Boluarte,0,2016,2016-07-28,0,1,1,1,0.115009
40,Fernando Zavala Lombardi,Independiente,Pedro Pablo Kuczynski,28 de julio de 2016,15 de septiembre de 2017,2016-07-28,2017-09-15,414,C. Paniagua to Boluarte,0,2017,2017-07-28,49,0,0,1,1.300456
41,Mercedes Aráoz Fernández,Peruanos por el Kambio,Pedro Pablo Kuczynski,17 de septiembre de 2017,23 de marzo de 2018,2017-09-17,2018-03-23,187,C. Paniagua to Boluarte,0,2018,2018-07-28,127,0,0,1,0.115009
42,Mercedes Aráoz Fernández,Peruanos por el Kambio,Martín Vizcarra,23 de marzo de 2018,2 de abril de 2018,2018-03-23,2018-04-02,10,C. Paniagua to Boluarte,0,2018,2018-07-28,117,0,0,1,0.115009
43,César Villanueva Arévalo,Alianza para el Progreso,Martín Vizcarra,2 de abril de 2018,8 de marzo de 2019,2018-04-02,2019-03-08,340,C. Paniagua to Boluarte,0,2019,2019-07-28,142,0,0,1,-0.771760
44,Salvador del Solar Labarthe,Independiente,Martín Vizcarra,11 de marzo de 2019,30 de septiembre de 2019,2019-03-11,2019-09-30,203,C. Paniagua to Boluarte,0,2019,2019-07-28,64,0,0,1,0.839617
45,Vicente Zeballos Salinas,Independiente,Martín Vizcarra,30 de septiembre de 2019,15 de julio de 2020,2019-09-30,2020-07-15,289,C. Paniagua to Boluarte,0,2020,2020-07-28,13,1,1,1,0.115009
46,Pedro Cateriano Bellido,Independiente,Martín Vizcarra,15 de julio de 2020,6 de agosto de 2020,2020-07-15,2020-08-06,22,C. Paniagua to Boluarte,0,2020,2020-07-28,9,1,1,1,0.115009
47,Walter Martos Ruiz,Independiente,Martín Vizcarra,6 de agosto de 2020,10 de noviembre de 2020,2020-08-06,2020-11-10,96,C. Paniagua to Boluarte,0,2020,2020-07-28,105,0,0,1,0.122620
48,Ántero Flores-Aráoz Esparza,Independiente,Manuel Merino,11 de noviembre de 2020,17 de noviembre de 2020,2020-11-11,2020-11-17,6,C. Paniagua to Boluarte,0,2020,2020-07-28,112,0,0,1,-0.771760
49,Violeta Bermúdez Valdivia,Independiente,Francisco Sagasti,18 de noviembre de 2020,28 de julio de 2021,2020-11-18,2021-07-28,252,C. Paniagua to Boluarte,0,2021,2021-07-28,0,1,1,1,0.122620
50,Guido Bellido Ugarte,Perú Libre,Pedro Castillo,29 de julio de 2021,6 de octubre de 2021,2021-07-29,2021-10-06,69,C. Paniagua to Boluarte,0,2021,2021-07-28,70,0,0,1,-0.771760
51,Mirtha Vásquez Chuquilin,Frente Amplio,Pedro Castillo,6 de octubre de 2021,31 de enero de 2022,2021-10-06,2022-01-31,117,C. Paniagua to Boluarte,0,2022,2022-07-28,178,0,0,1,-0.771760
52,Héctor Valer Pinto,Somos Perú,Pedro Castillo,1 de febrero de 2022,8 de febrero de 2022,2022-02-01,2022-02-08,7,C. Paniagua to Boluarte,0,2022,2022-07-28,170,0,0,1,0.115009
53,Aníbal Torres Vásquez,Independiente,Pedro Castillo,8 de febrero de 2022,24 de noviembre de 2022,2022-02-08,2022-11-24,289,C. Paniagua to Boluarte,0,2022,2022-07-28,119,0,0,1,0.122620
54,Betssy Chávez Chino,Perú Libre,Pedro Castillo,25 de noviembre de 2022,7 de diciembre de 2022,2022-11-25,2022-12-07,12,C. Paniagua to Boluarte,0,2022,2022-07-28,132,0,0,1,-0.771760
55,Pedro Angulo Arana,Independiente,Dina Boluarte,10 de diciembre de 2022,21 de diciembre de 2022,2022-12-10,2022-12-21,11,C. Paniagua to Boluarte,0,2022,2022-07-28,146,0,0,1,-0.771760
56,Alberto Otárola Peñaranda,Independiente,Dina Boluarte,21 de diciembre de 2022,5 de marzo de 2024,2022-12-21,2024-03-05,440,C. Paniagua to Boluarte,0,2024,2024-07-28,145,0,0,1,-0.771760
57,Gustavo Adrianzén Olaya,Independiente,Dina Boluarte,6 de marzo de 2024,13 de mayo de 2025,2024-03-06,2025-05-13,433,C. Paniagua to Boluarte,0,2025,2025-07-28,76,0,0,1,0.839617
58,Eduardo Arana Ysa,Independiente,Dina Boluarte,14 de mayo de 2025,19 de mayo de 2025,2025-05-14,2025-05-19,5,C. Paniagua to Boluarte,0,2025,2025-07-28,70,0,0,0,-0.771760

In [51]:
primesmodel.to_parquet('spellsModel.parquet')
primesmodel.to_excel('spellsModel.xlsx',index=0)

In [52]:
primesmodel.columns

Index(['PCM', 'party', 'PresidentOfExecutive', 'Inicio', 'Fin', 'start', 'end',
       'spell_duration', 'era', 'regimeFujimori', 'yearEnd',
       'speechDay_yearEnd', 'RadiusSpeechDay', 'speechRadius15',
       'speechRadius30', 'status', 'technocrat_trait_ltm'],
      dtype='object')

In [54]:
primesmodel.loc[:,['PCM', 'start', 'end',
       'spell_duration', 'status', 'technocrat_trait_ltm','regimeFujimori','PresidentOfExecutive']].head()

,PCM,start,end,spell_duration,status,technocrat_trait_ltm,regimeFujimori,PresidentOfExecutive
0,Manuel Ulloa Elías,1980-07-28,1982-12-09,864,1,-0.233155,0,Fernando Belaúnde Terry (II)
1,Fernando Schwalb López-Aldana,1982-12-09,1984-04-10,488,1,-0.771760,0,Fernando Belaúnde Terry (II)
2,Sandro Mariátegui Chiappe,1984-04-10,1984-10-13,186,1,-0.233155,0,Fernando Belaúnde Terry (II)
3,Luis Pércovich Roca,1984-10-13,1985-07-27,287,1,-0.233155,0,Fernando Belaúnde Terry (II)
4,Luis Alva Castro,1985-07-28,1987-06-26,698,1,-0.771760,0,Alan García

In [72]:

from pandas.tseries.offsets import QuarterEnd

def split_spell_row(row):
    intervals = []
    current = row['start'].to_period('Q').to_timestamp(how='start')
    while current <= row['end']:
        stop = min((current + QuarterEnd(0)).normalize(), row['end'])
        intervals.append({
            'id': row['id'],
            'start': current,
            'stop': stop,
            'event': int((stop == row['end']) and row['status'] == 1),
            'regimeFujimori': row['regimeFujimori'],
            'technocrat_trait_ltm': row['technocrat_trait_ltm'],
            'PresidentOfExecutive': row['PresidentOfExecutive']
        })
        current = stop + pd.Timedelta(days=1)
    return intervals

In [70]:
primesmodel.loc[:,['PCM', 'start', 'end',
       'spell_duration', 'status', 'technocrat_trait_ltm','regimeFujimori','PresidentOfExecutive']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PCM                   59 non-null     object
 1   start                 59 non-null     datetime64[ns]
 2   end                   59 non-null     datetime64[ns]
 3   spell_duration        59 non-null     int64
 4   status                59 non-null     int64
 5   technocrat_trait_ltm  59 non-null     float64
 6   regimeFujimori        59 non-null     int64
 7   PresidentOfExecutive  59 non-null     object
dtypes: datetime64[ns](2), float64(1), int64(3), object(2)
memory usage: 3.8+ KB

In [73]:
# Ensure 'start' and 'end' are datetime

primesmodel['id'] = primesmodel.PCM  # if not already assigned

# Generate the quarterly split spells
split_data = []
for _, row in primesmodel.iterrows():
    split_data.extend(split_spell_row(row))

# Create the final Andersen–Gill-style DataFrame
ag_primesmodel = pd.DataFrame(split_data)
ag_primesmodel['duration'] = (ag_primesmodel['stop'] - ag_primesmodel['start']).dt.days
ag_primesmodel['Quarter'] = ag_primesmodel['stop'].dt.to_period('Q').astype(str) 
ag_primesmodel

,id,start,stop,event,regimeFujimori,technocrat_trait_ltm,PresidentOfExecutive,duration,Quarter
0,Manuel Ulloa Elías,1980-07-01,1980-09-30,0,0,-0.233155,Fernando Belaúnde Terry (II),91,1980Q3
1,Manuel Ulloa Elías,1980-10-01,1980-12-31,0,0,-0.233155,Fernando Belaúnde Terry (II),91,1980Q4
2,Manuel Ulloa Elías,1981-01-01,1981-03-31,0,0,-0.233155,Fernando Belaúnde Terry (II),89,1981Q1
3,Manuel Ulloa Elías,1981-04-01,1981-06-30,0,0,-0.233155,Fernando Belaúnde Terry (II),90,1981Q2
4,Manuel Ulloa Elías,1981-07-01,1981-09-30,0,0,-0.233155,Fernando Belaúnde Terry (II),91,1981Q3
...,...,...,...,...,...,...,...,...,...
234,Gustavo Adrianzén Olaya,2024-07-01,2024-09-30,0,0,0.839617,Dina Boluarte,91,2024Q3
235,Gustavo Adrianzén Olaya,2024-10-01,2024-12-31,0,0,0.839617,Dina Boluarte,91,2024Q4
236,Gustavo Adrianzén Olaya,2025-01-01,2025-03-31,0,0,0.839617,Dina Boluarte,89,2025Q1
237,Gustavo Adrianzén Olaya,2025-04-01,2025-05-13,1,0,0.839617,Dina Boluarte,42,2025Q2
238,Eduardo Arana Ysa,2025-04-01,2025-05-19,0,0,-0.771760,Dina Boluarte,48,2025Q2

In [74]:
ag_primesmodel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239 entries, 0 to 238
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    239 non-null    object
 1   start                 239 non-null    datetime64[ns]
 2   stop                  239 non-null    datetime64[ns]
 3   event                 239 non-null    int64
 4   regimeFujimori        239 non-null    int64
 5   technocrat_trait_ltm  239 non-null    float64
 6   PresidentOfExecutive  239 non-null    object
 7   duration              239 non-null    int64
 8   Quarter               239 non-null    object
dtypes: datetime64[ns](2), float64(1), int64(3), object(3)
memory usage: 16.9+ KB

In [75]:
ag_primesmodel.to_parquet('ag_primesmodel.parquet')
ag_primesmodel.to_excel('ag_primesmodel.xlsx',index=0)